### ISSUE TITLE
TrueLink evaluates to false if there is a VariableNode in it?

### ISSUE THREAD

**Issue by leungmanhin** [opencog/atomspace#1253]
For example:
```scm
(use-modules (opencog) (opencog exec))

(cog-evaluate! (Satisfaction (And
  (True (List (Concept "A") (Variable "x"))))))
```
and returns:
```scm
$1 = (stv 0.000000 1.000000)
```

The same happens to GlobNode as well.

**Comment by linas** [comment]
yeah, looks like a bug.   Weird, it goes away if you add and then remove `(List (Concept "A") (Concept "b"))`

**Comment by linas** [comment]
I'll try to look at this "real soon now". Is this a blocking bug?

**Comment by leungmanhin** [comment]
Thanks, it's actually not blocking at the moment.

**Comment by stellarspot** [comment]
It seems the code evaluates to  (stv 0 1) because it contains a variable in it and it is satisfied as  'pattern' clause:
`(cog-evaluate! (Satisfaction (And (True (List (Concept "A") (Variable "x"))))))`

Adding link `(List (Concept "A") (Concept "B"))` still evaluates to (stv 0 1) because there is no True link in the AtomSpace

Adding the True link evaluates to (stv 1 1) as expected:
` (True (List (Concept "A") (Concept "B")))`

Deleting the True link evaluates back to (stv 0 1)
`(DeleteLink (True (List (Concept "A") (Concept "B"))))`

It seems that all works as expected if the Satisfaction link is treated as a 'pattern' clause when it contains variables in it and as 'evaluatable' clause otherwise.

**Comment by linas** [comment]
Interesting. That does indeed seem like the intended behavior. A bit counter-intuitive, I suppose. Viz, this is not a bug.

**Comment by linas** [comment]
thanks for looking at it @stellarspot
