### ISSUE TITLE
Rename OrderedHandleSet or UnorderedHandleSet to HandleSet

### ISSUE THREAD

**Issue by ngeiswei** [opencog/atomspace#1287]
I'd like to rename one of
```
//! a set of handles
typedef std::set<Handle> OrderedHandleSet;
```
or
```
//! a hash table
typedef std::unordered_set<Handle> UnorderedHandleSet;
```
to `HandleSet` to be the default unordered container. `OrderedHandleSet` is ordered by SHA (or content in case of extremely rare SHA clash), so suffice to say that both `OrderedHandleSet` and `UnorderedHandleSet` are, for practical purposes, unordered. Which tempts me to rename `OrderedHandleSet` to `HandleSet`. On the other handle maybe `UnorderedHandleSet` is faster so it should rather have a shorter name, and be the default.

What do you guys think?

**Comment by ngeiswei** [comment]
If we were to rename `UnorderedHandleSet` and replace all `OrderedHandleSet` by it, would we gain performance, or at least not lose anything? Then is there a point to ever use `OrderedHandleSet`?

**Comment by ngeiswei** [comment]
Usage # of `OrderedHandleSet`: 379
Usage # of `UnorderedHandleSet`: 227

across the atomspace and opencog repositories.

**Comment by ngeiswei** [comment]
I replaced all instances of `UnorderedHandleSet` by `OrderedHandleSet` and vice versa.  According to the unit test (I know it's a poor measure of performance but that's what I have) using `OrderedHandleSet` is slightly faster both in the atomspace and opencog repositories

** AtomSpace
```
Using only OrderedHandleSet:
N   min    max    sum     mean    stddev
10  25.43  32.16  310.67  31.067  2.00592

Using only UnorderedHandleSet:
N   min    max    sum     mean    stddev
10  31.39  33.15  321.23  32.123  0.480047
```

**OpenCog
```
Using only OrderedHandleSet:
N   min    max    sum     mean    stddev
10  20.02  29.85  216.59  21.659  2.96234

Using only UnorderedHandleSet:
N   min   max    sum     mean    stddev
10  19.9  24.71  222.28  22.228  1.61384
```

Moreover `OrderedHandleSet` does a bit more because it has an ordering relationship, as a result I can replace all usages of `UnorderedHandleSet` by `OrderedHandleSet` but I cannot replace some (well two only) of usage of `OrderedHandleSet` by `UnorderedHandleSet`.

All this makes me want to get right of `UnorderedHandleSet` usages, rename `OrderedHandleSet` by `HandleSet` and use only this, and if someone wants to `UnorderedHandleSet` in the future it will have to be motivated by something like better performance.

What do you think?

**Comment by ngeiswei** [comment]
I know it seems like a shallow concern but I'm obsessed with simplifying the code...

**Comment by linas** [comment]
I'm not against it, but some words of caution: in certain cases, using unordered i.e. hash-table, can be a performance disaster.  I've seen this in the last few months:  there were two cases:

-- on one case, I had hundreds of millions of hash buckets, and even though each bucket is maybe 50 bytes, this adds up to a lot of RAM.  So btrees use less RAM.
-- in another case, I had hundreds of atoms in the same hash bucket, and iterating over them repeatedly caused a 20x slowdown.

Both of these cases got fixed, but I don't remember where or how. I know I threw away some of the code. I think I tagged teh remiaining case with a message that says something like "this must be a btree not a hash table or else bad things..."  I'll try to grep for this message now.

**Comment by linas** [comment]
It was here: Atom.h lines 161 to 181 It does not use either Ordered nor Unordered handle set.  It does use a map (which is am rbtree) and it has to be a map, not an unordered_map, or else things blow up.

**Comment by linas** [comment]
In general, the rb-trees use less RAM than the hash tables, I think (need to check) and using less RAM is a good thing.

In general, I think that iterating on an rbtree is faster than iterating on a hash table (I think, but would need to check)

Insert for the hash table is almost always faster

In general, for almost almost all uses in the atomspace codebase (e.g. patterns) we iterate over the contain far more often than we insert into it, so using the container with the fastest iteration makes sense.

HOWEVER: in the "good old days", all we had, all we used was the rb-tree.  Then for certain special cases, the hash table was introduced, because it actually was faster/better for some particular use-case.  I recall that adding support for the hash tables was a real pain in the neck, all sorts of stuff had to be jiggered around, but the effort was worth it.  This is like 5-6-8 years ago, I don't recall why.  So, as a general rule, converting all Unordered's to Ordered's does not seem like a good idea, because the switch to sometimes using Unordered's was made on purpose, and it was a painful switch to make.

**Comment by linas** [comment]
But if you just globally rename `OrderedHandleSet` to `HandleSet`, that's fine by me.

**Comment by ngeiswei** [comment]
Excellent feedback, thanks Linas.

**Comment by linas** [comment]
But FWIW, there are probably some (maybe many?) places where using hashes instead of trees, and trees instead of hashes, would be better. But that would need to be done on a case-by-case basis.

**Comment by ngeiswei** [comment]
Understood.
