### ISSUE TITLE
can max link size for 'store-atom' be increased?

### ISSUE THREAD

**Issue by mjsduncan** [opencog/atomspace#1312]
running current code base from guile repl i ran into this while storing a bunch of new atoms:
```
terminate called after throwing an instance of 'opencog::IOException'
  what():  Error: do_store_single_atom: Maxiumum Link size is 330.
```
can the max link size be increased?  would i get this on a bulk save?

**Comment by mjsduncan** [comment]
addendum:  this happened during a for-each loop storing a bunch of atoms and the process continued for a long time after printing the error message but eventually the guile repl crashed and no atoms got stored.

addendum to the addendum:  i'm trying to get the full stack trace, anyone know how i can tell the ubuntu apport system how to find the opencog code to include in it's trace without putting it into a package?

**Comment by linas** [comment]
Points:

* The maximum link size cannot be changed without redesigning the database tables. This would be a major undertaking.

* The reason it ran a long time before halting is because the sql backend is multi-threaded: its got 8 or 12 or 16 threads storing in parallel, each thread has a queue up to 800 atoms long before it blocks and waits to catch up.

* No clue about apport. The stack trace is in the opencog log file, although it won't be very useful. 

* You'll hate me for saying this, but I have to say it anyway: if you have atoms with outgoing sets larger than about 20-ish atoms, you are mis-using the atomspace. OpenCog was never designed for atoms with more than a handful of atoms in the outgoing set: its kind-of buried deep in the architectural philosophy that the outgoing set is small: its in PLN, its in the tools, its in the overall structure and implementation.  In practice "shit happens", so the sql backend allows going up to 330 ... but from a usability point of view, you want to either ignore data that is malformed in this way, or design some alternate format that makes your data accessible and usable.

* A concrete day-to-day example: Instead of using a SetLink to store a whole bunch of stuff,  use instead a MemberLink to indicate set membership.  There are many advantages to MemberLink over SetLink: you can add an remove elements (you can't do that with SetLink), you can search and pattern match (you cannot, for SetLink, except by using GlobNode, which can be klunky and slow, especially for unordered links...) and finally, the MemberLink evades the 330 limit in SQL...

**Comment by linas** [comment]
The reason a stack trace will be boring is that it will probably be in one of the write-back threads, and we already know that.  

You can avoid the crash in two ways:
(1) before each store, check your data and look for <330
(2) wrap the code with a try-catch handler, catch the error, and ignore it.

method (1) is inefficient if the error is very rare. (2) is inefficient if the error is very frequent.

Note that (1) and (2) are cateogory-theoretic duals to one-another. In (1) you have arrows that point from 0 up a ladder to infinity (but never get there, because computation is finite). Versus (2) you have arrows that descend  down from infinity, and never touch the ground, unless something broke up there.  In fact (2) uses exactly ZERO cpu cycles, if there is no error!  Neato!

**Comment by mjsduncan** [comment]
good to know, is that documented anywhere?  the link in question is and
AndLink.  is there a work-around for that?  lots of parts are inherent to
the biology domain...

**Comment by linas** [comment]
* The 300 limit is not documented.  The data-representation issue with SetLink is... ? I assume its in Ben's books, but its also kind-of-ish "well-known" in logic and set theory, in general.  Its sufficiently subtle that it won't just jump out at you.  I'll amend the wiki page now.

* AndLink.   Hmm. That's interesting. You may want to sit down, and invent the AndMemeberLink or something like that.  In fact, my gut instinct (not knowing your data) is that inventing something like AndMemberLink might be the most important, break-through thing you could do, converting your data from bulky, icky hard-to-use AndLinks to nice bite-size pieces that can be assembled and re-assembled at will.   Not joking here.   AndLinks, OrLinks are just like SetLinks, and they have huge negative reprecussions on data analysis.  In fact, I have to thank you for this insight, I have long struggled with certain related issues, and this puts everything into the spotlight.  Wow!

I need to ponder this. Maybe inventing AndMemberLink is the easiest thing but I have to think some more.

**Comment by mjsduncan** [comment]
thanks for the quick feedback!  glad i can contribute...

**Comment by linas** [comment]
I updated http://wiki.opencog.org/w/SetLink to discuss these issues.

**Comment by linas** [comment]
Just to be clear, you should probably get Ben involved, and point out the issue of SetLink vs MemberLink, and point out the same issue exists for AndLink.   You should do this before you munge too much data.

You should also really really look at Rcpp and use that to provide R bindings for the atomspace. I can help a really tiny bit with that. http://dirk.eddelbuettel.com/code/rcpp.html

**Comment by mjsduncan** [comment]
re:  R bindings for atomspace.  i'd def like to take a crack at it but that will have to wait till after the end of summer frenzy for shiny demos ;P
i like your idea of and/or memberlinks.  i think in the short term there are some domain specific work-arounds to limit the size of the andLinks.  ben proposed another option on slack:

"about Atomspace representation of pathways… it seems the semantics we want is sort of like “the pathway P is a set of relationships R1, R2, …, R20” in kinda the same sense that “the human body is a set of organs: brain, heart, lungs, legs, etc.”First of all it seems what we have here is a part of relationship… maybe we wantPartLink
   ConceptNode “heart”
   ConceptNode “human-body”andPartLink
   >relationship<
   >pathway<Extending this a bit it seems to make sense to sayPartitionLink
  ConceptNode “human-body”
  ListLink
     ConceptNode “legs”
     ConceptNode “arms”
     ConceptNode “brain”
     etc.We could also haveOverlappingPartitionLink
   C
   Lif we want to encompass cases where the partition elements in L can overlap, orCoveringLink
   C
   Lif we want to encompass cases where the partition elements in L can overlap, AND the elements in L may encompass some stuff that’s not in CWe could then sayPartitionLink
   ConceptNode “Krebs cycle”
   ListLink
       >relationship 1<
       >relationship 2<
       etc.Now this solves the semantics problem but doesn’t solve the problem of having a long ListLink…To solve this we could do something likePartitionLink
  ConceptNode “human-body”
  PartitionNode “body-partition-1”PartitionElementLink
  PartitionNode “body-partition-1"
  ConceptNode “legs”PartitionElementLink
  PartitionNode “body-partition-1"
  ConceptNode “arms”etc.and similarlyPartitionLink
   ConceptNode “Krebs cycle”
   PartitionNode “krebs-partition-1”PartitionElementLink
   PartitionNode “krebs-partition-1"
   >relationship 1<PartitionElementLink
   PartitionNode “krebs-partition-1”
   >relationship 2<

pretty much, since a ConceptNode in the simplest case represent a set, these Atoms just embody the standard mathematical notion of the partition of a set"

**Comment by linas** [comment]
We already have a http://wiki.opencog.org/w/MemberLink that already does everything that the proposed PartitionLink does. It also has existing PLN rules to go with it, that work correctly, when used in conjunction with SetLink, SubsetLink EquivalenceLink,   SatisfyingSetLink, and so on. So unclear to my why you want to invent a new PartitionLink which .. to me .. sounds identical  to the existing MemberLink.
