### ISSUE TITLE
A different atomspace may be used when calling a GroundedPredicateNode?

### ISSUE THREAD

**Issue by leungmanhin** [opencog/atomspace#1332]
For example:
```scheme
; Populate the atomspace
(List (Concept "A") (Concept "B"))

; Will be called via the GroundedPredicate
(define-public (create-something ATOM)
    ; Print out the atomspace
    (display "as = ") (display (cog-atomspace)) (newline)
    ; Create some atoms
    (List (Concept "X") ATOM)
    (stv 1 1))

(cog-evaluate!
    (Satisfaction
        (TypedVariable
            (Variable "$x")
            (TypeNode "ConceptNode"))
        (And
            (List (Variable "$x") (Concept "B"))
            (Evaluation
                (GroundedPredicate "scm: create-something")
                (List (Variable "$x"))))))
```
And it returns:
```
as = #<atomspace 0x10d7730>
$2 = (stv 1.000000 1.000000)
```
But, the atomspace is different, so the atoms being created cannot be found:
```
scheme@(guile-user)> (cog-atomspace)
$3 = #<atomspace 0x10cde70>
scheme@(guile-user)> (cog-incoming-set (Concept "X"))
$4 = ()
```

However, if I change the `SatisfactionLink` to:
```
(cog-evaluate!
    (Satisfaction
        (And (Evaluation
                 (GroundedPredicate "scm: create-something")
                 (List (Concept "Z"))))))
```
it returns:
```
as = #<atomspace 0x10cde70>
$5 = (stv 1.000000 1.000000)
```
This time the atoms being created can be found:
```
scheme@(guile-user)> (cog-atomspace)
$6 = #<atomspace 0x10cde70>
scheme@(guile-user)> (cog-incoming-set (Concept "X"))
$7 = ((ListLink
   (ConceptNode "X")
   (ConceptNode "Z")
)
)
```
So is it a bug or feature?

**Comment by linas** [comment]
Its a feature. Here's how it works. During the the search, the pattern matcher first tries to match `(List (Variable "$x") (Concept "B"))` and it finds something: for example. `(List (Concept "A") (Concept "B"))` So maybe concept A is a grounding for variable $x.  The only way to be sure is to make sure that the `EvaluationLink` also returns true.  If it does return true, then the answer is accepted.

The evaluation is done in a different, temporary atomspace.  That is because we don't know what the `EvaluationLink` might do -- it might create all sorts of crazy atoms, and you can't put them into the current atomspace, because they might be wrong.  For example, there might be a second EvaluationLink that checks to see if $X < 42, and returns false if it isn't. That means that one would have to "undo" anything the first EvlauationLink did.  The "undo" function is implemented by running everything in a temp atomspace, and throwing it away at the end.   That explains the first query.

The second query is completely different -- there's no variable, there's no need to protect against accidental garbage data.  A temp atomspace is not used.

**Comment by linas** [comment]
Here's a better example of why the temp atomspaces are needed. 
```
(List (Concept "A") (Number 2))
List (Concept "B") (Number 2))
(cog-evaluate!
    (Satisfaction
        (VariableList   (Variable "$x") (Variable "$y")) 
        (And
            (List (Concept "A") (Variable "$x"))
            (List (Concept "B") (Variable "$y"))
            (EqualLink (Number 5) (PlusLink (Variable "$x") (Variable "$y"))))))
```
The perform this search, you have to create the link `(EqualLink (Number 5) (Number 4))` and then evaluate it, to see if it is true or not. You can't do this in the main atomspace.  

As a general rule, the pattern matcher must not, can never pollute the main atomspace with garbage created during searches.  The pattern matcher can never be smart enough to correctly guess what is garbage, and what is good stuff, so **all** evaluations are done in a temporary space.

**Comment by leungmanhin** [comment]
I see, I understand it now, thanks!
