### ISSUE TITLE
PutLink is not considered as evaluatable

### ISSUE THREAD

**Issue by leungmanhin** [opencog/atomspace#1407]
For example,

```scm
(use-modules (opencog) (opencog exec))

; Populate the atomspace
(List (Concept "A") (Concept "B"))

; Create a DefinedPredicateNode
(define-public (always-true x) (stv 1 1))
(Define (DefinedPredicate "some-pred")
        (Lambda (Variable "$y")
                (Evaluation (GroundedPredicate "scm: always-true")
                            (List (Variable "$y")))))

; ... and a SatisfactionLink containing it
(define sat
    (Satisfaction
        (TypedVariable (Variable "$x") (Type "ConceptNode"))
        (And (List (Concept "A") (Variable "$x"))
             (Put (DefinedPredicate "some-pred") (Variable "$x")))))

; Evaluate it
(cog-evaluate! sat)
```

will return `(stv 0 1)`, and just to be sure it will be satisfied if we try again with:

```scm
; Create this
(Put (DefinedPredicateNode "some-pred") (Concept "B"))

; Will return (stv 1 1)
(cog-evaluate! sat)
```

So should we consider `PutLink` as an evaluatable or a virtual link?

**Comment by linas** [comment]
Normally, PutLink is not "evaluatable", because it is not a function that returns a truth value -- instead, it is a function that returns an atom.

However, I guess its OK to implicitly take the TV of the atom that is returned by PutLink. I guess that the code does not do this currently.

To be perfectly, totally correct, you should write:
```
(And (PresentLink (List (Concept "A") (Variable "$x")))
         (TruthValueOfLink (Put (DefinedPredicate "some-pred") (Variable "$x"))))
```

where `PresentLink` returns `(stv 1 1)` whenever `(List (Concept "A") (Variable "$x"))` is in the atomspace, and `TruthValueOfLink` returns the truth value of whatever it wraps up.

The PresentLink exists, but is only partly supported, and is implicitly assumed in many places (it is implicitly assumed in what you wrote).  I like that implicit assumption -- it keeps things simpler. No point in torturing you, forcing you to always write PresentLink.

The `TruthValueOfLink` has not been invented yet. It could be ... but I guess its OK to make it implcit, as well:  So, whenever you want a TV, but have an atom instead, just implicitly take the TV on that atom.

This implicit handling could work for any kind of atom, and not just PutLinks.

**Comment by linas** [comment]
Just to be super-clear:  The `AndLink` expects TV's as input arguments. It can implicitly insert a PresentLink whereever it is needed, and can implicitly insert a TruthValueOfLink whenever that seems appropriate.

Sometimes, it might be confusing about which one to use...  though usually not: If some result is atom-valued, then assume PresentLink. If the result is a predicate, then just take it's TV.

Another possibility is to pretend that there are two different kinds of PutLink.  Once kind returns atoms; the other kind returns TV's.  The second kind is assumed implicitly whenever the PutLink acts on a predicate-like thing.

Anyway, go ahead and change the code in the pattern matcher to automatically get the TV, whenever the PutLink returned a PredicateNode.  That seems like the right thing to do.

**Comment by leungmanhin** [comment]
Got it, thanks! It's not a high priority thing to do at the moment, but I'll give it a try definitely

**Comment by linas** [comment]
I just now realized that my two earlier comments were incorrect.  The pattern matcher, as currently written, is looking for the PutLink; it is NOT trying to execute it.  Thus, it returns false simply because its not finding such a PutLink.  This can be demonstrated as follows - after doing above, do this:
```
(Put (DefinedPredicate "some-pred") (Concept "B"))
(cog-evaluate! sat)
```
Now it will return `(stv 1 1)`

There was an idea, once-upon-a-time, to execute things like PutLink during pattern matching.  This is not done: line 1043 of PatternMatchEngine.cc says `throw RuntimeException(TRACE_INFO, "Not implemented!!");`

One issue is how to tell apart the case where the user is *looking* for a PutLink, vs. when a user wants to actually run it.  Currently there is no way to force execution during pattern matching - you'd need to invent an `DoExecLink` to do that.  However: there is a way to force evaluation during pattern matching: wrap the PutLink with an AndLink, OrLink, NotLink, TrueLink or FalseLink.  Like so:
```
(define sat
    (Satisfaction
        (TypedVariable (Variable "$x") (Type "ConceptNode"))
        (And (List (Concept "A") (Variable "$x"))
             (And (Put (DefinedPredicate "some-pred") (Variable "$x"))))))
```
You can verify that this works y running it on the empty atomspace. Else turn the second And into a Not, and it will return false.


I'm closing this bug, because its a combination of a user-error and a bad reply on my part.
