### ISSUE TITLE
Trivial BindLink crash

### ISSUE THREAD

**Issue by ngeiswei** [opencog/atomspace#1412]
The following
```
(Bind (Variable "$X"))
```
crashes guile.

Sure, it's ill-formed but it should return a user error rather than crashing.

The following
```
(Scope (Variable "$X"))
```
doesn't crash it, instead it returns the following user error
```
ERROR: In procedure cog-new-link:
ERROR: Throw to key `C++-EXCEPTION' with args `("cog-new-link" "Expecting an outgoing set size of at least two; got (VariableNode \"$X\") ; [6809909406030619949][1]\n (/home/nilg/OpenCog/atomspace/opencog/atoms/core/ScopeLink.cc:134)\nFunction args:\n((VariableNode \"$X\")\n)")'.
```
but I think it should allow that, however futile it may seem, it's still a valid construct.

**Comment by linas** [comment]
Nil, `(Bind (Variable "$X"))` is not ill-formed, its perfectly valid.  Silly, but valid. 

There are two possible interpretations for it. One is  `(Bind (And (Variable "$X")))` and this is the intended interpretation.  It says "get me everything in the atomspace".  Curiously, its the same as  `(Bind (And (Variable "$X")(Variable "$X")(Variable "$X")))`  -- repeated clauses in the AndLink should be discarded.

The second interpretation is where its crashing (and where you fixed in in #1413):   `(Bind (VariableList (Variable "$X")) (And))` This is an invalid interpretation, since it leaves the body empty, and I don't know what to do with an empty body.  This is not, and never was the intended interpretation. Variable declarations in a BindLink are optional; if the size of the oset of Bind is just one,  then the oset is the body. Curiously, its the same as `(Bind (VariableList) (And))`.

Perhaps you want to rethink your fix?

**Comment by linas** [comment]
Or at least this: expand the unit test to do something for `(Bind (And (Variable "$X"))) ` and  `(Bind (And (Variable "$X")(Variable "$X")(Variable "$X")))` and `(Bind (VariableList (Variable "$X")) (And)) `  and  `(Bind (VariableList) (And))`

**Comment by linas** [comment]
argh scratch that, my comments do not make sense. Let me rewrite them.

**Comment by linas** [comment]
When I wrote that, I was thinking `GetLink`, not `BindLink`. Sorry.  Let me erase the old comments, and state:

 `(Get (Variable "$X"))` is not ill-formed, its perfectly valid.  Silly, but valid. 

There are two possible interpretations for it. One is  `(Get (And (Variable "$X")))` and this is the intended interpretation.  It says "get me everything in the atomspace".  Curiously, its the same as  `(Get (And (Variable "$X")(Variable "$X")(Variable "$X")))`  -- repeated clauses in the AndLink should be discarded.

The second interpretation is   `(Get (VariableList (Variable "$X")) (And))` This is an invalid interpretation, since it leaves the body empty, and I don't know what to do with an empty body.  This is not, and never was the intended interpretation. Variable declarations in a GetLink are optional; if the size of the oset of Get is just one,  then the oset is the body. Curiously, its the same as `(Get (VariableList) (And))`, which is also non-sensical, as there is nothing to get (impossible to return anything).

**Comment by linas** [comment]
I deleted my comments, and re-wrote one to say `Get` instead of `Bind`.   I have no objections or complaints about the changes made, we're all good, here.
