### ISSUE TITLE
Pattern Matcher small optimization

### ISSUE THREAD

**Issue by linas** [opencog/atomspace#1414]
Several optimizations and alterations for the pattern matcher are possible.

First, `(Get (And (Foo...) (Foo...)))` means exactly the same thing as  `(Get (And (Foo...)))` and as  `(Get (And (Foo...) (Foo...)(Foo...))` - repeated identical clauses can be discarded, as they do not change the outcome.  See wikipedia, "List of rules of inference", this is the "Rule of contraction (or idempotency of entailment) (aka no-deleting theorem)" that is being applied.

Next: we should alter `PresentLink` to automatically remove duplicates (done in #1415), and encourage users to use `PresentLink` instead of `AndLink` for conjoining multiple clauses.

The only remaining allowed use of `AndLink` would then be to write `(Get (And (Present ...) (Absent...)))`.

**Comment by ngeiswei** [comment]
@linas said
> Next: we should alter PresentLink to automatically remove duplicates (done in #1415), and encourage users to use PresentLink instead of AndLink for conjoining multiple clauses.

Amen to that! I'm gonna port all my atomese code to use `PresentLink` instead of `AndLink` whenever possible.

> The only remaining allowed use of AndLink would then be to write (Get (And (Present ...) (Absent...))).

And things like `(And (Present ...) <some-virtual-clauses>)`, right? Virtual clauses should not be wrapped in the `PresentLink`, right?

I wonder if `PresentLink` couldn't be used to get rid of most quotations (I don't think we'll ever completely get rid of it, but he we can make its usage rare it would already be great).

Anyway, I see this as a step forward toward having the pattern matcher explicitly support binary predicates.

**Comment by ngeiswei** [comment]
I meant "support boolean predicates", not binary...

**Comment by linas** [comment]
Closing, fixed in #2659
