### ISSUE TITLE
Forward Chainer doesn't check for complete satisfiability of premises 

### ISSUE THREAD

**Issue by Yidnekachew** [opencog/atomspace#1426]
`(define (return-value x) x)`

```
(define rule
    (BindLink
        (And
            (Inheritance
                (Variable "$a")
                (Variable "$b"))
            (Member
                (Variable "$c")
                (Variable "$d")))

        (ExecutionOutput
                (GroundedSchemaNode "scm: return-value")
                (Inheritance (Variable "$a") (Variable "$b")))))
```

`(cog-fc rule-base (Inheritance (Concept "table") (Concept "furniture")))`

Evaluates to

```
$1 = (SetLink
     (InheritanceLink
        (ConceptNode "table")
        (ConceptNode "furniture")
    )
 )
```

In this case, it will go to the rewrite term without evaluating one of the premises `(Member c d)`. i.e it doesn't check whether membership atom is found in the atomspace.

**Comment by ngeiswei** [comment]
In the absence of type constraints the premise
```
(Member
  (Variable "$c")
  (Variable "$d"))
```
can be itself. You need to specify the types of `$a`, `$b`, `$c` and `$d` in your rule. It is generally very advisable to do that, even without this problem because it can speed up the URE tremendously, due to the type constraints restricting the search space, and atoms being indexed by types in the AtmSpace.

See

https://wiki.opencog.org/w/Category:Type_constructors
https://wiki.opencog.org/w/Type_checker

for more information about type specification and checking.
