### ISSUE TITLE
The Pattern Matcher checks for atoms in a child atomspace when queried from parent atomspace

### ISSUE THREAD

**Issue by Yidnekachew** [opencog/atomspace#1428]
Constant clauses in a child atomspace are expected not to be accessible from the parent atomspace. But, when tested with this scenario, a query run in a parent atomspace checks for constant clauses in the child atomspace. 

```
(define parent-as (cog-atomspace))

(define derived-as (cog-new-atomspace parent-as))

(cog-set-atomspace! derived-as)

(define rule
    (Bind
        (Inheritance (Concept "a") (Concept "b"))

        (Concept "b")))

(cog-set-atomspace! parent-as)

(cog-bind rule)
```
evaluates to
```
$1 = (SetLink
   (ConceptNode "b")
)
```
when the expected result is an empty `(SetLink )`

**Comment by linas** [comment]
You've defined the rule itself in the child atomspace!!

I agree that the behavior here is unexpected.    There are several options:

1) Make `cog-bind` check to see if the rule is defined in the current atomspace, and, if it is not, refuse to work - throw an error message.  (By the way, you should be using `cog-execute`, not `cog-bind`)

2) Make `cog-bind` check to see if the rule is defined in the current atomspace, and, if it is not, copy the rule into the current atomspace.

3) don't change the current behavior.

4) verify that the test-pattern exists in the current atomspace.

I don't like option 2 at all. It's just asking for trouble, it seems.  Option 1 is .. flawed in complicated ways: consistent error checking has some fairly deep side-effects.  You don't like option 3.   I guess you want option 4.

The biggest problem with option 4 is that it forces an additional check to be performed for *every* match, which penalizes everyone, always, for what seems to be a rare and unusual use case.

What is this for? Does this really affect anything? Is there a "real world" use case for this?

**Comment by linas** [comment]
There is also another strange, interesting effect:
```

(use-modules (opencog) (opencog exec))

(define parent-as (cog-atomspace))

(define derived-as (cog-new-atomspace parent-as))

(cog-set-atomspace! derived-as)

(define rule
    (Bind
        (Inheritance (Variable "x") (Concept "b"))

        (Concept "b")))

(cog-set-atomspace! parent-as)

(cog-execute! rule)

(Inheritance (Concept "a") (Concept "b"))

(cog-execute! rule)
```

Both runs of `cog-execute!` return the empty set.  There's an interesting reason for this: the above creates not one, but TWO different copies of `(Concept "b")` -- and they are not equal. The pattern matcher, defined in the child space, discovers that varialbe x is grounded by Concept a, but when it compares the two Concept B's discovers that they are unequal!

**Comment by linas** [comment]
It does not say "apart from the rule" anywhere that I know of.  

One reason for this is that such notions of "apartness" are hard to define for the atomspace: there is only one `(Concept "b")` and it cannot be apart from itself.  Likewise for the InheritanceLink.  When searched for, it matches itself, it finds itself, so the match is true.

Now, constant terms are funny: normally, they should not affect the search, because they are trivially present, and thus always true.  Consider
```
(define rule-1
    (Bind
        (Inheritance (Concept "a") (Concept "b"))
        (Concept "b")))

(define rule-2
    (Bind
        (Present (Inheritance (Concept "a") (Concept "b")))
        (Concept "b")))

(define rule-3
    (Bind
        (Present  )
        (Concept "b")))
```

so rule-1 is what you have.  rule-2 is semantically equivalent (even though different, syntactically). That is, `PresentLink` evaluates to "true" whenever the atom that it wraps exists in the atomspace.  Since `(Inheritance (Concept "a") (Concept "b"))` exists in the atomspace, the present link trivially evaluates to "true" under all conditions.

rule-3 is interesting .. should `(Present empty-set)` evaluate to false, or to true? Apparently, the answer is "true", in the current code: and that makes sense: the empty-set is always a subset of any set; including the atomspace.  Now, the atomspace does not follow all the axioms of set theory; the atomspace is different.  But PresentLink does implement a predicate that answers true/false to the question "is this atom a member of the atomsapce?" which is a set-theory-like question and so it gets a set-theory-like answer.

**Comment by Yidnekachew** [comment]
Well, that's strange for me (a matcher rule matching itself).

Is there anyway I can check membership of constant terms in the atomspace apart from the rule?

**Comment by ngeiswei** [comment]
@linas, we would need option 4. Here's why:

The forward chainer works as follows

1. select a source, such as
```
            (Inheritance
                (Concept "table")
                (Concept "furniture"))
```

2. select a rule, such as
```
(BindLink
        (VariableList
            (TypedVariable (Variable "$a") (Type "ConceptNode"))
            (TypedVariable (Variable "$b") (Type "ConceptNode")))
        (And
            (Inheritance
                (Variable "$a")
                (Variable "$b"))
            (Member
                (Variable "$a")
                (Variable "$b")))
        (ExecutionOutput
            (GroundedSchemaNode "scm: return-value")
            (Inheritance (Variable "$a") (Variable "$b"))))
```

3. unify the rule with the source and rewrite a specialized version of that rule, such as
```
(BindLink
        (And
            (Inheritance
                (Concept "table")
                (Concept "furniture"))
            (Member
                (Concept "table")
                (Concept "furniture")))
        (ExecutionOutput
            (GroundedSchemaNode "scm: return-value")
            (Inheritance (Concept "table") (Concept "furniture"))))
```
This step is important as it restricts the rule's outputs, only generate what the user expects.

As you may see the unification process creates the constant clause
```
            (Member
                (Concept "table")
                (Concept "furniture"))
```
making the rule trivially and wrongly satisfiable. This unification process doesn't occur in the target atomspace so that is not where the problem is. The problem comes from the fact that it gets triggered no matter what.

Of course, if implementing 4 creates a computational overhead, I'd feel bad about it, but would it? It's really not obvious to me.

@linas, if @Yidnekachew and I decide to attempt to implement option 4, how can we properly benchmark the pattern matcher?

If it turns out to be bad, I think we can move that change to the URE only, say by say moving the code in a dedicated call back, to perhaps circumvent this problem altogether by changing the unifier. So it wouldn't be all blocking for us, but I feel this fix ideally belongs to the pattern matcher.

**Comment by linas** [comment]
One solution would be to remove the constant clauses during pattern compilation.  That is what the pattern matcher used to do, but then you argued that constant clauses are meaningful, in some way, so they were kept.  I no longer recall the argument.

Constant clauses are easy to detect and discard during pattern compilation. If you get a null body after constant removal, you know its not satisfiable. Doing it there would avoid penalizing other people.

FWIW, I never understood why you are doing unification. The pattern matcher is a unifier, so unifying into the unifier is just kind of  .. strange. It also seems slow: compiling a pattern is expensive, running a compiled pattern is cheaper.  Every time you build a bindlink, you pay the price of compiling it.

**Comment by ngeiswei** [comment]
I get your point, yes perhaps all overhead can be push back to pattern compilation.

Regarding unification, the reason is that a source itself can be a pattern. That is not obviously useful for the forward chainer, but it becomes absolutely necessary for the backward chainer. Even if you start with a grounded target, this target will create premises made of patterns and applying rules, i.e. to patterns requires unification.
