### ISSUE TITLE
Rename ImplicationScope to ImplicationLambda, etc

### ISSUE THREAD

**Issue by ngeiswei** [opencog/atomspace#1458]
As discussed in #1449 
1. `ImplicationScopeLink` and such should inherit from `LambdaLink`.
2. `ImplicationScopeLink` and such should be renamed `ImplicationLambdaLink` and such.
3. `ScopeLink::partial_substitute` and such should be moved to `LambdaLink`.

**Comment by ngeiswei** [comment]
@linas woudn't `PutLink` inherit from `LambdaLink`? https://github.com/opencog/atomspace/blob/master/opencog/atoms/base/atom_types.script#L263

**Comment by ngeiswei** [comment]
By the same logic I think `ForAllLink` and `ExistsLink` should inherit from `LambdaLink`. Think of it that way, `ForAllLink` and `ExistsLink` are high level functions over predicates, basically one could rewrite this
```
ForAll
  <variables>
  <body>
```
as this
```
ForAllHighLevelLink
  Lambda
    <variables>
    <body>
```
where `ForAllHighLevelLink` is the equivalent of `std::all_of`in C++ http://en.cppreference.com/w/cpp/algorithm/all_any_none_of.

Although `ForAll` and `Exists` are not equal to `Lambda` they certainly use its beta-reduction operation.

**Comment by linas** [comment]
> woudn't `PutLink` inherit from `LambdaLink`

Um, maybe-ish.  PutLink does type-checking and filtering when it performs the substitution.  The LambdaLink does not, the LambdaLink just blindly substitutues, without checking to see if the result is syntactically valid.

**Comment by linas** [comment]
> `ForAll`  and `Exists`

The conversation is going in circles. In principle, it is illegal to perform substitutions in `ForAll` and `Exists`. It becomes legal only in certain forms of predicate logic, where you have a specific rule of inference that allows this: namely the rule of https://en.wikipedia.org/wiki/Universal_instantiation 

So really, the question is: do you want to be neat and clean, and put all rules in the rule engine, or do you want to be sloppy and fast, and put some rules into C++ methods on atoms?   Right now, we do a little bit of both, depending on... some arbitrary historical decisions and mistakes.

If you have an urgent need to squeeze more performance out of PLN, and the only way to do this is to implement "universal instantiation" by making for-all inherit from lambda ... then OK, do the sloppy hack, and acknowledge that its a sloppy hack.  Otherwise, don't do it. 

We are kind of walking a hairy edge of sloppy code and clean code, and I would rather avoid sloppy unless its really really needed.  Its hard to clean up after the fact.

**Comment by linas** [comment]
FYI there is now a `RuleLink` that inherits from `ScopeLink` (and therefor inherits all the assorted methods.  The `ImplicationScope`  inherits from `RuleLink`

The `RuleLink` has the same general form as `BindLink`, but avoids the heavyweight and complex setup of `BindLink`. As a result, `RuleLink is smaller and faster; however, it cannot be used to pattern match.

I think that makes it ideal for things like URE, which uses `BindLink` to specify rules, but never actually executes the `BindLink`.

I'm closing this as a "done already" or "wontfix" or something like that, since I don't see what needs to be done here. Open a new bug report if needed.
