### ISSUE TITLE
Are create*Link really temporary hacks?

### ISSUE THREAD

**Issue by ngeiswei** [opencog/atomspace#1465]
The following have been described as temporary hacks for as long as I can remember

https://github.com/opencog/atomspace/search?utf8=%E2%9C%93&q=%2F%2F+XXX+temporary+hack+...&type=

Can we remove these comments? Or explain why there are temporary hacks?

**Comment by linas** [comment]
The comments can be removed.

Long ago, I think I planned to replace these with maybe some c++ template, or maybe ever overload `operator new` or something crazy like that.  I wanted to make it impossible for people to ever say `new BlahNode("foo")` instead of `createBlahNode("foo")` ... so that overloading operator new would  cause `createBlahNode` to run instead.

Another possibility was to make all atom ctors protected members, and then make `createBlahNode` be a friend.  

Doing all this no longer seems so important, mostly because all the people who insisted on being able to say `new BlahNode("foo")`  are now gone from the project...
