### ISSUE TITLE
CythonUtilities unit test fail

### ISSUE THREAD

**Issue by mjsduncan** [opencog/atomspace#1466]
this test also started failing for me after the `cog-bind!` purge.  i tried running by hand but the [README](https://github.com/opencog/atomspace/blob/master/tests/cython/README.md) is out of date...

```
114/117 Test #114: CythonUtilities ..................***Failed    0.16 sec
Failure: ImportError (/home/mjsd/oc/atomspace/build/opencog/atoms/core/libatomcore.so: undefined symbol: _ZN7opencog9AtomSpace8add_atomERKNS_6HandleEb) ... ERROR

======================================================================
ERROR: Failure: ImportError (/home/mjsd/oc/atomspace/build/opencog/atoms/core/libatomcore.so: undefined symbol: _ZN7opencog9AtomSpace8add_atomERKNS_6HandleEb)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)

  File "/home/mjsd/oc/atomspace/tests/cython/utilities/test_utilities.py", line 3, in <module>
    from opencog.type_constructors import *
ImportError: /home/mjsd/oc/atomspace/build/opencog/atoms/core/libatomcore.so: undefined symbol: _ZN7opencog9AtomSpace8add_atomERKNS_6HandleEb

----------------------------------------------------------------------
```

**Comment by linas** [comment]
:-(  I wonder why it passes for me.

There are several undefined symbols in libatomcore, which cannot be resolved due to circular dependencies.   I tried to resolve these but they are hard.   Solving it this way requires:

Step one:  remove the unifier from libatomutils; it is one major source of circular dependencies

Step two: alter libatomutils so that it no longer depends on libatomcore:  this issue first arose when the routines in the libatomutils were replaced by algos living in the free-variables code.   

I kind-of have to blame Nil for introducing both of these circular dependencies. I tried to fix them very recently, spent a whole day on this ... but its hard,  find them all is like a game of whack-a-mole.
-----
The alternative is to make cython smarter, and have it also load all the other modules it needs, so that it can resolve the dependencies itself.  I don't know if this is easy or hard...

**Comment by linas** [comment]
I did a `make clean` just to be sure, it still passes.

**Comment by ngeiswei** [comment]
@linas have you tried to remove `/usr/local/lib/opencog`?

Regarding unify, I actually wanted to move it out of libatomutils, be in its own library. If it fixes circular dependencies, it's even better.

**Comment by linas** [comment]
I removed `/usr/local/lib/opencog` and also `/usr/local/include/opencog`, rebuilt cogutils and atomspace, and this test still passes  .. although `MultiAtomSpaceUTest` still fails.

**Comment by mjsduncan** [comment]
CythonUtilities still fails for me (on ubuntu 16.04 and 14.04) but MultiAtomSpaceUTest still passes after linus' fix!

**Comment by linas** [comment]
Is this still an issue? I think it got fixed maybe a week ago, when the shared-lib structures got reorganized.

**Comment by mjsduncan** [comment]
it was failing till yesterday.  then after one of the commits building atomspace failed completely on 14.04 untill i installed libgmp3-dev for a missing include file gmp.h .  after that CythonUtilities passed but CythonGuile gives a segfault.  i installed libgmp3-dev on ubuntu 16.04 and the same thing is now happening, CythonUtilities passes but CythonGuile gives a segfault.  16.04 was still building successfully without libgmp3-dev, and i can't be sure if adding that did the trick or if it was one of the new recent commits that did it.  i'll file a new issue for CythonGuile, unless there is some python cache that i can try to clear similar to the guile/ccache ?

**Comment by linas** [comment]
there is no reason for needing `gmp.h` that I know of. There's no multi-precision anywhere in opencog, so installing `gmp.h` is just strange.

CythonGuile probably crashes because new atom types were added, and CythonGuile isn't smart enough to recompile.  Try starting guile by hand, and then `(lod-modules (opencog))` once - that should trigger a recompile.
