### ISSUE TITLE
automatic insertion into atomspace?

### ISSUE THREAD

**Issue by ngeiswei** [opencog/atomspace#1471]
I see these types of comments

https://github.com/opencog/atomspace/blob/master/opencog/atoms/core/ArityLink.cc#L70

I think it would be wrong to automatically add the results to the atomspace of the function, as the following comment seems to suggest
```c++
	// XXX This is probably wrong ... if the as is null, we should
	// probably use the atomspace that this link is in, right?
```

Actually I think the `execute` methods should not take any optional AtomSpace in argument, instead they should create all results in RAM, then it would be up to the callers, like `Instantiator::walk_tree`, to add these results however they want.

It seems it would not only make the code simpler, but it would allow more flexibility, such as allowing the pattern matcher to write the results in a different atomspace than the queried one.

**Comment by linas** [comment]
I think I agree in principle; there are some practical difficulties. These include:

1) If the link being executed has a GetLink or BindLink under it, those need to be run in some atomspace, and not in thin air. So for example, if ArityLink is used to count the number of results returned by the Get.

2) If there are GPN's that look at TV's or other values: that GPN has to use the TV of the atom in the atomspace, instead of the DEFAULT_TV that the free-floating atom would typically have.

**Comment by linas** [comment]
OK, I just now attempted to do this.  Viz, remove the AtomSpace argument from FunctionLink. It's almost doable, except for one place: MapLink, which explicitly requires that argument, because it works in a scratch atomspace.  I'll see if I can fix that.

**Comment by linas** [comment]
I think this is fixed in #1486 This has nothing to do with the pattern matcher: it was always free to write results in some other atomspace, and in fact, that is its general mode of operation - it uses scratch spaces throughout. If you were getting atoms in the wrong atomspace, the issue was that the correct scratch space was not being used somewhere.

The two meta-issue 1. and 2. listed above are still in effect.  The tangle of code involving those is now segregated to `Instantiator.cc`

**Comment by ngeiswei** [comment]
I came to the same conclusion about `MapLink` (requires an AtomSpace), I think even this is addressable but I guess it's better to keep that for another issue, thus I'm closing.

**Comment by linas** [comment]
MapLink is hhairy, but the real show-stoppers are:

3) DeleteLink: which atomspace is this supposed to be deleted from?

4) equality/inequality of truth values: if you don't poke an atom into a an atomspace, you won't know if you've got the "right" atom with the "right" TV on it (as opposed to the default TV that freshly created atoms have)
