### ISSUE TITLE
Crash ill-formed PutLink

### ISSUE THREAD

**Issue by ngeiswei** [opencog/atomspace#1496]
The following ill-formed `PutLink` crashes when executed
```scheme
(PutLink
  (LambdaLink
    (VariableNode "$X")
    (EvaluationLink
      (PredicateNode "P")
      (VariableNode "$X")
    )
  )
  (LambdaLink
    (UnquoteLink
      (VariableNode "$x")
    )
    (UnquoteLink
      (VariableNode "$g")
    )
  )
)
```
Instead of crashing it should raise an exception.

**Comment by linas** [comment]
Fixed in #1497 This is a great example of exactly why I dislike quote-unquote: they violate some notion of "closure" -- that is, when an atom that is perfectly valid, it should never have invalid sub-trees under it.  Nothing else in atomese has this property.  This is not true for QuoteLink, and I find that highly objectionable and undesirable.

**Comment by ngeiswei** [comment]
Actually I don't think the fix is right, it should allow the user to construct such an hypergraph, because it might be get wrapped in a `QuoteLink` and then be a valid construct (I don't like that either but until we replace `QuoteLink` by something better we have to deal with it). Instead it should simply ignore the check.

My problem wasn't about building it but about running it, `(cog-execute! (PutLink ...`

**Comment by ngeiswei** [comment]
I've added a unit test for the problem I initially wanted to report.

**Comment by ngeiswei** [comment]
I was hoping this https://github.com/ngeiswei/atomspace/commit/4fcf8edffbe08cfdc639616c2d3f1a8a5f42b8a6 would fix it but oddly it doesn't.

**Comment by ngeiswei** [comment]
No longer an issue.
