### ISSUE TITLE
Strange behavior of NotLink

### ISSUE THREAD

**Issue by shujingke** [opencog/atomspace#1598]
NotLink is a virtual link, maybe it is not supposed to to represent a negative truth in the Atomspace, but when it does, and it is at the root of the pattern implicant (second argument of the BindLink), the result is weird:

```
;; knowledge base:
(Not
     (Evaluation
       (Predicate "keep-pet")
       (List
     (Concept "German")
         (Concept "dog")))
   )
;; rule:
(define nooo
   (BindLink
    (VariableNode "$A")
    (NotLink
      (VariableNode "$A")
    )
    (VariableNode "$A")
   )
)

;;Execute this BindLink and I got the werid result below: (is this normal?)
(SetLink
    (VariableNode "$A")
)
```

Also Nil tried below:
```
(define nooo
  (BindLink
    (TypedVariable (VariableNode "$A") (Type "EvaluationLink"))
    (NotLink
      (VariableNode "$A")
    )
    (VariableNode "$A")
  )
)
```

and it outputs the same, which is even less normal.

**Comment by linas** [comment]
Looking at this now. NotLink support in the pattern matcher has always been incomplete and unfinished.  One   problem  that its not clear what "not" means. It can mean "isn't true", but it can also mean "doesn't exist" which are similar but not the same.  So for example, 
```
(define n2
   (BindLink
    (VariableNode "$A")
    (Exists (NotLink (VariableNode "$A")))
    (VariableNode "$A")))
```
is another reasonable query, and I believe that is what you really wanted to ask. Unfortunately, n2 is also broken, but in a different way.  I'm looking now.

**Comment by linas** [comment]
OK, So #1602 fixes this. But, with various caveats and points:

1) Since you are returning `(VariableNode "$A")` it would be prettier and more readable to use GetLink instead of BindLink.  The BindLink as written is OK, it just looks awkward.

2) You really need to declare a variable type; for example: `(TypedVariable (Variable "$A") (TypeNode "EvaluationLink"))`  Without this, you risk infinite loops, as the variable can match anything, including itself.  Actually there is a warning for this printed into the log file, but you probably did not see it there. I would like to have the warning converted into an actual error, so that you would see it, but unfortunately, this is not possible, since  apparently the URE does soething I don't understand, and there are now unit tests that depend on and test this broken behavior. Oh well.

3) The evaluation link is evaluatable, and so is the NotLink. That means that the result of the query depends on the TV on the EvaluationLink.  If you only want to see if the EvaluationLink is in the atomspace, instead of looking at its TV, then you need to search for `(Present (Not (Variable "$A")))` -- the PresentLink prevents the TV from being computed.

**Comment by shujingke** [comment]
I think NotLink means "isn't true" in my understanding, since there is "AbsentLink" as well which means  "doesn't exist".  But even for the meaning "isn't true", it can still mean different things:

1. Not absolutely-true 
2. strength value < 0.5 
3. confident value < 0.5
4. And so on...

So I think it is ambitious to use it in rules unless we give it clear definition. Currently I use directly tv comparison in the rule instead for checking negations.

**Comment by linas** [comment]
As implemented, the pattern matcher supports crisp, classical predicate logic, whenever it sees the atoms And, Or Not, SequentialAnd, SequentialOr, Predicatenode, GroundedPredicateNode, DefinedPredicateNode.  The logic is made crisp by interpreting TV's with strength> 0.5 as true, and otherwise false.  The confidence value is ignored.

The code was written to allow probabilistic logic (Bayesian probability aka measure theory) support to be easily added: for example, by using SetIntersectionLink, SetUnionLink, SetComplementLink instead of AndLink, OrLink, NotLink, using the obvious formulas from measure theory. So far, no one has been interested in that.  One could of course, support yet other formulas, e.g. the PLN formulas, which need both strength and confidence, but - again - no one has expressed interest in this.

PresentLink and AbsentLink implement intuitionist logic on the atomspace.  The LgAndLink and LgOrLink implement a subset of linear logic, related to pregroup logic, related to the logic of simplex categories.

I do not have any plans for supporting any kind of general logic: e.g. the Heyting algebras, coherent logic, dependent types, etc.  The pattern matcher currently supports three different logics, could "easily" support two more, but the general use case remains unclear.

**Comment by linas** [comment]
Closing. If there are other issues, please open a new bug report.
