### ISSUE TITLE
Hash collision between atoms

### ISSUE THREAD

**Issue by ngeiswei** [opencog/atomspace#1625]
The following, rather similar but different, scope links have the same hash
```
      (LambdaLink
        (VariableList
          (VariableNode "$PM-565f9848") ; [3051023176053525644][1]
          (VariableNode "$PM-164e1b09") ; [5471808729358182586][1]
        ) ; [14860589810072735837][1]
        (ImplicationLink
          (InheritanceLink
            (VariableNode "$PM-565f9848") ; [3051023176053525644][1]
            (VariableNode "$PM-164e1b09") ; [5471808729358182586][1]
          ) ; [14496589888635524888][1]
          (InheritanceLink
            (VariableNode "$PM-565f9848") ; [3051023176053525644][1]
            (VariableNode "$PM-164e1b09") ; [5471808729358182586][1]
          ) ; [14496589888635524888][1]
        ) ; [14820499435918140327][1]
      ) ; [9607689818773494246][1]
```
```
      (LambdaLink
        (VariableList
          (VariableNode "$PM-164e1b09") ; [5471808729358182586][1]
          (VariableNode "$PM-164e1b09-47189056") ; [7316959371767173953][1]
        ) ; [13581315379842424018][1]
        (ImplicationLink
          (InheritanceLink
            (VariableNode "$PM-164e1b09") ; [5471808729358182586][1]
            (VariableNode "$PM-164e1b09") ; [5471808729358182586][1]
          ) ; [11372164815996221702][1]
          (InheritanceLink
            (VariableNode "$PM-164e1b09-47189056") ; [7316959371767173953][1]
            (VariableNode "$PM-164e1b09-47189056") ; [7316959371767173953][1]
          ) ; [9543682399918497524][1]
        ) ; [17442028992361417521][1]
      ) ; [9607689818773494246][1]
```

**Comment by ngeiswei** [comment]
Some more background about that issue in case someone not familiar with OpenCog decides to take it on.

Hash collision is unavoidable in principle and, when it happens, is well handled by OpenCog, still we would like to minimize it in practice. Here's why
1. Collision is costly to manage, for instance when comparing 2 different atoms, if they happen to have different hashes, comparison is instantaneous. Otherwise it must recursively compare their outgoings, etc.
2. Since collision is rare, seeing the same hashes on 2 different atoms tends to catch the attention of the user/dev and raises a false alarm, thus wasting his/her time.

Here are a some guidelines to help to fix this issue
1. Add a unit test for that issue, `ScopeLinkUTest::test_compute_hash_3()` next to https://github.com/opencog/atomspace/blob/master/tests/atoms/ScopeLinkUTest.cxxtest#L159
2. [Optional] Run it in a debugger to figure out what it's doing (carefully read https://wiki.opencog.org/w/Development_standards#GDB to be able to run it on opencog).
3. Come up with a formula that would generate 2 different hashes for this case.

The code you'll need to modify will likely be in https://github.com/opencog/atomspace/blob/master/opencog/atoms/core/ScopeLink.cc#L240 or https://github.com/opencog/atomspace/blob/master/opencog/atoms/core/ScopeLink.cc#L283. Don't take my words for it, it's just a suggestion! Also, make sure your changes don't worsen other cases. Absolutely feel free to add more unit tests next to `test_compute_hash_3()` for the cases you're not sure of.

**Comment by ngeiswei** [comment]
Here's some more collision
```
    (ListLink
      (ListLink
        (VariableNode "$X") ; [6809953386495729144][1]
        (ConceptNode "soda drinker") ; [918100154518884601][1]
        (VariableNode "$W") ; [3551762524734464419][1]
      ) ; [14473380265392838865][1]
      (EvaluationLink (stv 1.000000 1.000000)
        (PredicateNode "minsup") ; [7652255624949679335][1]
        (ListLink
          (LambdaLink
            (VariableList
              (VariableNode "$X") ; [6809953386495729144][1]
              (VariableNode "$Z") ; [5473937806047228437][1]
              (VariableNode "$W") ; [3551762524734464419][1]
            ) ; [12703954679464070855][1]
            (AndLink
              (InheritanceLink
                (VariableNode "$X") ; [6809953386495729144][1]
                (VariableNode "$Z") ; [5473937806047228437][1]
              ) ; [9416207393950424927][1]
              (InheritanceLink
                (VariableNode "$X") ; [6809953386495729144][1]
                (VariableNode "$W") ; [3551762524734464419][1]
              ) ; [16717404149492436717][1]
              (InheritanceLink
                (VariableNode "$X") ; [6809953386495729144][1]
                (ConceptNode "ugly") ; [4140072183546835984][1]
              ) ; [17305713808304808282][1]
            ) ; [9791754264062313680][1]
          ) ; [13901025108701717330][1]
          (ConceptNode "texts") ; [2601010213486140193][1]
          (NumberNode "5.000000") ; [2039561946621192489][1]
        ) ; [15371690046944129881][1]
      ) ; [11346760901924129231][1]
    ) ; [9870226789692348477][1]
```
```
    (ListLink
      (ListLink
        (VariableNode "$X") ; [6809953386495729144][1]
        (ConceptNode "ugly") ; [4140072183546835984][1]
        (VariableNode "$W") ; [3551762524734464419][1]
      ) ; [10117992781057924808][1]
      (EvaluationLink (stv 1.000000 1.000000)
        (PredicateNode "minsup") ; [7652255624949679335][1]
        (ListLink
          (LambdaLink
            (VariableList
              (VariableNode "$X") ; [6809953386495729144][1]
              (VariableNode "$Z") ; [5473937806047228437][1]
              (VariableNode "$W") ; [3551762524734464419][1]
            ) ; [12703954679464070855][1]
            (AndLink
              (InheritanceLink
                (VariableNode "$X") ; [6809953386495729144][1]
                (VariableNode "$Z") ; [5473937806047228437][1]
              ) ; [9416207393950424927][1]
              (InheritanceLink
                (VariableNode "$X") ; [6809953386495729144][1]
                (ConceptNode "soda drinker") ; [918100154518884601][1]
              ) ; [14083741779276856899][1]
              (InheritanceLink
                (VariableNode "$X") ; [6809953386495729144][1]
                (VariableNode "$W") ; [3551762524734464419][1]
              ) ; [16717404149492436717][1]
            ) ; [14526306756683566201][1]
          ) ; [10679053079673765947][1]
          (ConceptNode "texts") ; [2601010213486140193][1]
          (NumberNode "5.000000") ; [2039561946621192489][1]
        ) ; [11525524440319880834][1]
      ) ; [16723967332154655992][1]
    ) ; [9870226789692348477][1]
```
They are not scope links though, so obviously the fixes wouldn't be in the `ScopeLink` class and the unit tests wouldn't be added in `ScopeLinkUTest`, I don't know where at that point.

**Comment by linas** [comment]
Did we establish the root cause of the collisions? Pull req #1638 purports to fix them, but all it really seems to do is to just use a different hash function; that alone should be ineffective in changing anything.

It might be possible that the hash collisions have something to do with unordered links (the AndLink).  I just looked at #1638, and it is not clear that it is handling the unordered links correctly.  Hmm. Let me take a closer look...

**Comment by linas** [comment]
I think I understand the reason for the hash collisions. The problem has to do with which happens to unordered link (such as AndLink), when it has different different, but alpha-equivalent contents. So: unordered links get put into some arbitrary, but deterministic order, depending on their contents.  However, the sort order for `(And A B C)` will probably be different from the sort order for `(And X Y Z)`,  Now imagine that A B C is ala-equivalent to X Y Z.  This implies that we want   `(And A B C)` to hash to the same value as `(And X Y Z)` - viz, this is an "intentional" hash collision. Its not really a collision- they really do need to be considered identical.

To guarantee this outcome, I wrote the code in a certain way.  As a result, there could be (would be) more accidental hash collisions than normal.  I was trading off code-correctness for hash collisions. 

I do NOT recall if I created a unit test for all this! (bad bad me)  The risk is that pull req #1638 doesn't get this right. I can't quite tell, without spending a few more hours on it, and trying to create some funky unit tests, designed to try to fool the hashing algo into giving wrong answers.   So, are we really sure that the pull req is doing the right thing, here?

**Comment by ngeiswei** [comment]
@linas the problem was that, in case of unordered links, the resulting hash was only modified by additions, see https://github.com/opencog/atomspace/blob/master/opencog/atoms/core/ScopeLink.cc#L336 which has the advantage of being commutative (thus invariant to permutation) but the inconvenient of being far from injective. I believe the fix improves the "injectiveness" of the encoding while still being maintaining the invariance to permutation.

**Comment by ngeiswei** [comment]
That is said if you want to come up with funky unit tests that attempt to fool the hash function, that would still be great. I did test it on thousands of auto generated scopes with no collision, besides that I'm not that confident about it, though confident enough to merge #1638 as I have observed that it represents an improvement.

**Comment by linas** [comment]
So is this now fixed, or are there outstanding issues, still?

**Comment by ngeiswei** [comment]
I think it's fixed. I didn't close it because you, @linas, expressed the desire to create funky unit tests to fool the hashing algo. Fabian Klopfer said he might give it a try but it's not sure. Regardless of that I think it can be closed.

**Comment by linas** [comment]
Yeah, OK, I actually did try to create some awkward hashes, but, indeed, I wasn't able to dream up anything that didn't work.  I didn't try that hard; instead I somehow decided that the algo worked correctly, so I gave up.

I'll leave this open a while longer in case Fabian chimes in.

**Comment by noskill** [comment]
If hash function is somewhat working, then for 64bit hash probability of collision is too small if you test it on 1000-10000 random items. Taking a lot of real data and measuring probability of collision is good test for a hash function. @ngeiswei Could you share the code for generating random scope links? I would like to measure probability of collision on random data.

**Comment by ngeiswei** [comment]
Agreed @noskill , besides I didn't exactly test it on random scope links, but rather on scope links generated while running this unit test https://github.com/opencog/opencog/blob/master/tests/learning/miner/UREMinerUTest.cxxtest that are pretty diverse though, but not random.

@vsbogd is actually adding random scope link generator in the benchmark repo https://github.com/opencog/benchmark , see https://github.com/opencog/benchmark/pull/13 which should hopefully be merged soon.

**Comment by vsbogd** [comment]
At the moment this generator is very simple: it generates new ScopeLink using unique variable and predicate name. Unique names are generated just adding incremented postfix. 
This is code snippet:

```
std::string get_unique_name(const std::string& prefix, size_t& seed)
{
	std::ostringstream oss;
	oss << prefix << "-" << ++seed;
	return oss.str();
}
static Handle create_scope_link(AtomSpace& atomspace, size_t& seed)
{
	Handle X = atomspace.add_node(VARIABLE_NODE, get_unique_name("$X", seed));
	Handle P = atomspace.add_node(PREDICATE_NODE, get_unique_name("P", seed));

	Handle variable_list = atomspace.add_link(VARIABLE_LIST, X);
	Handle expression = atomspace.add_link(EVALUATION_LINK, P, X);

	return createLink(SCOPE_LINK, variable_list, expression);
}
```
It may be enough to generate collision though.

**Comment by ngeiswei** [comment]
@vsbogd I don't think that would be enough.

I think what we really need is a formal grammar describing the Atomese syntax, perhaps superseding `atom_types.scrip`. Then such grammar could be used by benchmark and other programs (like AS-MOSES) to generate Atomese. I'll try write an issue about that tomorrow.

**Comment by linas** [comment]
@ngeiswei I think enough of the the deep-types idea has been implemented that you can enforce any kind of type checking that you wish. There are three ongoing experiments in this: The `TypedAtomLink` (see wiki) and static type-checking in the classserver factory. Turns out that static type-checking kind-of sucks, and works badly. The static typechecking uses three link types: NumericOutputLink, TypeOutputLink, EvaluatableLink and NumericLink.

NumericLink says "I'm a function and I expect numbers as input"
NumericOutputLink says "I'm executable, and when I get executed, I generate a number"
EvaluatableLink says ""I'm evaluatable, and I generate a truth value when evaluated".

These constraints are verified in the factory, when the atoms get created. Basically, it works badly; the implementation is fine, the idea is bad.

The TypedAtomLink allows you to declare more complex constraints, but it is not used anywhere.

**Comment by ngeiswei** [comment]
@linas I'm thinking of something that would generalize (entirely or partly) the classserver checker where atom constructs are the least constrained possible, a syntax check of some sort.

TyoedAtomLink seems adequate if one wants to add further constrains on atoms (especially useful for predicates and schemata but not only).

**Comment by linas** [comment]
On Fri, Jun 1, 2018 at 1:11 AM, Nil Geisweiller <notifications@github.com>
wrote:

> @linas <https://github.com/linas> I'm thinking of something that would
> generalize (entirely or partly) the classserver checker where atom
> constructs are the least constrained possible, a syntax check of some sort.
>

Just saying that it's easier-said than done. Preliminary experience with
static typechecking indicates that its ugly.   Here's an example:

(Plus (Number 3) (RandomChoice (Number 1) (Number 21)))

 (Plus (Number 3) (RandomChoice (Number 1) (Concept "B")))

So .. is RandomChoice a numeric-output link, or not?  Well, the above
example suggests that its a https://en.wikipedia.org/wiki/Dependent_type
which we do not yet support in the Atomese type system

Values add a new layer of confusion.

I thought I would start "nice simple and easy" with the classserver
type-checker, but that has already exposed issues.  So now when you say
"like the classserver but more complicated", that makes me nervous, because
even the simple case doesn't work well, yet.


-- 
cassette tapes - analog TV - film cameras - you

**Comment by ngeiswei** [comment]
I've added the following related task #1726 if a newcomer (maybe @noskill) wants to tackle it. If no hash collision is detected during normal operation (unit tests, benchmarks, examples, etc) it would indicate that the hash function is very good.

**Comment by ngeiswei** [comment]
This issue is getting too big and most of the information in it is outdated (due the recent improvements with the hash algorithm). So I'm closing it will recreate one with the update to date residual problems.
