### ISSUE TITLE
add pre-tweaked pgsql server config file for sql persistance

### ISSUE THREAD

**Issue by mjsduncan** [opencog/atomspace#1633]
this would significantly improve ease of installation.

**Comment by linas** [comment]
Such a "pre-tweaking" is strongly dependent on the postgres major and minor version, and is also dependent on the distro, and where and how the distro chooses to install postgres.  It also depends on how the user has done their file-system layout.  It also depends on the on-postrges packages installed, such is the use of inetd and identd to provide unix authentication services, or the use of gssapi, or whatever. 

If you want to do this, do it for some standardized LXC install; I almost said "Docker", but docker does not work well with databases, in general. Anyway, that would not be this repo, but some other one.

**Comment by AmeBel** [comment]
@mjsduncan there is a pre-teawked docker setup at https://github.com/opencog/docker/tree/master/opencog/postgres. You can pull it from https://hub.docker.com/r/opencog/postgres/

**Comment by mjsduncan** [comment]
this is a feature request to make installation on the oc standard ubuntu distro slightly less painful so people besides you might actually use it.

<div>-------- Original message --------</div><div>From: Linas Vepštas <notifications@github.com> </div><div>Date:25/04/2018  14:35  (GMT-05:00) </div><div>To: opencog/atomspace <atomspace@noreply.github.com> </div><div>Cc: mjsduncan <mjsduncan@gmail.com>,Author <author@noreply.github.com> </div><div>Subject: Re: [opencog/atomspace] add pre-tweaked pgsql server config file for
  sql persistance (#1633) </div><div>
</div>Such a "pre-tweaking" is strongly dependent on the postgres major and minor version, and is also dependent on the distro, and where and how the distro chooses to install postgres. It also depends on how the user has done their file-system layout. It also depends on the on-postrges packages installed, such is the use of inetd and identd to provide unix authentication services, or the use of gssapi, or whatever.

If you want to do this, do it for some standardized LXC install; I almost said "Docker", but docker does not work well with databases, in general. Anyway, that would not be this repo, but some other one.

**Comment by linas** [comment]
Mike, the ockpg is exactly that tool to make installation easy.

Since postgres is unrelated to opencog, it does not make sense to put postgres code into this repo -- it breaks expectations of orthogonality of function.  In software development, orthogonality is the number one primary defining concern, ahead of everything else.

Repos are for code. Questions of packaging and installability are distinct, and are typically handled through distinct organizations -- for example: Debian,. Ubunutu, RedHat -- they exist (were created) to solve the installability problem.  Thus, in Debian/Ubunut, which use dpkg/deb and RedHat, which uses rpm, the deb file, or the rpm file performs the installation, and it also contains scripts that modify other system components as required, e.g. the database configuration.  

The right thing to do, in this case, would be to pester MHata, who is the Debian maintainer for opencog, and see if you can get him to fix it.

**Comment by mjsduncan** [comment]
thx!

<div>-------- Original message --------</div><div>From: Amen Belayneh <notifications@github.com> </div><div>Date:26/04/2018  00:04  (GMT-05:00) </div><div>To: opencog/atomspace <atomspace@noreply.github.com> </div><div>Cc: mjsduncan <mjsduncan@gmail.com>,Mention <mention@noreply.github.com> </div><div>Subject: Re: [opencog/atomspace] add pre-tweaked pgsql server config file for
  sql persistance (#1633) </div><div>
</div>@mjsduncan there is a pre-teawked docker setup at https://github.com/opencog/docker/tree/master/opencog/postgres. You can pull it from https://hub.docker.com/r/opencog/postgres/
