### ISSUE TITLE
Synchronize AttentionBank properly

### ISSUE THREAD

**Issue by vsbogd** [opencog/atomspace#1658]
See https://github.com/opencog/atomspace/pull/1656#discussion_r186028473

**Comment by vsbogd** [comment]
AttentionBank::getRandomAtomNotInAF() uses _importanceIndex and attentionalFocus to return atom which is not in in attentional focus. But this method may work incorrectly as operations which update _importanceIndex and attentionalFocus are not atomic and both collections can be update in parallel. 

For instsance AttentionBank::stimulate() method calls _importanceIndex.updateImportance(h, oldav, newav); without synchronization and then updates attentionalFocus using AFMutex.

**Comment by linas** [comment]
A general remark: the code in that directory is old, and has been only very minimally maintained (by Misgana, who has added only those features he needs, as a user).  It has not had any sort of top-to-bottom design review or cleanup in a very long time.  So this bug is not surprising; there are probably more. 

(For example, the way it uses `config()` is super-annoying, because it results in warning messages being printed every time you use it. I hate that. It should probably not be using config() at all; that should be done by the user application, and not by the AttentionBank itself)

Also, there might be other attention-related things in the opencog repo that should be move here. Maybe. I can't tell.   The rule, so far, has been that if it is solid, well-thought-out, maintained, and interesting for everybody, it should be in the atomspace repo. If it is experimental, goofy, unmaintained, not of general interest, it should stay in the opencog repo.

**Comment by linas** [comment]
FYI, I just moved all attention-bank-related code to one directory, in pull req #1664 and have another one coming, which puts all the attention-bank related unit tests into the same directory.

**Comment by linas** [comment]
#1666 is the other half of the consolidate-atention-bank code series.

**Comment by linas** [comment]
closing, the attentionbank code is in the opencog repo, not here.
