### ISSUE TITLE
FreeLink variable order depends on variable names, not just atom structure

### ISSUE THREAD

**Issue by ngeiswei** [opencog/atomspace#1677]
The variable order returned by `FreeLink` (`FreeLink::get_vars()` for C++, `cog-free-variables` for Scheme) depends on the variable names, not just the atom structure. For instance
```
 scheme@(guile-user)> (cog-free-variables (And (Variable "$X") (Variable "$G")))
$6 = ((VariableNode "$G")
 (VariableNode "$X")
)
scheme@(guile-user)> (cog-free-variables (And (Variable "$X") (Variable "$Y")))
$7 = ((VariableNode "$X")
 (VariableNode "$Y")
)
```
I don't know if that's a bug, probably not, but it should at least be added as a warning in the pertinent documentations https://wiki.opencog.org/w/FreeLink https://wiki.opencog.org/wikihome/index.php/Scheme#cog-free-variables

**Comment by linas** [comment]
The free variables are a set.  Sets do not have a defined order. It was defined that way on purpose. The documentation somewhere does state why its a set, and not an ordered list. Please note that the concept of order is fundamentally ill-defined in atomese. Not only is there ambiguity in breadth-first vs. depth-first searches, there is also  ambiguity in unordered links.  I don't see much point in artificially introducing some fake order, when the core concept is naturally unordered.

I don't recall adding a scheme wrapper for this; exposing this function in scheme does not seems to be a wise idea, I don't know why it got exposed or who uses it.

**Comment by linas** [comment]
Archeology reveals that it is you, Nil, who added the scheme binding for `get_free_variables`, two years ago. Here: 341eda9ef70f3219b1c55fea48b987225eee7dc0 Why did you add this? why would you ever need to access this outside of C++ code? 

I'm kind of nervous to see core function escape out of C++ code, and move into scheme (or python) -- it makes long-term maintainability and portability harder, and risks creation of spaghetti code.  Maybe there really is some valid reason to export this kind of function into scheme code, but its not obvious what it would be.

**Comment by linas** [comment]
A few more comments about "connectors": as a general rule, the location of the connector does not matter; only the type; as long as the connector types are compatible, they can connect.  There still may be some global rules that constrain connection: e.g. the the final graph is planar, with no crossing links.  This has the side-effect of enforcing a degree of sequential order.

Or there may be more complex constraints e.g. "landmark transitivity".  If the graph can be laid out in a linear fashion, then there can be left-right constraints. If you can naturally color the graph, there might be coloring constraints.  Again: these are all "global" constraints that have to be satisfied by the final graph, rather than "local" constraints, e.g. that the connectors appear in a certain fixed order.

Whatever. I'm just looking at `implication-instantiation.scm` and it looks like its trying to enforce local connector constraints, using variables as connectors. Or I might be wildly wrong.

**Comment by ngeiswei** [comment]
Ooops, I had forgotten *I* had added that wrapper. And of course I got confused because it returns a list, while as you pointed free variables are a set. My bad.

As far as `instantiation.scm` goes, it is likely obsolete, and if not it should be. All rules under the wip directory need to be reviewed, then fixed or removed.

**Comment by ngeiswei** [comment]
Though I've got to say that the `FreeVariables` class https://github.com/opencog/atomspace/blob/master/opencog/atoms/core/Variables.h#L48 doesn't exactly reflect the fact that free variables are unordered either, see `FreeVariables::varseq`, etc. Maybe all attributes and methods of `FreeVariables` pertaining to and depending on variable ordering should be moved to `Variables`. Not that it is very important though...

**Comment by linas** [comment]
the schizophrenic usages of seqs vs sets has a lot to do with C++, and that it is often awkward to use one or the other -- its often just easier, faster to use seq, even though something is conceptually a set.

**Comment by linas** [comment]
I'm closing this, because:
* There's been work done in this direction,
* The discussion above seems too vague to suggest an actual action plan. There doesn't seem to be anything concrete to do?

Reopen if you disagree, or a new issue with a more precise description of what should be done.
