### ISSUE TITLE
Cannot create BindLink in one go (unadded Handles comparison problem)

### ISSUE THREAD

**Issue by williampma** [opencog/atomspace#172]
```
    Handle v(createNode(VARIABLE_NODE, "$A"));
    Handle blv(createLink(VARIABLE_LIST, v));
    Handle blb(createLink(AND_LINK, v));
    Handle blt(createLink(LIST_LINK, v));
    HandleSeq bll = {blv, blb, blt};
    Handle bl_final(createLink(BIND_LINK, bll));

    as->add_atom(bl_final);
```

gives me exception

```
The variable (VariableNode "$A") ; [18446744073709551615]
 does not appear (unquoted) in any clause! (/home/william/atomspace/opencog/atoms/bind/PatternLink.cc:365)
```

This is causing some problem with Instantiator when a mapping mapped a variable to a BindLink on an evaluatable (so the thing has to be added to `_temp_aspace`).

I came across this before but worked around it at the time.  The problem is that Handles that haven't been added to the AtomSpace yet cannot be compared (no UUID).

**Comment by ngeiswei** [comment]
For that reason I always use AtomSpace::add_{node,link} and never create{Node,Link}, but it seems it would be nice if one could create and manipulate hypergraphs without having to insert them in the AtomSpace.

**Comment by linas** [comment]
For the most part, you can create atoms outside of the atomspace, and
things should mostly work.  There are a few "obvious" limitations:

-- There is no way of gauaranteeing the uniqueness of atoms unless you
place them in the atomspace. Viz, witout the atomspace, you can have
multiple copies of "atom foo", and this can potentially cause
problems, depending on your algo.

--- UUID's are only issued whten atoms are placed in the atomspace.
Since the python bindings use UUID's (they should not, but they do),
you cannot use python on atoms that are not in the atompsace.

-- The only way to share atoms on different machines (in an
unambiguous fashion) is via the atomspace.

-- In parinciple, the pattern matcher does not really depend on the
atomspace; however, the new design splits pattern matching into two
parts: one-time-only initialization, and the rest, and perhaps the
first-time initialization is tangled into the atomspace. This could
perhaps be fixed; its not a fundamental limitation.

Linas.

**Comment by linas** [comment]
I just tried this, it seems to work at this time. Maybe one of the recent pull requests fixed it.

**Comment by jswiergo** [comment]
Yes, it is fixed by #244 and can be closed. BindLink constructor used FindUtils which did not support atoms not in the atomspace yet (having UUID=MAXINT).

**Comment by williampma** [comment]
OK, I don't think the fix is correct.  The following
```
    Handle va(createNode(VARIABLE_NODE, "$A"));
    Handle vb(createNode(VARIABLE_NODE, "$B"));
    Handle blv(createLink(VARIABLE_LIST, va, vb));
    Handle blb(createLink(AND_LINK, va));
    Handle blt(createLink(LIST_LINK, va));
    HandleSeq bll = {blv, blb, blt};
    Handle bl_final(createLink(BIND_LINK, bll));

    _as->add_atom(bl_final);
```
should give me the exception since $B is not used anywhere in the clause, but instead it passes.

**Comment by linas** [comment]
Huh. Well, this one does work:
```
(BindLink
   (VariableList
      (VariableNode "$a")
      (VariableNode "$b"))
   (AndLink
      (VariableNode "$a"))
   (ListLink (VariableNode "$a")))
```
I wonder whats different ...

**Comment by linas** [comment]
OK, found the problem, fixed it, you won't exactly like the result because it causes BackwardsChainerUTest to fail.  I get this:
```
'Variable Fullfillment Query'
 [DEBUG] [BackwardChainer] Matching knowledge
base with  (NotLink (stv 1.000000 0.000000)
  (EqualLink (stv 1.000000 0.000000)
    (VariableNode "$A-pln-rule-deduction") ; [7207]
    (VariableNode "$C-pln-rule-deduction") ; [7211]
  ) ; [7216]
 and variables (VariableList (stv 1.000000 0.000000)
  (TypedVariableLink (stv 1.000000 0.000000)
    (VariableNode "$A-pln-rule-deduction") ; [7207]
    (TypeNode "ConceptNode") ; [7113]
  ) ; [7208]
  (TypedVariableLink (stv 1.000000 0.000000)
    (VariableNode "$C-pln-rule-deduction") ; [7211]
    (TypeNode "ConceptNode") ; [7113]
  ) ; [7212]
) ; [7251]
In BackwardChainerUTest::test_2rules_bc:
/home/linas/src/novamente/src/atomspace-git/tests/rule-engine/BackwardChainerUTest.cxxtest:40: Error: Test failed: Variable not groundable: (VariableNode "$A-pln-rule-deduction" (av 0 0 0) (stv 1.000000 0.000000)) ; [7207]
```

I'm going to push the fix even though it breaks the unit test.

**Comment by linas** [comment]
well, pull req #257 does it.  Careful what you wish for :-)
