### ISSUE TITLE
Check hash collision between atoms at run-time

### ISSUE THREAD

**Issue by ngeiswei** [opencog/atomspace#1726]
This issue is related to #1625.

To measure the quality the atom hashing function it would be convenient to be able to enable some systematic check at run-time.

So more specifically, it could be done by adding some code somewhere under the AtomSpace API that checks, whenever an atom is added, whether its hash differs from all other existing atoms in the atomspace. If it does, since the atomspace refuses to add duplicates, it implies that they differ in content and thus that there is a hash collision. 

Obviously this code should be wrapped in a macro so that it doesn't slow down the atomspace in operation when disabled.

**Comment by linas** [comment]
If you just want to measure the size of a typical hash bucket, you can place a counter into the loop at AtomTable.cc line 238-245 and 284-291 -- besides finding just 0 or 1, I think you'll frequently find 2 or more.   I believe its a Poisson distribution -- there is a finite but exponentially small probability of arbitrarily many hash collisions.

**Comment by ngeiswei** [comment]
@linas I'm not interested in measuring whether 2 hashes are in the same bucket which is up to `std::unordered_multimap`'s implementation, as of now anyway. What I am interested in is how often `Atom::compute_hash()` computes the same hash of atoms that differ in content. A good implementation should produce such collision fairly rarely.

I don't think placing a counter into the loop at AtomTable.cc line 238-245 and 284-291 measures the size of a hash bucket. Based on `_Hashtable::equal_range`, http://en.cppreference.com/w/cpp/container/unordered_map/equal_range and http://www.cplusplus.com/reference/unordered_map/unordered_multimap/equal_range I believe it counts the number of identical hashes, thus is actually a good suggestion for what I'm interested in. So, if I'm correct, I do not expect it would be frequently 2 or more, it will only be rare. If not, `Atom::compute_hash()` needs to be fixed.

**Comment by stellarspot** [comment]
Method AtomTable::add(...) put an atom using its hash as key and the atom as value.
Because of hash collisions the unordered_multimap is used.
Is it possible to use unordered_set instead of unordered_multimap and directly put in and get atoms from it?

**Comment by ngeiswei** [comment]
@stellarspot I think replacing unordered_multimap by unordered_set would work, I suspect unordered_multimap is only here for historical reason, predating atom hash (when the atom ID used to be determined by a run-time counter).

**Comment by linas** [comment]
Um no. Two different atoms can still hash to the same hash. There needs to be some way of handling this. 

Lack of hash collisions is a statistical property, not an absolute property. The C++ unordered classes are designed so that they *intentionally* get hash collisions approximately half of the time. This is done this way to avoid having lots of empty hash buckets.

When one has lots of empty hash buckets, the size of the atomspace explodes.  My datasets have anywhere from 10 million to 80 million atoms; at 1.5KBytes/atom thats 15GB to 120GB of RAM. Getting the size of this table incorrect, due to fiddling about with the hash buckets only leads to even more RAM usage, which I cannot afford.

Again: hash collisions are normal; they are used to keep most hash buckets full. The C++ docs on cppreference explin this in detail

**Comment by linas** [comment]
I'm closing this, because I assume this is a done task; or is there more?

**Comment by ngeiswei** [comment]
@linas I'm not sure you understand @stellarspot 's suggestion, if I'm correct he means replacing `AtomTable::_atom_store` type by `unordered_set`. It would work exactly like `unordered_map` but *might* take less RAM (not sure, maybe) and make the code slightly simpler. Since `std::hash` is overloaded for `Handle` I think it would work out of the box.

@stellarspot if you wish to go forward with this idea best is to create an issue for it, then a PR.

**Comment by linas** [comment]
Hmm. Indeed. Maybe. There was one part of the system I experimented with very heavily, trying to find exactly the right c++ container so as to minimize RAM and maximize performance. It was surprisingly hard and unintuitive, and I'd written a fairly long comment in the C++ code explaining the why and wherefore of this.   Now I can no longer find that comment, nor do I recall if it was the `_atom_store` or if it was something else.

I'm sort of extremely nervous about changes in this area of the code; its performance-senstive, so my knee-jerk reaction is "leave it alone".  We still don't have any test framework that can measure this, at scale.

However ... if there's a super-duper clean pull request, I could test it, or give you a dataset to test with. One of my smaller datasets has 26M atoms in it; 25924129 to be exact, and earlier today it loaded in 3500 seconds into 38GB RAM virtual, 36.5 GB RSS.  I can give you that dataset, or I can redo the measurements myself.  Match or beat that record, and the change goes in.  (its my `en_pairs_rfive_mtwo` dataset.)

I'm looking at the `_atom_store`code, and I don't know why it's a multimap. The notes don't explain why.  Its not that old, its fairly modern code, as it goes; it was used instead of `set` for a reason, but I don't see the reason just right now.

**Comment by ngeiswei** [comment]
Maybe that dataset could be added to https://github.com/opencog/benchmark or rather it's access (if it's big and can't be generated cheaply) using git-annex or such?

**Comment by linas** [comment]
Its located at https://linas.org/lxc-nlp-containers/en_pairs_rfive_mtwo.sql.bz2
It needs to be leaded by saying 
```
createdb  en_pairs_rfive_mtwo
bzcat en_pairs_rfive_mtwo.sql.bz2 |psql en_pairs_rfive_mtwo
```

The load of the 26M atom subset is done by saying this:
```
(use-modules (opencog) (opencog logger))
(use-modules (opencog persist) (opencog persist-sql))
(use-modules (opencog matrix))
(use-modules (opencog nlp) (opencog nlp learn))
(use-modules (opencog cogserver))
(sql-open "postgres:///en_pairs_rfive_mtwo?user=linas&password=asdf")
(define pca (make-pseudo-cset-api))
(pca 'fetch-pairs)
```

I think these instructions are accurate. Please note that, due to OS file buffering, etc. the second load will be much much faster than the first one (because it won't be on disk any more)

**Comment by linas** [comment]
Its handy also to `(start-cogserver)` and telnet in and monitor progress by saying `(sql-stats)` every now and then.

**Comment by linas** [comment]
I don't know how to use git-annex.  I have 35 other roughly comparable dumps of a large variety of sizes and having everything from bad to good data in them

**Comment by linas** [comment]
Although the data is "bad", its good enough for benchmarking.

**Comment by linas** [comment]
well, the `en_pairs_rfive_mtwo`  data is good; some of my unpublished others, not so much.

**Comment by ngeiswei** [comment]
@vsbogd what do you think would be the best way to manage that sort of big data set?

**Comment by vsbogd** [comment]
@ngeiswei, I am not familiar with git-annex but from brief description on its website it is some workaround which doesn't fully resolve problem. As far as I understand when using  git-annex Git repository keeps only symlink on file. File itself is kept only locally. Not sure we need this.

I think the simplest way to manage it is adding a script to load files from some remote storage before running benchmarks. The only question is what storage can be used. 

GitHub documentation mentions that Releases can be used to keep large binary files. But it doesn't seem natural. Do we have any opencog related file storage with enough space?

**Comment by ngeiswei** [comment]
Git LFS is very cool, they even seem to say that you can store files GBs in size, which sounds too good to be true. Although apparently configuring it for another server doesn't seem too complicated https://github.com/git-lfs/git-lfs/blob/master/docs/api/server-discovery.md#custom-configuration.

**Comment by vsbogd** [comment]
Ok, let's use git-lfs then.
