### ISSUE TITLE
Should we add an ArgumentList?

### ISSUE THREAD

**Issue by rTreutlein** [opencog/atomspace#1853]
I have been working on Distributional Values recently and am using these for joint probability distributions which are attached to Cartesian Product which can easily be represented by a ListLink. The issue comes up when a VariableNode is grounded by this ListLink and I want to pass it to an EvaluationLink. The EvaluationLink sees the ListLink and assumes that you want to provide it with multiple Arguments even though that is not the case.
To avoid this we could add an ArgumentList which acts like a ListLink would right now. To allow people to specify when they wish to have multiple Arguments and a when to treat the Product as a whole.

**Comment by linas** [comment]
The obvious work-around is to have a ListLink that wraps the ListLink.

Maybe having an ArgumentList is a good idea. But maybe having a CartesianProductLink is a better idea.  When would you use one instead of the other?  When does the ListLink get used? How does existing code change to accommodate this?  Or maybe something completely different, like getting rid of the ListLink in an EvaluationLink (so that you have just `(Evaluation Pred arg arg arg)` instead of wrapping args in a list).

I've run around in circles, over and over, contemplating all of these different kinds of variations. Adding more link types just adds more complexity, more confusion, more unit tests, more exceptions, if-and-but's in the documentation, so the payoff has to be worth it.  So far, in developing atomese, I've tried to work through all of the different ways of doing things the different alternatives, and pick the alternatives that seem to fit together best.  But this is a global-optimization problem; its hard.  Usually, a gain, a win, here, means that something somewhere else loses or gets uglier.  Usually, it takes about a year to figure it out, after one or two failed implementations. (I'm not joking about it taking a year).

In my new job title, I won't have much time to ponder these tradeoffs. That means you or others have to.  That means you should describe the actual problem you're having above in much greater detail (cause I don't fully understand it)  Maybe there's some easy work-around? I can't tell.

**Comment by ngeiswei** [comment]
@rTreutlein A more detailed description of the problem, with examples, would be welcome indeed.

**Comment by vsbogd** [comment]
Hi @rTreutlein , as far as I understand you always need to designate GroundedSchemaNode arguments, so last part of the BindLink should be:
```
ExecutionOutPutLink
                GroundedSchemaNode "scm: modus-ponense-formula"
                ListLink
                    VariableNode "$B"
                    VariableNode "$A"
                    InheritanceLink
                        VariableNode "$A"
                        VariableNode "$B"
```

**Comment by ngeiswei** [comment]
Thanks, @rTreutlein , I understand your problem now. I wonder if the ideal solution wouldn't be to have the Atomese interpreter check the arity of the grounded schema, and it is fixed and equal to 1, then it would pass the `ListLink` instead of decomposing it into multiple arguments, would have the effect of not dismissing the `DV` attached to it.

However I don't know how feasible that it (how much from within C++ one can probe the Scheme/Python/Haskell function signature).

For now (and maybe the long term as well) I think it's acceptable to use a `ProductLink`.

**Comment by linas** [comment]
I see several potential confusions. First:  this part:
```
   AndLink
       VariableNode "$A"
       More stuff  that uses $A
```
You don't need that initial `VariableNode "$A"` in the AndLink. It does nothing.  By the same reasoning, you also do not need the Inheritance Link.  The whole thing can be simplified to
```
	AndLink
		Evaluation
			GroundedPredicateNode "scm: has-dv"
			VariableNode "$A"
		Evaluation
			GroundedPredicateNode "scm: has-dv"
			InheritanceLink
				VariableNode "$A"
				VariableNode "$B"
```

Now that we have the whole thing in pocket, its easier to read. Since the second argument to an EvaluationLink must **always** be a ListLink, we have that Variable A is always grounded by a list link, always. 

However, that means that the second Evaluation is mal-formed: you are using an InnheritanceLink where only a ListLink is allowed.

So I think you need to fixes these issues first. 

Note also that you are using both variable A and B untyped. You might want to specify types for A and B. This will often speed up the search; it will also avoid confusing matches.

**Comment by rTreutlein** [comment]
@linas Having the VariableNode "$A" and the InheritanceLink in the AndLink is pretty standard in the PLN-Rules but yea I guess it's not really needed other than to clarify what are the preconditions vs the pattern clause.

Regarding the second point if you **always** need a ListLink in the second argument then maybe we should throw an error if this is not the case. Because at the moment this works perfectly fine if the VariableNode "$A" is grounded by a ConceptNode.

**Comment by linas** [comment]
There is no such thing as a "precondition" to the pattern clause. There is no such concept. It doesn't exist.  From the pattern matcher, its just some extra cruft to deal with.

The AndLink is an unordered link. Just because you wrote the outgoing set in some particular order, does not mean that the internal representation is in that order.  The internal representation orders the clauses by the hash value.

The rules for EvaluationLink are pretty ad-hoc, at the moment. My understanding is that PLN is quite strict about that; Nil knows better. If you want strictness, the variables should be typed -- that is what variable typing is for.
