### ISSUE TITLE
Will SetLink's be replaced soon?

### ISSUE THREAD

**Issue by tanksha** [opencog/atomspace#1866]
HI all
I am working on applying PLN for bio-medical relationship reasoning and the results of cog-execute/cog-bind are in a SetLink. I have read in [this](https://wiki.opencog.org/w/SetLink) article that it is recommended to use MemberLink instead of SetLink. My question is, will PLN or Pattern matching results with a SetLink be replaced by MemberLink soon or Should I just consider using SetLink as a result of my PLN rules and continue with it.

**Comment by linas** [comment]
This is a dupe of #1502 ... 

It would be better if we replaced SetLink by MemberLink sooner, rather than later, but if it's me who has to write the code .. ooof. I simply don't know when to find the time. I have made half-a-dozen promises to do things, and each of these takes a month.   Doing this replacement is important, but zero warm bodies are assigned to the task.  And it's kind-of non-trivial.

**Comment by tanksha** [comment]
Thank you Linas. I will continue working with it and consider writing a function to retrieve the results inside the SetLink since I don't need the SetLink to appear as my result.

**Comment by ngeiswei** [comment]
> function to retrieve the results inside the SetLink
```
(cog-outgoing-set results)
```
