### ISSUE TITLE
Question about atom copying procedure

### ISSUE THREAD

**Issue by vsbogd** [opencog/atomspace#1965]
`AtomTable` uses `createNode()` function to copy node. 
https://github.com/opencog/atomspace/blob/e47dc46daa278c22cf3ba0c503e12b0e1e9b025d/opencog/atomspace/AtomTable.cc#L394

`createNode` uses constructor of `Node` class to create `Node` instance and then calls the `classserver().factory(tmp->get_handle())` to create the new instance of proper class. 
https://github.com/opencog/atomspace/blob/e47dc46daa278c22cf3ba0c503e12b0e1e9b025d/opencog/atoms/base/Node.h#L128-L134

Such way of copying has two disadvantages:
- temporary node is created though it will not be used further;
- as Node copies only type and name of the copied node all other information which node can potentially contain will be lost.
The same is true for link copying procedure.

I would like to discuss and implement another way of copying, which allows using copying constructor of method which is specific for original atom class if it is different from Node or Link.
One of the simplest and safe ways is to add another method for copying existing atom and return it from `ClassServer` (the way as `factory` method works).

**Comment by linas** [comment]
Oh, huh. Sure. Wouldn't the easiest fix just be to call the factory directly, in `AtomTable.cc` line 394?  "Other information" is not lost; it's copied at line 422.  I'm tempted to try that right now, to see what kind of impact it makes on performance.

Please note the following:

* In "principle", one is not supposed to copy atoms: the original idea is that they are unique: there's only one of a given atom in the atomspace.  This assumption does get violated in a few places, but I don't want to abandon it.

* AtomTable.cc line 389-390 says "We MUST maintain our own private copy", but perhaps this is no longer needed.  Maybe we can skip copying, entirely. In the past, there were unit tests that crashed ... !?? Why?  Why is a private copy needed?   Maybe the unit tests are badly designed?

* In order to help enforce the idea of a single, globally unique atom, the AtomTable API originally did not have methods that took `const Handle&`.  The original methods were `getHandle(Type, const std::string&)` and `add(Type, const std::string&)`.  Should we return to this API? Or maybe the opposite: should we get rid of it? 

* Why do we need both `AtomPtr` and `Handle` anyway? Every time I think of getting rid of one or the other, I get tired and confused and lazy and give up.  Maybe there is a valid reason for having both, but I can't remember what it is, and its not obvious.

* Perhaps we should get rid of `createNode`. It originally was a `#define` with a note that said `XXX FIXME` on it, and, instead of fixing it, it morphed into a template, which got fancier and fancier.

Most of these questions remain unaddressed because they are kind of boring, and don't have any real impact on performance.  They only make the C++ API a little more confusing than it could be.  And they are also kind-of hard to solve; there is no clear, obvious answer.

**Comment by linas** [comment]
> MUST maintain our own private copy

Disabling this causes 7 unit tests to fail. Some of these explicitly trigger the need for a copy (e.g. the COWUTest) while others might be badly designed.

**Comment by linas** [comment]
> factory

There should be one version which *always* creates now atoms, and another which only creates new atoms, if they are not yet in C++ canonical form. The current factory is a mixture of these two behaviors; it shouldn't be.  There's some fairly large amount of code in the pattern matcher, etc. which does `if(BlahNodeCast(x)) else createNode()` and that code could be eliminated.

**Comment by linas** [comment]
Net-net: if you want to do this, do it. It's not a bad idea.  I don't have objections.

**Comment by vsbogd** [comment]
> "Other information" is not lost; it's copied at line 422

I mean not only values of the atom but also any object state which is not part of abstract Atom, Node or Link. But values also can be copied by Atom or Node copying constructor.

> Wouldn't the easiest fix just be to call the factory directly, in AtomTable.cc line 394?

It should help to remove temporary copy, but will not copy all of object state because `factory()` calls `create...()` with atom `type` and `name`, it creates the atom instead of copying its state.

>AtomTable.cc line 389-390 says "We MUST maintain our own private copy", but perhaps this is no longer needed.

It was my first idea but then I found that Atom also contains a pointer to the atomspace and I thought that copying should protect Atom state in situations when atom from one atomspace is added to another. I think it is possible to re-think API taking it in mind but for now it seems like a big and non backward compatible change. For me adding copying method looks like simplest backward compatible way.

>Why do we need both AtomPtr and Handle anyway?

I agree that they look interchangeable, but I think it is better to discuss it in separate issue. 

>Perhaps we should get rid of createNode

I think removing `createNode` may simplify the code and make it more explicit.

**Comment by linas** [comment]
> stateful atoms

To repeat what I wrote, stateful atoms have always been prohibited, for many reasons; one big one is that they create a huge amount of trouble. There is a reason that the world of programming is becoming more and more stateless (e.g. clojure, scala, haskell, etc.)  State is considered to be "bad" and "evil".

That said: the atomspace is one big giant ball of "state" and the design philosophy is that all state is explicitly in the atomspace, and zero state is not in the atomspace.  That means all atoms must be explicitly stateless.

There should be a way to handle `GroundedObjectNode`, just without state. There was a partly-fnished conversation elsewhere on this. 

The StreamValue was invented to handle the API to neural nets. So I'd rather stick to that design, until it becomes obvious that it won't be sufficient.

**Comment by linas** [comment]
> scala

If you want to steal great programming ideas, stealing them from scala would not be bad.

**Comment by vsbogd** [comment]
Ok, may be I should not use word "state" here. And I don't suggest making atoms mutable. I don't see any problems with having immutable information inside atom. Do you see? 

For example `NumberNode` has `double` field in it. But as it supposed to have only `type` and `name` as any other node in fact this field always copied via converting it to string and back.

**Comment by linas** [comment]
> NumberNode ... immutable information inside atom

I'd like to repeat something you might already know; maybe you can explain it to @Necr0x0Der or others who might not yet understand.

So -- A far more extreme example is `PatternLink` which has dozens of complex structures inside of it.  This is possible because those structures don't encode anything that isn't already available to the outside observer, just look at the atoms. The structures merely encode short-cuts that can be cached: how many variables are there? where are they? what types are they?  etc. questions that can always be answered by scanning the Link itself, but can be answered much more quickly by doing it once, and caching the result.  So that kind of "state" is acceptable.

Next: why should "all state" be "only in the atomspace"?  The reason for this is so that reasoning algorithms (learning, logical inference, data-mining, etc.) can "find" that state, examine it, and do all the typical learning/inferencing/etc. things that they do. If there is extra state that is hidden in some object where it cannot be found, then those algo's .. can't find it, can't do anything useful with it.   Besides just "learning, inferencing, mining", there are two more: "saving to disk" and "sending to a remote computer".  The last one is the powerhouse behind 80% of cloud-computing scalability.  It's deeply embedded in amazon and google products; I'm just saying "oh hey, its not only about serializing and object sending it over fiber-optic across the ocean to another server; its also about giving *any* algo access to the state." That means the state has to be there, where you can find it.

As to time-varying state: take a look at `RandomNumberLink`. It's "stateless", but every time you ask, you get a different number. We could build a `VideoCameraLink`, which would return the last N pixels. That's an "acceptable" design for changing data. For various reasons, I think that maybe `VideoCameraStreamValue` is better, but I also know that part of that design is incomplete/inadequate, and it needs to be refined.  Current experiment for how this might go is the space-time server.

**Comment by vsbogd** [comment]
> Next: why should "all state" be "only in the atomspace"? The reason for this is so that reasoning algorithms

- Reasoning algorithms relies on atom type and name and on fact that one and only one atoms has same <type, name> pair. It will be true as well for `GroundedObjectNode` so it doesn't seems to me very different from other atoms.
- There is already very similar atom `GroundedSchemaNode` which represents some behavior which is black box for reasoning algorithms.

> there are two more: "saving to disk" and "sending to a remote computer"

I agree that in current implementation it is not easy to implement serialization for such atoms link `GroundedObjectNode` but it is not impossible, and it is one of the things which probably can be improved: moving all atom related code: initialization, copying and serialization to the atom implementation. 

> We could build a VideoCameraLink, which would return the last N pixels. That's an "acceptable" design for changing data.

If it is a question of having more specific atoms to represent particular kinds of objects then I agree. For instance `GroundedObjectNode` can be some abstract atom implementation but `NeuralNetworkModelNode` can be specific node which semantics is more clear for reasoning system.

> The StreamValue was invented to handle the API to neural nets. 

Converting neural nets models to StreamValue and vice versa losts an information about model structure which is required for error back propagation (@noskill, @Necr0x0Der please correct me if I am mistaking). It is the reason why `GroundedObjectNode` is suggested.

**Comment by noskill** [comment]
Perhaps we should better describe our usecases to @linas:

1) We would like to be able to pass between ExecutionOutputLinks python objects, particulary pytorch tensors. Pytorch saves in it's tensor instances necessary information for performing backward propagation.

2) More convenient api than GroundedSchemaNode for calling objects methods.

Here is one example:
```
ExecutionOutputLink
   GroundedSchemaNode("obj: dot.apply")
   ListLink
      ExecutionOutputLink
          GroundedSchemaNode("obj: redModule.runModule")
          ListLink
              VariableNode("$Scene")
      VariableNode("$SomeWeights")

class Dot:

 def apply(atom_value, atom_value1):
   tensor = ((GroundedObjectNode)atom_value).getObject()
   weights = ((GroundedObjectNode)atom_value1).getObject()
   result = tensor.dot(weights)
   return GroundedObjectNode(randomname(), result)

class ColorModule:

 def runModule(data_obj):
   features = ((GroundedObjectNode)data_obj).getObject()
   result = modules[module_name.name](features)
   return GroundedObjectNode(randomname(), result) (edited) 
```

We would like to represent layers(here ColorModule is interface for some NN layers) as Nodes in atomspace and to be able to pass python objects between these layers, thus making neural networks somewhat introspectable from within the atomspace.

**Comment by linas** [comment]
Hmm. Ther are maybe too many parallel discussions going on at once.
> GroundedObjectNode

I'd have to find the other place where this is discussed, and review it. At the moment, I don't understand why there is a problem, or what it is.

>  implement serialization

Again, I want to very strongly resist this concept. To be bombastic about it: many decades of comp-sci experience has demonstrated that serialization is a truly terrible, awful idea. You can see its birth with CORBA, back in the 1990's. You can see it with serialization of objects to files. You can see it in python freeze. You can see it in java serialization. All of these projects were either killed, or died natural deaths, for important reasons that should not be ignored. Java serialization was officially killed only this year? Last year? Serialization to file died naturally in the 2000's when people woke up with permanently corrupted data after software upgrades. Python freeze similarly: your objects get corrupted, if you make any mistakes at all in freezing them (and sooner or later, developers always make mistakes). And CORBA never really worked, it was too complex.

Meanwhile, academia went in the opposite direction: haskell invented the concept of monadic actions to explicitly formalize what was wrong with serialization and state, and force it into a tight box which can be controlled. Clojure made their objects immutable so that they could avoid lock overhead. Scala went state-free so that it could do massively scalable parallel distributed computing.  There's only one programming language that goes opposite to this general trend: Erlang. 

This is one case where I think the atomspace should go with the majority, and do what almost everyone else is doing. The Atomspace already is built on so many new and novel and different ideas, that its already very contrarian and non-mainstream.  But we don't have to be contrarian on every possible idea from comp sci.  Mainstream comp-sci has repeatedly shown that serialization is a truly bad idea. Lets not try to figure out if we can somehow magically make it work, when so many others have failed.

**Comment by linas** [comment]
> neural nets models to StreamValue loses information

There is some mis-understanding.  I think the original design discussion had the network connectivity living in Atoms, and that the Values would be attached to the data streams in the GPU's. Anyway, this needs to be discussed in some other issue, not this issue. Again - by keeping connectivity information in the Atoms, the reasoning system could "think about" the connectivity, and alter it s needed.

**Comment by linas** [comment]
@noskill  Thank you. Can you open a new issue, maybe call it "best way of doing neural nets in the atomspace"?   Posting the code is useful, but I'm having trouble trying to guess what you are doing there.  It would be better if you described what the various pytorch objects and data streams are.  

As a general approach, the following seems reasonable:

* Any "static" data that does not change quickly should be encoded with atoms.  So, for example, connectivity: which layers get connected to which other layers.  (FYI, the atomspace is kind-of one-giant tensor algebra, already, so representing tensors in it should be "trivial". Maybe I need to explain this sentence in more detail. In short, Atoms are like tensor indexes. That is what an Atom is. The numeric value of a tensor is .. a Value. In the old days, a TruthValue, but now it can be anything.)

* Weights ... I'd have to think about that. We could have WeightNode or WeightLink or WeightValue. I'm not sure which is best, or why.  It depends on lots of details that I don't know yet.

* Python vs. C++ -- I'm worried that this is causing a lot of design confusion.  So, first, lets pretend that `pytorch` was 100% pure C++ code. Then what would be the best possible design? Then AFTER answering this question, move to the next question: "but pytorch is not pure C++, now what do we do?"  I want to separate the abstract conceptual architecture from the details of pytorch. A good neural net design should also work "the same way" with tensorflow, or ... whatever.  It should not be python-specific.

**Comment by vsbogd** [comment]
> serialization

Complexity which I am talking about is that one cannot create atom in its own repository with custom store/load procedure. To add such procedure one need to modify atomspace code.

**Comment by noskill** [comment]
I am not sure i get the "serialization is terrible" idea, aren't postresql persistence is relied upon atom's serialization?

**Comment by vsbogd** [comment]
> Once you start storing data at some special location that is not generically accessible, then every algorithm that accesses data has to be modified to somehow find that data, and do something special with it.

Algorithm can provide an interface which must be implemented by class to be handled correctly by the algorithm. Then it will be possible to create new classes outside of algorithm repo, implement this interface and still be compatible with algorithm. 

For instance atom and value factory methods are implemented by this way. `ClassServer` and `ValueFactory` provides a way to implement and register custom atom/value factory methods. You don't need to have all factory methods in the atomspace. SQL storage procedures for instance can be implemented by the similar way.

**Comment by linas** [comment]
> Algorithm can provide an interface which must be implemented 

Are you serious? So when the pattern miner asks you to implement a special interface, you are just going to do that? And when the pattern matcher asks you to implement a different interface, you will be happy to do that, too? And because postgres wants to do it a third way, you will also implement that also?  What about the pattern matcher, the rule engine, and PLN? That's six different interfaces you have to implement!

This is the opposite of modular programming, modular design. If every subsystem defines its own API for accessing your data, you'll just die from the code-bloat and the testing confusing, and the debugging effort to make all of these interfaces work. Again -- there is a reason that the software industry decides to do things a certain way.  Again -- the atomspace already does so many new and experimental things, its OK to be conservative, and not try to be counter-cultural with everything.

**Comment by linas** [comment]
I feel like I'm brow-beating you -- but maybe this can be solved by working through some examples. Suppose you define an Atom with hidden state. For simplicity, assume it can have only two values: a and b.  The user wants to run the pattern matcher, for find all Atoms where the hidden state is "b". So, 

*  How does the user even know that "b" is a valid state to ask for? Why not ask for (invalid) state  "c"?
* How does the user formulate the query?  Somehow, the user has to be able to express: `SELECT from AtomSpace atom_type=VsBogdNode AND atom_internal_state=b` but written in Atomese, not SQLese.

* What if `VsBogdNode` has two kinds of internal state, one which is A or b, the other which is p or q?  How does the user find all atoms with first-state=b and second-state=q?  How do you give names to these state-containers? Do you call them first and second?  or do they get custom names? If they get custom names, how does the user find out what the custom names are?

* What if first-state is a float, and the second-state is a string? How does the user find that out, so that they can correctly formulate their query for floats and strings? What is the object is compound? Does the user formulate a JSON query? What does the JSON "mean" (ie. what is the "semantics"?)

OK, so those are the issues that the pattern matcher faces.  The pattern miner faces a different set of issues. The pattern miner has to do this:

* Pattern miner has to ask: Hey VsBogdNode, tell me if you have hidden state, and what its called, so that I can get it".
* Pattern miner has to ask: Hey VsBogdNode, tell me if hidden-state-1 is a float or a string, because I count frequency of strings one way, and I perform histogramming bin-counts for floats. Oh, and maybe a clue about the float-range, so I can pick histogram bins of the appropriate widths.
* Pattern miner has to ask: Hey, is this JSON-valued-state, is it a cartesian product of sub-parts, or should I only count it as a whole?

What about the rule engine and the chainers? I think Nil designed to chainers to work like natural deduction, instead of like sequent calculus (I'm not sure). Whichever. So look at the wikipedia article on "natural deduction", and tell me how to map which parts of hidden-state to premises, and which parts of hidden-state to conclusions. 

The current atomspace design solves this by exposing all state in such a way that it can always be found (the atomspace holds all state) and all state can be fully described (the type system can fully express the type of an expression). The "hypergraph query language" aka BindLink, GetLink is "query-complete": if there is some state, the query language can access that state.

If you start hiding state inside of Atoms, you have to provide: (a) a way of accessing that state viz. a collection of "get" methods (b) a way of describing that state, viz a type system and (c) a way of finding that state viz a query system.

But we already have a,b,and c; why would you want to invent a new, different, incompatible a,b,c that parallels the existing system, but works differently?

**Comment by vsbogd** [comment]
I didn't mean that two atoms having same name will have different state. I mean that if I have `(VsBogdNode "a")` it has the state `a`, and if I have `(VsBogdNode "b")` it has state `b`. But `a` and `b` here is not something you can simply convert to string `"a"` or string `"b"`.

PatternMatcher or PatternMiner will use standard atom interface (`get_type()` and `get_name()`) to match these atoms, but atoms will have another interface which is not known to PatternMatcher or PatternMiner and can be used by code which knows how to work with atoms of such type. For instance function called via `ExecutionOutputLink` can get atom state and use it because it knows this atom type.

**Comment by linas** [comment]
ExecutionOutputLink is a temporary, nasty hack that mostly should be avoided if at all possible. The visual-processing code seems to be sufficiently well-defined that there does not seem to be a valid reason to use ExecutionOutputLink; just create the atom and link types that you actually need (as described in the other issue).

Some Atoms have explicit API's -- many have an explicit `execute()` method, if they are executable; others have an `evaluate()` method.  These are teh two big ones, and they are accessible both via scheme and python.  Some of the other atoms have miscellaneous public, documented API's meant to make them work well together; for example, the 5 or 6 different styles of pattern matching are all built in basic infrastructure provided by `PatternLink`, which has half-a-dozen or more public methods, and a big giant mass of "state" -- precomputed, precompiled state that summarizes what's in the pattern, so that it can be found quickly at run-time.

Do that here, as well. Create the nodes and links that you need. Let them do the processing that you need. Don't use GroundedSchemaNodes or GroundedPredicateNodes; they are inadequate for general engineering, they're a low-quality, hard-to-use, badly-designed API into executable code. They are OK for extremely simple use-cases, but you are trying to force them into doing something that they should not be used for.

**Comment by linas** [comment]
Take a look at `opencog/atoms/pattern/PatternLink.h` -- it is an extremely complex atom (maybe the most complex one we have) that has a large amount of "internal state". However, all of that state is computed by the atom constructor, by walking the tree of atoms underneath it -- its derived from state that is openly visible in the atomspace. The "internal state" that it contains is in some sense "invisible"; it does not need to be serialized, it does not need to be saved to the database.  It exists only to make pattern matching run fast.

PatternLink has a public API: `const Variables& get_variables(void)` and  etc. which returns a big complex `Variables` structure containing all sorts of complex info in it. There are at least a dozen other files that work with the info contained in `class Variables` to compute whatever it is they compute.

You can do the same thing with the visual processing code. Write it so that it consists of 2 or 5 different atom types; each of these atom types has some methods, some data attached to them, using documented API's that work with documented data structures, using conventional object-oriented programming style.

What I don't want to see is undocumented code that is using `goto`s to jump from one place to another, while  passing around `void*` pointers to undocumented, mystery data structures.  To me, `ExecutionOutputLink` is a fancy `goto` and `PtrValue` is a fancy `void*` Don't do that. Use ordinary structured programming, instead of using goto's, and use object-oriented programming, instead of using void*'s.

**Comment by vsbogd** [comment]
After discussing this issue and #1970 I start feeling that the only reason why we are suggesting `PtrValue` is that we wanted to make one change to atomspace which allow experimenting with different kind of objects.

I think we can start creating new types of atoms in repository other than `opencog/atomspace`. Then any strange idea can be implemented outside of `opencog/atomspace` repo, we can play with it, and if it seems reasonable for `opencog/atomspace` it can be moved into it. Saying this I don't insist that `PtrValue` is the best possible design for #1970, but I think one need some space to play with it quickly if he wants to. For instance we could start from it and then find that specific atom type suits our needs better.

Adding new types of atoms is possible (for instance `opencog/opencog` repo has new types of atoms) but current atomspace implementation has restrictions on functionality which can be extended outside of atomspace. For example:
- one cannot create its own evaluatable atom outside of atomspace because static methods `EvaluationLink::do_eval*` are used to evaluate atoms (instead of `EvaluationLink::evaluate()`); and the only way to create new `EvaluationLink` type is modifying these methods
- atom with hidden state cannot be injected to the atomspace because copy procedure copies only type and name; it is original question of this issue #1965 and I believe it is answered already

I think the best way is to try adding new atoms in our repo and we will face difficulties with extending atomspace then discuss and fix these things in `opencog/atomspace` repo.

**Comment by ngeiswei** [comment]
@vsbogd, that sounds like an excellent point. I'm not intimate enough with that code to know what should be done concretely but it smells right. If you can build a minimal example of a new atom type with its own execution/evaluation code to exhibit the contention points, I guess that would go a long way. Then it could be turned into a unit test.

**Comment by linas** [comment]
> creating new types of atoms in repository other than `opencog/atomspace`.

This has always been possible. It is also the recommended way for prototyping.

>  because static methods `EvaluationLink::do_eval*`

I don't understand the issue. EvaluationLink is not carved in stone; changes to it can be made, if need be. But I want to see a reasonable explanation of why it's needed; changes based on misunderstanding and confusion are almost never good changes.

> Hidden state

The atomspace is a relational database. I want you to understand what a relational database is, and what a relation is, and all of the basic ideas of relational programming.  I believe that if you understand this, a lot of the confusion about "hidden state" will melt away.

In issue #1970, I proposed a simple, clear, direct easy API for what you are trying to do. I do not understand why that proposal is being resisted, and why you want to do things in this other way.

**Comment by vsbogd** [comment]
>  EvaluationLink is not carved in stone; changes to it can be made, if need be.

I mean that if I will introduce experimental subclass of EvaluationLink in my own repository I will not be able to implement my own `evaluate()` method without touching `atomspace` repo. 

> The atomspace is a relational database.

May be it is not very relevant here but sometimes you don't want to represent the structure of data you have in the database scheme. I don't see many differences with representing `TruthValues` as vector of doubles instead of `ListValue` of `FloatValue`s. You don't need this structure in atomspace and don't have it.

**Comment by linas** [comment]
> sometimes you don't want to represent the structure of data you have in the database scheme

The atomspace does not force you to declare a table structure or a schema, before putting data into it; its free-form (and thus like prolog, rather than SQL). The atomspace does have a partly-finished "deep types" system that allows you to declare one or more schema; examples include https://wiki.opencog.org/w/Type_signature  https://wiki.opencog.org/w/ArrowLink and things linked from there. Its not used very much, which is why its only partly implemented.  What's there works and has unit tests. I'm interested in having dependent types as first-class types, but that's for some rainy day.

> I don't see many differences with representing TruthValues as vector of doubles instead of ListValue of FloatValues. 

Its was done that way for performance purposes. All users wanted to store more than one float, and using LinkValue to string together multiple singletons seemed very inefficient. Currently, there are zero active users of LinkValue, but its there anyway, because otherwise people would complain about not having it.

I'm interested in eventually extending the type system to describe Values; the type system is older than the Values. 

Also EvaluationLink and TrtuhValue are older than values; I'd like to extend `EvaluationLink::evaluate()` so that it returns generic values instead of just truth values. Exactly how to do this without breaking backwards compat and lots of unit tests is not yet clear.

**Comment by vsbogd** [comment]
Closing it as discussion gone too far from original question. Opened #2024 with suggestion on atoms copying related changes.
