### ISSUE TITLE
two classes named "Atom" in python bindings

### ISSUE THREAD

**Issue by linas** [opencog/atomspace#200]
There are two classes called Atom:
One is here:
```
from opencog.type_constructors import *
```
the other is here:
```
from opencog.atomspace import Atom
```

If you don't import these in the correct order, you get very confusing behavior.  (The second import overrides the first)

**Comment by AmeBel** [comment]
The `from opencog.type_constructors import *` approache is less verbose, somewhat similar to what is done in scheme. 

Which one should remain?

**Comment by linas** [comment]
I don't know.  Not sure I care. I think some code breaks somewhere, no matter which one you remove.  

I'm just saying that they need to be merged or unified somehow, as otherwise you get really hard-to-debug situations, where you have atoms but the atoms don't work right and you can't figure out why.

**Comment by inflector** [comment]
Okay, if I'm reading this right,

`from opencog.type_constructors import *`

ends up importing this Atom definition:

```
def Atom(*args):
    return atomspace.add_link(types.Atom, args)
```
via `core_types.pyx`. This function definition is an auto-generated construction function that comes from auto-camel-casing the `ATOM` definition when the OPENCOG_ADD_ATOM_TYPES macro processes `atom_types.script` as part of the cmake processing of `CMakeLists.txt` in `atoms/base`.

So rather than there being two `Atom` classes, there appear to be two identifiers called `Atom`, one of which is the Python binding `Atom` class, the other which is the above `Atom `function and these conflict.

It seems to me that there will be many uses of the `Atom` type as the wrapper for the `Atom` Python binding class and very few using the script-generated `Atom` function. In fact, I doubt that anyone currently uses the `Atom` construction function.

Assuming you concur, I propose that I change the OPENCOG_ADD_ATOM_TYPES macro so it special-cases the processing of the `ATOM` type to not output anything at all for Python.

**Comment by linas** [comment]
>Assuming you concur, I propose that I change the OPENCOG_ADD_ATOM_TYPES macro so it special-cases the processing of the ATOM type to not output anything at all for Python.

That sounds good to me!

**Comment by inflector** [comment]
Pull Request #596 fixes this issue.

**Comment by inflector** [comment]
@linas Ready to be closed

**Comment by linas** [comment]
thanks
