### ISSUE TITLE
Pattern Matcher: ERROR Variable not groundable 

### ISSUE THREAD

**Issue by kasimebrahim** [opencog/atomspace#2093]
<pre>
(GetLink
  (VariableList
    (VariableNode "$num1")
    (VariableNode "$num2"))
  (PlusLink
    (VariableNode "$num1")
    (VariableNode "$num2")))
</pre>
For the above pattern  I am getting an exception "Variable not groundable: (VariableNode "$num2")".
adding quote makes it work,
<pre>
(GetLink
  (VariableList
    (VariableNode "$num1")
    (VariableNode "$num2"))
  (Quote (PlusLink
    (Unquote (VariableNode "$num1"))
    (Unquote (VariableNode "$num2")))))
</pre>

**Comment by linas** [comment]
Interesting bug/feature. So, in `PatternLink.cc` line 642ff, it states that PlusLink, just like other function links, should be executed *before* the pattern match is made. I no longer recall why it was decided to work that way, it seemed to make sense at the time. I'm not sure what code depends on this; I am guessing that the robot behavior trees expected this behavior. I am not sure if this was a good decision, or a bad decision... it is what it is. Clearly, lines 642-676 are very careful to implement this; it is no  accident. 

What this means is that PatternLink knows that it will need to execute the `PlusLink` later on, and it knows that, in order to do this, it will need to find groundings for the two variables. But its impossible to find these, so it throws an error. 

Three solutions are possible. One really bad solution is to remove lines 642-676  and also remove `_pat.executable_holders.` from everywhere in the code. This is probably a really bad idea, at this point.

Another solution is to wrap PlusLink inside of ExistsLink. Like so: 
```
(GetLink
  (VariableList
    (VariableNode "$num1")
    (VariableNode "$num2"))
  (ExistsLink (PlusLink
    (VariableNode "$num1")
    (VariableNode "$num2"))))
```
Currently, this also asserts. But, in this case, it makes sense to treat a top-level PlusLink as if it were quoted: that is, to alter lines 649 or nearby to not look for FunctionLinks when they are at the very top of the pattern. This seems like the correct fix. A big problem is that I don't have time to do it myself. Someone else should learn how this code works; however,  this code is really quite large and complex, so learning it is hard. 

The third solution is not-a-solution, but a work-around. Use QuoteLink. Its ... ugly.

**Comment by linas** [comment]
Hmm. Solution one, the "bad" solution above, is mybe the right one. See pull req #2095. All atomspace unit tests pass when I comment out this code. If the opencog unit tests also pass, then this can be merged.

**Comment by linas** [comment]
Looks like #2095 was harmless. You're welcome!

**Comment by linas** [comment]
Reopening @kasimebrahim could you write a unit test to test this?  The simplest way is probably to find some short yet modern unit test in `/tests/query`, copy it, and hack it to substitute the above into it.

**Comment by ngeiswei** [comment]
@linas, thanks for looking into this. When you say
```scheme
(GetLink
  (VariableList
    (VariableNode "$num1")
    (VariableNode "$num2"))
  (ExistsLink (PlusLink
    (VariableNode "$num1")
    (VariableNode "$num2"))))
```
you mean to use `PresentLink`, not `ExistsLink`, right? Thus as follows
```scheme
(GetLink
  (VariableList
    (VariableNode "$num1")
    (VariableNode "$num2"))
  (PresentLink (PlusLink
    (VariableNode "$num1")
    (VariableNode "$num2"))))
```

**Comment by kasimebrahim** [comment]
Thanks @linas, I will write the unit test.

**Comment by linas** [comment]
> you mean to use PresentLink, not ExistsLink, right? 

Yes. So many link types, hard to keep them all straight.

@ngeiswei so - although 2095 fixed this issue, a more general question remains: when should a portion of a pattern be executed during a search, and when not? So, currently, `GreaterThanLink` is always evaluated during the search. ... because it can only every be true/false (just like PresentLink) so it "makes sense" to evaluate it.

But suppose instead, the query was this:
```
(define sum (GetLink
  (VariableList (Variable "$num1") (Variable "$num2"))
  (And
   (Present (Variable "$num1"))
   (Present (Variable "$num2"))
   (Present (EvaluationLink
        (Predicate "speed of travel")
        (ListLink
            (Concept "miles per hour")
            (Plus (Variable "$num1") (Variable "$num2"))))))))
```
i.e. find all pairs of numbers, that, when added result in an evaluation link that can be found.  Should the Plus be executed, or not?  I think this was the original idea. The above can be worked around:
```
(define sum2 (GetLink
  (VariableList (Variable "$num1") (Variable "$num2") (Variable "sum"))
  (And
   (Present (Variable "$num1"))
   (Present (Variable "$num2"))
   (Equal (Variable "sum") (Plus (Variable "$num1") (Variable "$num2")))
   (Present (EvaluationLink
        (Predicate "speed of travel")
        (ListLink
            (Concept "miles per hour")
            (Variable "sum")))))))
```

The Equal forces the execution of the Plus. Curiously, the above examples crash :-(
 

@kasimebrahim Thank you!

**Comment by linas** [comment]
The example doesn't crash when the variables are constrained: 
```
(define mph2 (GetLink
  (VariableList
   (TypedVariable (VariableNode "$num1") (Type 'NumberNode))
   (TypedVariable (VariableNode "$num2") (Type 'NumberNode))
   (Variable "sum"))
  (And 
   (Present (Variable "$num1"))
   (Present (Variable "$num2"))
   (Equal (Variable "sum") (Plus (Variable "$num1") (Variable "$num2")))
   (Present (EvaluationLink
        (Predicate "speed of travel")
        (ListLink
            (Concept "miles per hour")
            (Variable "sum"))))))) 
```
so it all works.

**Comment by ngeiswei** [comment]
OK, I think I love the idea! So present link would disable evaluatable/executable, and one can always execute them outside of present link and link them using EqualLink. It seems it would remove 99% of the need for quotations.

BTW, just a reminder that `PresentLink` can take multiple arguments so the example above can be written

```scheme
(define mph2 (GetLink
  (VariableList
   (TypedVariable (VariableNode "$num1") (Type 'NumberNode))
   (TypedVariable (VariableNode "$num2") (Type 'NumberNode))
   (Variable "sum"))
  (And 
   (Equal (Variable "sum") (Plus (Variable "$num1") (Variable "$num2")))
   (Present
     (Variable "$num1"))
     (Variable "$num2"))
     (EvaluationLink
        (Predicate "speed of travel")
        (ListLink
            (Concept "miles per hour")
            (Variable "sum")))))))
```

**Comment by linas** [comment]
Thanks!  I cannot guarantee that the `PresentLink` always disables evaluation of what's inside of it. It might be buggy: it was grafted on to a much older design.

I'm wondering in mild horror if the code I just disabled, in pull #2095 had been causing you grief all these years. I hope not.  That would be sad and embarrassing.  .. surely not. It would have caused an error and throw, if you'd stumbled into it.

**Comment by linas** [comment]
BTW. The `mph2` example is an example of a sentence from an "equational theory". That's because it only has one relation: "equal", and no axioms.  

Without the equals, you have only the "empty theory" (duhh - no relations, no axioms) or the "free theory" (you can freely arrange anything any way that you want).

For some reason, the people who write books on this never have an explicit "PresentLink", its always implicit, assumed, obvious, invisible, you are not even aware of any need for it. Like a ghost, things are always "present".

For your entertainment: (this means @kasimebrahim too): https://en.wikipedia.org/wiki/Uninterpreted_function 

Googling "empty theory" also brought up this entertaining but totally off-topic question: https://math.stackexchange.com/questions/1192679/models-of-the-empty-theory

**Comment by linas** [comment]
Actually, `mph2` would belong to the arithmetic theory, because it has addition. Whatever. I'm glossing.

Thinking about these things helps me keep things straight, about what "should" happen.

**Comment by linas** [comment]
... and indeed PresentLink fails to not-exec GreaterThan:
```
(define g5 (GetLink
  (VariableList
   (TypedVariable (VariableNode "$num1") (Type 'NumberNode))
   (TypedVariable (VariableNode "$num2") (Type 'NumberNode)))
   (Present (GreaterThanLink (VariableNode "$num1") (VariableNode "$num2")))))
```
does not "quote" the `GreaterThan`. It should. Openening new issue.
