### ISSUE TITLE
execute_atom does not execute LambdaLink in ExecutionOutputLink using Python

### ISSUE THREAD

**Issue by stellarspot** [opencog/atomspace#2094]
Here is a simple LambdaLink usage which just sums two numbers which works when written in Scheme:
```scheme
(use-modules (opencog) (opencog exec))

(Define
 (DefinedSchema "add")
 (Lambda
  (VariableList
   (Variable "$X")
   (Variable "$Y"))
  (Plus
   (Variable "$X")
   (Variable "$Y"))))

(display
 (cog-execute!
  (ExecutionOutput
   (DefinedSchema "add")
   (List
    (Number "2")
    (Number "3")))))
```
The result is (NumberNode "5.000000")

The same code written in Python which uses execute_atom prints:
```python
from opencog.type_constructors import *
from opencog.utilities import initialize_opencog
from opencog.bindlink import execute_atom

# Initialize AtomSpace
atomspace = AtomSpace()
initialize_opencog(atomspace)

(DefineLink(
    DefinedSchemaNode('add'),
    LambdaLink(
        VariableList(
            VariableNode('$X'),
            VariableNode('$Y')),
        PlusLink(
            VariableNode('$X'),
            VariableNode('$Y')))))

res = execute_atom(atomspace,
                   ExecutionOutputLink(
                       DefinedSchemaNode('add'),
                       ListLink(
                           NumberNode("3"),
                           NumberNode("4"))))
print(res)
```
Output:
```scheme
(ExecutionOutputLink
  (DefinedSchemaNode "add")
  (ListLink
    (NumberNode "3.000000")
    (NumberNode "4.000000")
  )
)
```

**Comment by linas** [comment]
Yeah. Looks like a bug. Fix should be easy!? Care to learn how to fix python code?

**Comment by linas** [comment]
So pull req #2100 provides a quick, cheap fix for this bug. It's deficient in multiple ways. Maybe I could get you to fix up the rest?
* It should get a unit test, so that it stays fixed.
* `execute_atom` should return a ValuePtr, not a Handle.
* It should not be called "bindlink", its got nothing to do with bindlink.

And more general python cleanup: 
* probably all of type constructors, the `execute_atom` should be moved into the main atomspace python/cython module. 
* The whole thing should be called "atomspace" not "opencog". 
* And the whole `initialize_opencog(atomspace)` is a dorky hack that should not be needed.  I mean, if you already did a "import *" you should not need to "initialize opencog" 
* ... which is misnamed, anyway, as that is not quite really what it does... it seems to be declaring the current atomspace that the type constructors use, and not "initializing" anything. So should be renamed to "set_current_atomspace", instead.

There is no python/cython maintainer for the atomspace. I was trying to convince @noskill to maybe try doing this.... maybe that is still possible?

**Comment by noskill** [comment]
@linas feel free to ping me for suitable issues. For this particular bug i belive @stellarspot can fix it too.

**Comment by linas** [comment]
Closing, I think this was fixed.  Open a new issue if still a problem.
