### ISSUE TITLE
atomese api for atomspace manipulations

### ISSUE THREAD

**Issue by noskill** [opencog/atomspace#2105]
Recurrent pattern in our code is creating temporary atomspaces to hold intermediate results. For example in VQA demo https://github.com/singnet/semantic-vision/tree/master/experiments/opencog/pattern_matcher_vqa temporary atomspace is created for current image. It holds bounding boxes nodes and query result. After image is processed temporary atomspace is discarded. To rewrite main loop from python to atomese we need same api for manipulation of atomspaces as in python.

**Comment by linas** [comment]
Issue #1967 is a proposal for how to do this.  It is not implemented. Let me know if this would solve your needs. Here's an example usage:

Place atom into "my atomspace":
```
(AtomSpaceLink
    (AtomSpaceNode "my atomspace")
    (FooAtom "some atom"))
```

Create a temp atomspace:
```
(AtomSpaceLink
     (AtomSpaceNode "my primary atomspace")
     (AtomSpaceNode "my temporary AS-one"))
```
I think I know how to maybe kind of implement this so that it is efficient, simple, small, fast. But I'm not sure, and I need an example use-case to make sure that it solves the problem that you actually have.

**Comment by noskill** [comment]
It might indeed solve the problem of getting rid of temporary object. Looks quite promising.
Usecase is rewriting python code using temporary atomspaces to atomese, for example this function.

https://github.com/singnet/semantic-vision/blob/2681f93cf12ee0e5c1a53faef28a815d9e9c857c/experiments/opencog/pattern_matcher_vqa/pattern_matcher_vqa.py#L332

**Comment by linas** [comment]
If you are using python and/or scheme, I think it is mostly straight-forward to copy atoms from one atomspace to another. In python, you can certainly say `add_atom(some_atomspace, some_atom)` and it will be copied, no matter what atomspace the `some_atom` is in.  What is currently not possible is to move atoms around, using only Atomese.

**Comment by linas** [comment]
I looked at `pattern_matcher_vqa.py` for all of three seconds, before I spotted the word "relex" in it.  This is OK for now, but cannot be the long-term solution. 

The long-term solution really needs to be predicates such as `(PredicateNode "has the color green")` or `(PredicateNode "is to the left of")` so that other subsystems, such as ghost, which does chatbot-like things can get access to these predicates ... as well as PLN, which may want to reason over green things to the left of other things. Or even the pattern miner, or the language learner, which may want to count the number of times that green  things have been seen.

Exactly how to define these predicate nodes is still a bit of an open issue. There are details that I have not worked out completely.

**Comment by linas** [comment]
My naive impression is that it is much more important to have a good, generic design for attaching PredicateNodes to the visual subsystem, and that moving atoms between atomspaces is very much a lower priority.   I'm certainly much more interested in the generic predicate design, than I am in anything else ...
