### ISSUE TITLE
UREConfigUTest.cxxtest crashes with double free or corruption

### ISSUE THREAD

**Issue by ngeiswei** [opencog/atomspace#2130]
I randomly (more that half of the time) get `UREConfigUTest` to crash with 
```
double free or corruption (fasttop)
```
The unit test passes but it crashes at the end.

I have no such problem with Debian (stretch) only with Ubuntu 18.10.

I also have no problem when I run this test standalone, or with the other unit tests as long as they run one after the other (no use of `make -j4 test ARGS=-j4`, make -j4 test` instead).

Guile version is 2.2.4 (on all my boxes).

**Comment by linas** [comment]
Last time that this happened regularly, it was due to shared library destructors running twice -- and specifically, the shared-library destructors for the nameserver/classserver. This is fairly easy to verify: just put a printf into the `__dtor__` for the name/classerver(s)  (look for `static __attribute__ ((destructor)) void fini(void)` I forget the exact reason it was being called twice; somehow about how the  shared libs got linked in. I don't  recall the details. This was supposed to get fixed by the "sircular shared library dependency work" but apparently, was not.

In the past, there were two or three dozen unit tests that failed with this double-free error.  These unit tests had a work-around hack, that simply forced an `exit()` without unloading the shared libs. I removed the hack, when I fixed the circular-lib fixes. So, some of the unit tests from 6 months ago will still have that hack in it.

You have two choices: 

(1) put the hack back in for this one unit test,

(2) Figure out why destructors are running twice, and fix that. Figuring out why is .. confusing. I think that sometimes two copies of the same library get loaded twice (i.e. two copies of one library) or something like that.. If you use printf's, be sure to print library addresses as otherwise it is .. confusing. Do this by this trick:
```
static int foobar;
printf("address is %p\n", &foobar);
```
You're good at GDB, maybe you can figure it out that way.

**Comment by linas** [comment]
Its possible that #2132 might even fix this. Or not. Yes, it seems crazy that something like that might fix it... :-)

**Comment by linas** [comment]
An example for the double-free unit test hack from Nov 2018 is this:
```
   ~AbsentUTest()
   {
      delete eval;
      delete as;
      // Erase the log file if no assertions failed.
      if (!CxxTest::TestTracker::tracker().suiteFailed())
            std::remove(logger().get_filename().c_str());
int rc = CxxTest::TestTracker::tracker().suiteFailed();
_exit(rc); // XXX hack to avoid double-free in __run_exit_handlers
   }
``` 

Notice the bad indentation. Whenever some code is really bad or really broken or wrong, I also indent it badly -- its an eye-catcher, it kind of screams out "I am broken", instead of hiding and pretending like its normal, nicely-behaved code.

**Comment by linas** [comment]
FYI, the old `rule-engine/UREConfigUTest.cxxtest` and `rule-engine/forwardchainer/ForwardChainerUTest.cxxtest` both had this hack in it.  I removed them, when the circular-lib stuff seemed to fix everything.

**Comment by ngeiswei** [comment]
I'm still having this problem (but nothing urgent ofc).

**Comment by linas** [comment]
You can word around it (hide it) by applying the patch above.  I don't particularly want to debug URE today.

**Comment by linas** [comment]
>  have no such problem with Debian (stretch) only with Ubuntu 18.10.

There is a small chance that this is actually a glibc bug. It has happened before, and it usually takes 1/2 a year for a fix to get created and to trickle out to the distros.

**Comment by linas** [comment]
still a bug?

**Comment by vsbogd** [comment]
@linas, we (me and @stellarspot ) are investigating this issue right now, we will post results of analisys here.

**Comment by vsbogd** [comment]
Ok, we have finally found the cause:

In coredump it can be seen that tests which fails loads `libure.so` library twice:
- first one from  `/ws/atomspace/build` directory;
- second one from `/usr/loca/lib` directory;

because C++ test uses `libure.so` functions both directly (being linked to it) and indirectly (via loading Scheme module). Loading Scheme module leads to loading it by `guile` from `/usr/loca/lib` because `guile` uses `libltdl` library as discussed in https://github.com/opencog/opencog/issues/3529#issuecomment-504938563. Twice loading leads to twice construction and twice destruction of static variables of the library.

One can see that this issue happens only for `circleci` configurations where `make install` of the atomspace is done before `make test` ([`cogutil`](https://github.com/opencog/cogutil/blob/fb5163015648320a60fb39e45966a98b12a074ed/.circleci/config.yml#L71) for example). So this is kind of duplicate of https://github.com/opencog/opencog/issues/3529 and it seems to be fixed by @ferrouswheel PRs.

**Comment by linas** [comment]
Thanks  @vsbogd & @stellarspot  !

**Comment by ngeiswei** [comment]
Good finding!
