### ISSUE TITLE
How to filter values from temporary set?

### ISSUE THREAD

**Issue by vsbogd** [opencog/atomspace#2202]
I have the set which is dynamically created. In fact it is returned by `GroundedSchemaNode`. I would like to filter some values from set using `GroundedPredicateNode` as filter. 

I tried to use the folowing `MapLink` expression but it returns empty set and doesn't call `filter`. Is it intended behavior? 

Since `MapLink` seems to be the only atom which can perform pattern matching on some set of atoms (not on the whole atomspace) it looks like there is no possibility to make such filtering.

```scm
(define (filter atom)
  (display "filter called ") (display atom) (newline)
  (SimpleTruthValue 1 1)
)

(cog-execute!
  (Map
    (ImplicationScope
      (TypedVariable (Variable "x") (Type "ConceptNode"))
      (Evaluation (GroundedPredicate "scm:filter") (Variable "x"))
      (Variable "x")
    )
    (Set (Concept "a") (Concept "b"))
  )
)
```

**Comment by linas** [comment]
For now, just use GetLink/BindLink.  These "serch the entire atomspace" only at the conceptual level; in practice, they search only a very tiny part of it, so performance should not be an issue.  However you were able to corral  `(Concept "a") (Concept "b")` into a single set, you should also be able to tag them with MemberLinks, and then pattern-match the memberlinks:  e.g
```
(MemberLink (Concept "a") (Concept "my set"))
(MemberLink (Concept "b") (Concept "my set"))

(cog-execute! (Get (And
   (PresentLink (MemberLink (Variable "x") (Concept "my set")))
   (Evaluation (GroundedPredicate "scm:filter") (Variable "x")))
```
and that should work (modulo optional `(TypedVariable (Variable "x") (Type "ConceptNode"))` and whatever bugs I've introduced)

`MapLink` is a half-baked experiment, that never really worked very well, and perhaps it might be time to remove it.  Here's what happened:
* It seemed like "not searching the whole atomspace" was somehow a good idea. as pointed out above, GetLink already doesn't search the whole atomspace, so it's actually a mediocre idea.
* MapLink potentially allows you to build pipelines ... but so does GetLink.
* Turns out SetLink is a bad idea .. see the wiki page for SetLink, and also one of the github issues for this.  I want to replace all users of SetLink by MemberLink.
* ... all this suggests that maybe MapLink serves no known purpose in life, and should be removed.

**Comment by linas** [comment]
p.s. the advantage of MemberLibnk vs SetLink is:
* you can add/delete to MemberLink any time.
* you can have neamed sets with memberlink
* SetLinks have to be manually deleted when you are done with them; if you don't delete them, they accumulate as zombie garbage in the atomspace, alive but playing no role.
* SetLinks are hard to search, even with GlobNodes, they are hard to search.
* SetLinks don't allow incremental reporting of results. e.g. if you have a very long-running algo, and you have to collect all results in a set-link, then you have to wait until it is done, instead of being able to report partial results immediately  the way you might with a promise/future. (proposal #1750)

**Comment by linas** [comment]
reply edited, click to see full reply...
