### ISSUE TITLE
Hierarchical AtomSpace same atom multiple copies problem

### ISSUE THREAD

**Issue by williampma** [opencog/atomspace#221]
Finally bump into this problem of multiple atomspace outlined on the wiki

>However, if an atom is added to B that does not exist in A, then it will be in atomspace B only. If later it is added to A, then two independent copies shall exist: one in B and one in A. Its not quite clear if this is the 'right' thing to do; but defacto, this is what happens.

This code
```
		AtomSpace as;
		AtomSpace ex(&as);
		AtomSpace ns;

		Handle haa = as.add_node(CONCEPT_NODE, "PLN");
		Handle hab = as.add_node(CONCEPT_NODE, "URE");

		Handle hea = ex.add_link(LIST_LINK, haa, hab);
		Handle heb = ex.add_node(CONCEPT_NODE, "VAR");
		Handle hec = ex.add_link(IMPLICATION_LINK, hea, heb);

		as.add_link(LIST_LINK, haa, hab);

		Handle hna = ns.add_atom(hec);
		Handle hec_copy = ex.get_atom(hna);

		std::cout << hec->toShortString() << std::endl;
		std::cout << hna->toShortString() << std::endl;
		std::cout << hec_copy->toShortString() << std::endl;
```
gives seg-fault on printing hec_copy, becuase hec_copy is actually returned UNDEFINED.

I ran into this type of code path when handling member-to-inheritance-rule and inheritance-to-member-rule in two different steps of BC.

Ideally, it would be great if when the atom is added to A, handles that refer to B's copy will automatically change to refer to A's copy.  Not sure how do-able is this.

**Comment by linas** [comment]
Well, the seg-fault should be fixed, first. The C++ code above is perfectly valid, and its well-defined, and hec_copy should have returned exactly hec; the two should have been pointers to the same atom.

**Comment by linas** [comment]
Regardng the idea: 
>Ideally, it would be great if when the atom is added to A, handles that refer to B's copy will automatically change to refer to A's copy. Not sure how do-able is this.

I agree, except for the "automatically" part.  There tends to be a high overhead for "automatic" things.   Thus, it would be better if a method was added to the AtomTable -- lets call it "promote" that, given atom Xb, looks to see if the equvalent Xa is in the parent(s) A, and, if so, removes Xb from B, and replaces all uses of Xb in B by A's version Xa.

Easier said than done: if B has an extension C, and C is using Xb in some link then .. oh oh .. C now has bad atoms in it. So we have to walk Xb's incoming set, and fix up all users of it.  Fortunately, this is easy, because each atom knows what table it is in.

Also, it might be that A is an extension of  Z, and there is no Xa, but there is an Xz. I guess that means that Xb should be promoted to Xz. 

In some very distant future, if you wanted to make this "automatic" then you could just call the new method you wrote. Otherwise, leave it as manual.

**Comment by linas** [comment]
p.s. the current AtomTable insert code is kind-of-ish too complex. it can be simplified as decribed in bug #223 (which is petty much totally unrelated to above, but could have some impact).

**Comment by linas** [comment]
Why did you close this? the patch  #233 fixes the crash, but the core issue remains...

**Comment by williampma** [comment]
I wasn't sure if a new issue should be created or just leave this open, since the first post is mostly about the crash.
