### ISSUE TITLE
Variable value is not passed to the EvaluationLink under SatisfactionLink

### ISSUE THREAD

**Issue by vsbogd** [opencog/atomspace#2222]
```scm
(ConceptNode "some-node")

(define (print-arg arg) 
(display "print-arg") (newline) (display arg) (SimpleTruthValue 0 0))

(cog-evaluate! 
  (Satisfaction 
    (Variable "x")
    (And 
      (EvaluationLink (GroundedPredicateNode "scm: print-arg") (Variable "x"))
    )
  )
)
```
prints
```
print-arg
(VariableNode "x")
print-arg
(VariableNode "x")
print-arg
(VariableNode "x")
print-arg
(VariableNode "x")
print-arg
(VariableNode "x")
print-arg
(VariableNode "x")

```

But same request with `TypedVariable` passes variable value:
```scm
(cog-evaluate! 
  (Satisfaction 
    (TypedVariable (Variable "x") (TypeNode "ConceptNode"))
    (And 
      (EvaluationLink (GroundedPredicateNode "scm: print-arg") (Variable "x"))
    )
  )
)
```
prints argument correctly:
```
print-arg
(ConceptNode "some-node")
```

**Comment by linas** [comment]
Yuck.  The broken variant can only be satisfied by allowing x to match any/every atom in the atomspace.  The pattern matcher has thousands of lines of code attempting to prevent exactly that kind of situation. Appearantly, it was a little too successful!

**Comment by linas** [comment]
oh, scratch that. It printed six times. Odd. Looking into it.

**Comment by linas** [comment]
BTW, you might find formatted prints more convenient:  its just like printf, except use ~ instead of %  and use ~A to print "anything". So `(format #t "my printy-arg ~A\n" arg)`

**Comment by linas** [comment]
The #t prints to stdout. the #f prints to string  and otherwise its a file handle.

**Comment by linas** [comment]
Ah, and you should have seen this message:
`[WARN] No type restrictions! Your code has a bug in it!`  but Nil downgraded/suppressed that, because PLN triggers it all the time.

**Comment by linas** [comment]
fixed by #2223

**Comment by linas** [comment]
I didn't write a unit test for this, to make sure it stays fixed ... I still consider searches of the entire atomspace to be pathological (there are other, simpler ways of doing that, if that's what you really want)

**Comment by ngeiswei** [comment]
> Ah, and you should have seen this message:
> [WARN] No type restrictions! Your code has a bug in it! but Nil downgraded/suppressed that, because PLN
> triggers it all the time.

I didn't suppress anything
```scheme
scheme@(guile-user)> (use-modules (opencog logger))
scheme@(guile-user)> (cog-logger-set-stdout! #t)
scheme@(guile-user)> (cog-execute! (Get (Variable "$X") (Variable "$X")))
[2019-06-14 03:35:29:243] [WARN] No type restrictions! Your code has a bug in it!
```

**Comment by linas** [comment]
@ngeiswei  ah, this is from some 5-year-old argument; maybe it was not you but with Shujing;  the original idea was that whenever some Get or Bind  attempted to search the entire atomspace, it would throw an exception, instead of printing a warning.  But somehow the argument went "we really want to iterate over the entire atomspace", so the exception is now ifdef'ed out.   When I re-enable it, at least three unit tests fail.  So this behavior is now baked in. Still, long-run Id like to remove it (and throw an exception again)

One of the problems is that a complete search is inefficient; a second is that, for Get/BindLink's, the content of the atomspace keeps changing (since SetLinks keep getting added) and so one hits an infinite loop. There is a hand-coded infinite-loop detector in there, so that the code doesn't blow up.  But that just seems...  I dunno, I don't like it.

**Comment by ngeiswei** [comment]
Well, maybe it was me ;-) I don't remember, but certainly today the URE is resilient to that, even throwing rather than warning should be fine on my end.

**Comment by linas** [comment]
OK, But there are three unit tests to be re-examined, and I don't feel like doing that today.  I'm scrambling trying to get the codebase for learning back on track. There's still a lot to do there.

**Comment by vsbogd** [comment]
It is fixed, thanks!
