### ISSUE TITLE
Function type of arbritrary number of arguments

### ISSUE THREAD

**Issue by ngeiswei** [opencog/atomspace#2240]
How to declare a function (arrow type) of a function that takes an arbitrary number of arguments, such as `PlusLink`?

For matching we can use `GlobNode`, for instance

```
TypedVariableLink
  GlobNode "$args"
  TypeNode "NumberNode"
```

however this requires the variable to be specified as glob, such type information cannot be used on an anonymous variable, thus cannot be wrapped in an `ArrowLink`. Perhaps we could use `ListLink`, for instance

```
ArrowLink
  ListLink
    TypeNode "NumberNode"
  TypeNode "NumberNode"
```

However `ListLink` is a not a type constructor, not sure it's a good idea. Maybe we could introduce a `TypeGlobLink`, or a `TypeListLink`, not sure

```
ArrowLink
  TypeGlobLink
    TypeNode "ConceptNode"
  TypeNode "ConceptNode"
```

then how to add `IntervalLink` in the mix? Using `TypeSetLink`? Clearly `IntervalLink` only makes sense when speaking about something that has an arity, like a `GlobNode`. Would the following work for representing a function that take 2 or more numbers and outputs a number?

```
ArrowLink
  TypeSetLink
    TypeGlobLink
      TypeNode "NumberNode"
    IntervalLink
      NumberNode "2"
      NumberNode "-1"
  TypeNode "NumberNode"
```

Sorting that out would also allow to use variable nodes as glob nodes, as described in https://wiki.opencog.org/w/GlobNode#Variables_as_GlobNodes

**Comment by linas** [comment]
Yes, more or less.  You have a typo which confused the issue, I think. It should be `TypeNode` or `Type` for short, not `NodeType`  The "for short" makes it clear:
```
Type "NumberNode"
```
Instead of `TypeGlobLink`, make it  `VAType`  where VA is supposed to make you think of varags in C/C++. Perhaps `VarArgType`. Both `VAType` and `VarArgType` would be Nodes, not links.

For example:
```
Arrow
   VAType "ConceptNode"
   Type "ConceptNode"
```
is a function that takes a variable number of ConceptNodes, and returns on ConceptNode.  Your last example would read almost the same way:
```
Arrow
  TypeSet
      VAType "NumberNode"
      Interval
          Number "2"
          Number "-1"
  Type "NumberNode"
```

**Comment by ngeiswei** [comment]
Of course!!! However I don't think the variadic atom should be a node because you may want to attack a composite type to it. So it should be more something like
```
Arrow
  TypeSet
      VAType
          Type "NumberNode"
      Interval
          Number "2"
          Number "-1"
  Type "NumberNode"
```

Regarding the name, what should we choose? I see 3 contenders

1. `VAType`
2. `VariadicType`
3. `VarArgsType` (or `VarargsType`)

I'm also not sure of the order of `VA` or such and `Type`. For instance we have `TypeSet`, `TypeChoice`, etc, maybe we want `TypeVA`, etc?

**Comment by linas** [comment]
I like the word `Variadic`. However, looking at what I wrote, and what you wrote, it seems like no new atom type is needed.  `TypeSet` is already variadic.  Maybe `TypeSet` should have been called `VariadicLink` or `TypeVariadicLink` from the very beginning.  I called it a "set" because I imagined throwing other things in there, besides the interval spec, although I could not yet imagine what those "other things" might be.

So:  using existing notation, and code that already "works" (at least, currently works within the pattern matcher):  a list of 2 or more numbers:
```
  TypeSet
      Type "NumberNode"    ;; The interval below signifies this is variadic
      Interval
          Number "2"
          Number "-1"
```
 A list of two or more number/concept nodes, mixed arbitrarily:
```
  TypeSet
      TypeChoice
              Type "NumberNode" 
               Type "ConceptNode"
      Interval
            Number "2"
            Number "-1"
```

 A list of two or more number nodes, only, or a list of concept nodes, only (no mixing):
```
  TypeChoice
          TypeSet
                 Type "NumberNode" 
                  Interval
                        Number "2"
                        Number "-1"
          TypeSet
                 Type "ConceptNode" 
                  Interval
                        Number "2"
                        Number "-1"
```
This last one I'm not too sure about.  I think it's correct.  A list of alternating concept-number pairs of arbitrary length (the two must alternate one-for-one C-N-C-N-..)
```
  TypeSet
      Signature
              Type "ConceptNode" 
               Type "NumberNode"
      Interval
            Number "2"
            Number "-1"
```
In the above, `SignatureLink` is acting like a `ListLink`, but for types. I can't use `ListLink` because that can already be mixed in with type declarations, e.g. a list of two or more ListLinks, with each ListLink being concept-number:
```
  TypeSet
      ListLink
              Type "ConceptNode" 
               Type "NumberNode"
      Interval
            Number "2"
            Number "-1"
```
and, of course, a list of two or more EvaluationLinks:
```
  TypeSet
      Evaluation
              Type "PredicateNode" 
              ListLink
                   Type "ConceptNode"
                   Type "ConceptNode"
      Interval
            Number "2"
            Number "-1"
```
A list of two or more "is-inside-of" Evalutation links:
```
  TypeSet
      Evaluation
              PredicateNode "is-inside-of" 
              ListLink
                   Type "ConceptNode"
                   Type "ConceptNode"
      Interval
            Number "2"
            Number "-1"
```

**Comment by linas** [comment]
I updated the wiki page for https://wiki.opencog.org/w/TypeSetLink to say the above, and to explicitly use the word "variadic".   There already is code and unit tests for most of what is on that page, although I suspect that the more complicated examples will trigger bugs or asserts.

**Comment by ngeiswei** [comment]
But isn't that inconsistent with `TypeSetLink` being a form of type intersection? As it can be used as such, for instance
```atomese
TypedVariable
    Variable "$foo"
    TypeSet
        TypeInh "UnorderedLink"
        TypeCoInh "SetLink"
```

Also, would

```
TypeSet
   Type "ConceptNode"
```

be equivalent to

```
Type "ConceptNode"
```

or

```
TypeVariadic
  Type "ConceptNode"
```

?

I fear that confounding type intersection and variadic is gonna lead to ambiguities, while this can be avoided by introducing a `TypeVariadic` or such link, which doesn't require to modify the existing code since in the case of `GlobNode` we know that it is variadic, which is I suppose 100% of the use cases of `TypeSet` as variadic type as of today.

**Comment by linas** [comment]
> Also, would
> ```
> TypeSet
>   Type "ConceptNode"
> ```
> be equivalent to
> ```
> Type "ConceptNode"
> ```
> or
> ```
> TypeVariadic
>    Type "ConceptNode"
> ```

Yes, both, with the implicit understanding that, without any actual `(Interval (number lo) (Number hi))` statement, that lo=hi=1 i.e. it defaults to just one instance.

> 100% of the use cases 

Yes, as of today, the only use I know of for `TypeSet` is to twiddle GlobNodes.  Ghost uses this, and the language-learning pipeline uses this.

Yes, I suppose we could rename `TypeSet` to `TypeVariadic`  ... slowly, so that existing users can update their machines in a timely fashion :-) Let them co-exist for a month or two while machines get upgraded.

The TypeInh./CoInh trick is a .. trick. A kind of "Look Ma! No hands!" kind of trick. There's a unit test for it; it works. Its got an almost trivial implementation. Its hard to imagine who would really need that.

**Comment by ngeiswei** [comment]
I do think that `TypeSet` as type intersection can be useful in the future. But anyway, if any type is basically a singleton variadic by default, then I guess no need to change anything, it all gets coherent. Defaults can be a little bit dangerous, as anything that is implicit, on the other hand it I guess it saves some syntax.

**Comment by ngeiswei** [comment]
I've added the following section in the wiki https://wiki.opencog.org/w/TypeSetLink#Variadic_and_type_intersection

There's still a part of me that isn't sure about such blend but I guess we can let it for now.

**Comment by ngeiswei** [comment]
> Yes, I suppose we could rename TypeSet to TypeVariadic ... slowly, so that existing users can update their machines in a timely fashion :-) Let them co-exist for a month or two while machines get upgraded.

Well, if we do introduce `TypeVariadic` then they would not co-exist just for a month, but for ~ETERNITY~, because as I said `TypeSet` used in combination with `GlobNode` is completely unambiguous anyway, so that usage doesn't need to be updated (unless the users want to), and I believe `TypeSet` as type intersection can be used in the future (I can see URE rules making use of it for instance) thus we would keep it as well.

**Comment by linas** [comment]
Well, I just mean that we can fix it, but that some period of backwards-compat is needed.

The API slowly accumulates cruft, we can slowly fix it. it's not urgent.  You're right, TypeSet is a mashup of two kind-of unrelated ideas that just happen to work together. But this wasn't clear when it got invented, and now that it's getting clear, we can fix it.  But sometimes its better to wait, ...

**Comment by linas** [comment]
p.s. re; parametric polymorphism and dependent types ... I'm more-or-less ready to have those discussions, I think. I've gotten quite comfortable with parametric polymorphism, having written huge wads of code in that style over the last few years. Its more or less central to the "objects are closures, closures are objects" idea, and it's the simplest way of doing objects in scheme. The `atomspace/opencog/matrix` directory contains a dozen parametric-polymorphic objects.

**Comment by linas** [comment]
except I'm also busy with other things ...

**Comment by linas** [comment]
I think this issue can be closed? If there are still some unfinished ideas here, they should be copied to new issues...

**Comment by ngeiswei** [comment]
I don't mind closing it.
