### ISSUE TITLE
is_free_in_tree behavior has changed

### ISSUE THREAD

**Issue by ngeiswei** [opencog/atomspace#2290]
The bug introduced in the atomspace that fails the unifer is in

https://github.com/opencog/atomspace/blob/0928e9d17b9917fdbe58abd68c21ecdc9f5f796e/opencog/atoms/core/FindUtils.cc#L219-L241

After https://github.com/opencog/atomspace/pull/2286 the following returns false

```
is_free_in_tree(
tree=
(QuoteLink
  (PutLink
    (LambdaLink
      (VariableNode "$X")
      (VariableNode "$X")
    )
    (UnquoteLink
      (VariableNode "$Y")
    )
  )
)
,
atom=
(VariableNode "$Y")
)
```

I don't think that is the desired answer, clearly `$Y` is free in the put link.

**Comment by linas** [comment]
OK, I'll look at that now & fix it. I know what I was trying to do, and I thought the changes were innoccuous.

**Comment by linas** [comment]
I see the bug.  the new code didn't know that the Put was quoted.

**Comment by linas** [comment]
fixed in #2291

**Comment by ngeiswei** [comment]
Wow, thanks!

**Comment by linas** [comment]
welcome. BTW, all of the `is_whatever` functions are wrong, if the given term appears twice in a tree .. say, once quoted, and once not quoted ... I have not spent any time thinking about how to fix this.  At the moment, it is merely an obscure unlikely bug to be hit in some indeterminate future...

**Comment by linas** [comment]
Looking more closely, I think all of the routines are just fine, except for one:

`is_quoted_in_tree` -- what if it's also unquoted somewhere else in the same tree? 

All the others seem unambiguous, and are not a problem: for example, `is_unquoted_in_tree` -- I assume that means it appears at least once unquoted, even if it is also quoted elsewhere in the same tree.

**Comment by ngeiswei** [comment]
I'm almost certain `is_quoted_in_tree` returns true if `atom` appears both quoted and unquoted in the tree, but yeah I guess it should probably be checked and the comment should mention it.

**Comment by linas** [comment]
Not urgent. the pending pull req does touch that one comment.

So, totally off-topic, but the pending pull req now adds a more-or-less fully-functional ForAllLink to the pattern matcher.  I had to change the name to "Always" because ForAll was already taken by PLN.  But it seems to work, and there's a demo for it, and I'm excited, because three days ago I would have said "well that's impossible" or "don't do it, its a bad idea(tm)" and it turned out to be not too hard.

(and of course, you can think of `PresentLink` is the pattern-matchers "there-exists")
