### ISSUE TITLE
Inconsistency between GetLink and BindLink in specific contects

### ISSUE THREAD

**Issue by astroseger** [opencog/atomspace#2306]
This issue is connected to #2304 

In the following context GetLink and BindLink work differently (but they probably should return the same result)

```
(use-modules (opencog) (opencog exec))
(define imp1 (ImplicationLink (VariableNode "X0") (VariableNode "X1")))
(define imp2 (ImplicationLink (VariableNode "X1") (VariableNode "X5")))

; the following will return empty list
(cog-execute! (GetLink (VariableList ) imp2))

; the following will return (SetLink *imp1*)
(cog-execute! (BindLink (VariableList ) imp2 imp2))

```

**Comment by linas** [comment]
No, its correct as is. The BindLink has the form "if P then Q" where both P and Q are `imp2`.  Since the variable list is empty, P is a constant, its always found in the atomspace, thus is always true, thus Q is always returned.

The GetLink is the form "if P(x) then x" and P(x) is again `imp2` but `x` is the empty list.  Once again,  P is a constant, its always found in the atomspace, thus is always true, and so the empty list is returned.
