### ISSUE TITLE
Introduce VariableSet for commutative variable declarations in scopes

### ISSUE THREAD

**Issue by ngeiswei** [opencog/atomspace#2325]
## Problem

In some scopes, the order of the variables in the variable declaration does not matter. I.e one can say that such scope are Variable Declation Permutation Invariant, or VDPI for short.

That is typically the case for bind links. For example

```
Bind
  VariableList
    Variable "$X"
    Variable "$Y"
  Present
    Inheritance
      Variable "$X"
      Variable "$Y"
  List
    Variable "$X"
    Variable "$Y"
```

and

```
Bind
  VariableList
    Variable "$Y"
    Variable "$X"
  Present
    Inheritance
      Variable "$X"
      Variable "$Y"
  List
    Variable "$X"
    Variable "$Y"
```

are behaviorally equivalent, yet are not alpha-equivalent.

On the contrary, for instance

```
Get
  VariableList
    Variable "$X"
    Variable "$Y"
  Present
    Inheritance
      Variable "$X"
      Variable "$Y"
```

and

```
Get
  VariableList
    Variable "$Y"
    Variable "$X"
  Present
    Inheritance
      Variable "$X"
      Variable "$Y"
```

are not behaviorally equivalent.

It would be nice if there was an easy way to take this into account as to avoid over-representing these scopes. In other words, pushing alpha-equivalence up to VDPI.

## Proposal

I'm not completely sure but we could introduce a `VariableSet` construct, analog to `VariableList`, expect that it would re-order the variables following predetermined order like `UnorderedLink`.

The reason I'm suggesting that instead of just taking care of scopes that we know are VDPI like BindLink, is because sometimes whether this is determined by usage rather than scope type, so letting the user the freedom to choose could be a plus.

Their might be better ways, any thought on the matter is welcome.

**Comment by linas** [comment]
`VariableSet` seems perfectly fine.

For `BindLink`, I've occasionally thought about moving the variable declarations out of the header, and into the body itself.  I don't recall the syntax that would be needed for this, and I can't find it in my notes. This hasn't been done because it would add yet more complexity to an already-complex decoding of the body of the `BindLink`. (its already quite the mess, with fixed clauses, virtual ones, evaluatable ones, optional/must-be-absent clauses, logical connectives tying them together... Throwing variable decls into that risks further confusing the issue, at least, at this point in time, in the current code base).  I'm not sure why I even bring this up... other than to say its possible, but ill-advised.

**Comment by ngeiswei** [comment]
This seems to be working so I'm closing.
