### ISSUE TITLE
UnorderedUTest::test_embed randomly fails

### ISSUE THREAD

**Issue by ngeiswei** [opencog/atomspace#2371]
Since 981e35a09 `UnorderedUTest::test_embed()` randomly fails.

**Comment by linas** [comment]
I merged #2372 as a work-around to this, but that commit should be a no-op.  That is: the permutations are just a copy of the outgoing set ... since all permutations are explored, the order should not matter ... by default, outgoing sets are already placed into canonical sort order .. and so the sort performed here should be a no-op, since the outgoing set is already sorted.  So it should be a no-op.

The only bug I can imagine is that maybe, with all reference passing, the outgoing set inside the atom itself was getting shuffled....  

I'll look into this, but I have never seen the "random failure" ...

**Comment by linas** [comment]
So far:

* With sort: zero crashes in 38K test runs.
* With sort commented out: 12 crashes in 28K runs.
* Direct return of outgoing set:

**Comment by linas** [comment]
Explicit compare of the permutations before and after sorting shows that sort is a no-op; the order is unchanged by sorting ...

**Comment by linas** [comment]
How did you even find this? Does this crash more often for you? It takes about 5 mins to run this test 1K times, so I get crashes about every half-hour ... do you have a way of making this crash more frequently?

**Comment by linas** [comment]
Hmm .. I wonder if its related ti the weak-pointers in the pattern term, and that sometimes, they are used without checking (i.e. are used unsafely) then, perhaps some finalization triggers, invalidating one of the pointers, and resulting a bad pointer ref...

**Comment by linas** [comment]
Also -- to be clear: when you say "fails", you mean "crashes"?  I'm havng trouble collecting a log file, it seems to be crashing before the log file has a  chance to be written.

**Comment by linas** [comment]
Hmm. It's not leaving behind a core file.  Test does seem to run to completion, even when it fails.  Unfortunately, CxxTest does not report the error to the opencog logger. If I try to capture stdout to a file (instead of `/dev/null`) it never crashes -- I'm 3 hours and 15K iterations in, no crash yet.  Not sure how to collect a trace....

**Comment by linas** [comment]
Ohh .. OK, so making it write synchronous to log file seems to have upset the timing that causes the fail (it doesn't seem to be a crash, I have not been able to squeeze a core file out, yet) ... the test runs 3x or 4x slower when `logger().set_sync_flag(true);` is set. This makes it run so slow that the timing window that leads to the failure closes.   Will run overnight, see if I get lucky...

Any hints suggestions/tips on how to make this fail faster appreciated.

**Comment by linas** [comment]
Ran all night, zero failures.

**Comment by ngeiswei** [comment]
By fail I mean fail, the unit test fails, the result of the matching is 1 while it should be 2. And that failure (used to) occurs once every 3 run.

**Comment by linas** [comment]
> once every 3 run.

That's with unmodified code? Just everything straight up, checked out of git?  What OS and compiler are you on?

**Comment by linas** [comment]
Wow. I've got at least two crazy problems.

1) Logger is insane; log files have repeated blocks in them. One log file has the first 98 lines, containing  4388 bytes, repeated three times in the logfile. 

2) `operator<()` on `class Handle` is failing to do an actual content compare.

**Comment by linas** [comment]
Logger:

0) The repeated portion contains 25 log messages (i.e. 25 calls to logger().fine() or logger().debug())
1) Checking return value on fprintf() and fflush reveals no errors.
2) checking number of file opens indicates that only one logfile open has occurred.
3) checking the number of writer threads indicates that only one (and always the same) writer thread is active.

Anyway, since the block of repeated log messages is 25 messages long, this suggests that its not the writer thread at fault. The writer thread only dequeues one message at a time, to write it.  it's as if it dequeued 25 messages, and then the queue forgot, and reverted back to a form where the 25 messages are still on queue... and not just once, but twice ... Maybe the queue is getting clobbered?

**Comment by linas** [comment]
Forward progress at last:  replacing `sort(perm.begin(), perm.end());` by `sort(perm.begin(), perm.end(), std::less<PatternTermPtr>());`  causes the unit test to fail once out of every three times.

This now hints at the true problem: both sorts should have been no-ops.  For me, the first sort is a no-op (comparing the before and after order, its always the same) while the second should have also been a no-op, since the sort order of the outgoing set should always be the same, since the atoms in there are supposed to be deterministically ordered by the hash, which should always be the same.  Apparently, the outgoing set of the unordered link is not being sorted according to the hash, but according to the address space randomization.  Why it takes 5000 tries for one to fail, and 3 tries to get the other to fail is still mysterious.

**Comment by linas** [comment]
OK, so it seems that #2376 fixes this. Apparently there was a crazy mixture of address-based sd::less and content-based std::less that lead to crazy-making. So this got fixed.

PLEASE NOTE: (IMPORTANT!) calling `sort(HandleSeq.begin(), HandleSeq.end())` does NOT use `std::less<Handle>`. Instead, it just uses `std::less<std::shared_pointer<Atom>>` which performs an address-compare. 

So far, have done 7.5K unit tests with no crash ... crossing fingers....

**Comment by linas** [comment]
Closing; 34K unit tests so far, without any failures.  This exceeds the previous failure-free records, including the overnight run.

**Comment by ngeiswei** [comment]
Wow, I didn't think about that address vs content compare, crazy, well done!
