### ISSUE TITLE
split python initialization and setting default atomspace in python api

### ISSUE THREAD

**Issue by noskill** [opencog/atomspace#2391]
Current python api is confusing. My idea is

1)  give user set_default_atomspace function to set current default atomspace - analogous to cog-set-atomspace in guile.  
2) perform python initialization automatically - it is possible to check if python is already initialized using Py_IsInitialized function.

**Comment by vsbogd** [comment]
> perform python initialization automatically - it is possible to check if python is already initialized using Py_IsInitialized function.

@noskill, what will trigger Python initialization? Do you mean importing any opencog package will initialize Python interpreter?

**Comment by noskill** [comment]
I think it can be delayed until PythonEval instance creation,  wherever it happens.

**Comment by vsbogd** [comment]
I would not remove `initialize_opencog` completely as lazy initialization has disadvantages.
In case of lazy initialization software developer don't control point when initialization happens:
- it may lead to unexpected errors after some work is already done;
- performance could be poor at some critical step because initialization happens at this moment.

Taking it into account I would keep `initialize_opencog` for cases when software developer would like to control moment initialization happens. If one doesn't work to call it right now `PythonEval::instance()` already creates new instance if it is not created already.

I agree that split Python initalization and atomspace setting is a good idea. I looked at `PythonEval` code and I see that `_atomspace` is used to set global `ATOMSPACE` variable for each loaded module. But this global `ATOMSPACE` variable is not used in code.

**Comment by linas** [comment]
It would be useful to clarify the different usage scenarios.  The ones I see are:

1) User starts python first, then does `import atomspace` then creates atoms, etc. with python.

2) User starts cogserver first, then runs python scripts inside cogserver.

For case 1) it seems pointless to have `initialize_opencog` .. everything should be initialized by the time that the `import` finishes.  Also, its pointless to ask the user to set a "default atomspace" it could be set automatically during the import. Changing it makes sense only if the user wants to work with more than one atomspace (which is an advanced thing to do; almost no users will ever do this.).  

There are two interesting subcases:

1a) Python user loads scheme file(s) e.g. by using PLN, where the "formulas" are in `GroundedPredicate "scm:some-formula"`  and scheme has to get the correct atomspace. I'm not sure if there's a unit test for this or not.

1b) Python user starts the cogserver.  In this case, the cogserver needs to use the same atomspace as python. I'm not even sure if the python API's allow you to start the cogserver.

For case 2) the cogserver has already created an atomspace, and python should use this atomspace as the default (instead of trying to switch to a different one.) In the past, a recurring bug was that the cogserver-atomspace already held a bunch of atoms, and then the python-atomspace held copies of some of these same atoms, but because they were copies, the TV's went out of sync.  This was a confusing situation.  

At any rate, for case 2), you also do not need `initialize_opencog` since its already initialized.

For case 2) there are two subcases:

2a) user telnets to cogserver, starts `py-shell` and starts doing python commands. There are two sub-cases:

2a-i) User has a long-running python session, typing stuff by hand.

2a-ii) User has very short sessions, less than a a tenth of a second, sending very very short python snippets to create one or two atoms, or alter a TV or whatever. There is not even any `import atomspace` because it's assumed this was done earlier. I don't recall now, but I think this is how the robot-ROS interfaces worked. Or something like that. Going through a complex re-initialization sequence would be insane in this scenario.

Finally, there's a case:

2b) User starts cogserver, and runs scheme code which does `GroundedPredicate "py:do_stuff"`  .. again, the correct atomspace should show up.

Some of these (most of these?) have unit test cases, but ... maybe not?

**Comment by linas** [comment]
Anyway .. it was all of these different usage scenarios that lead to all of the crazy-making in the cython code. Things like the global `ATOMSPACE` and also  the `_atomspace`, as well as `initialize_opencog` and also `set_current_atomspace` were all supposed to be "solutions" or at least "hacks" to work around badness in one of these usage scenarios.   Typically, fixing one of these would usually break another one, and so, for example, the way you used python from the cogserver `py-shell>` prompt was different from the external stand-alone `python3>` prompt .. and these differences lead to .. more craziness.   In the ideal case, the user thinks that both prompts work the same way, even if we do something a bit different under the covers.

**Comment by linas** [comment]
This seems partly/mostly fixed in #2398 however, we still have #2411 (the `initialize_opencog` call is not needed, it should be done automaticay during `import opencog`) and also #2409 (type_ctor atomspace is split across three different python modules, setter in one, getter in another, and the global itself in a third.)

**Comment by vsbogd** [comment]
I would close it as there are two other issues to track PR comments.
