### ISSUE TITLE
Explicit representation of the bottom type

### ISSUE THREAD

**Issue by ngeiswei** [opencog/atomspace#2490]
`Variables::extend` applied on incompatible types, such as

```scheme
(TypedVariable
  (Variable "$X")
  (Type "ConceptNode"))
```

and

```scheme
(TypedVariable
  (Variable "$X")
  (Type "PredicateNode"))
```

must return a bottom type.

As of today the code would return

```scheme
(TypedVariable
  (Variable "$X")
  (TypeChoice))
```

which is actually conceptually correct, because an empty disjunction is false (by virtue of being the neutral element), thus corresponds to the bottom type.

However, the following pattern matcher query

```scheme
(Inheritance (Concept "A") (Concept "A"))
(define X (Variable "$X"))
(cog-execute! (Get (TypedVariable X (TypeChoice)) (Inheritance X X)))
```

returns

```scheme
(SetLink
   (ConceptNode "A")
)
```

which is inconsistent with `(TypeChoice)` being the bottom type.

Also, as it turns out we already have a bottom type

https://github.com/opencog/atomspace/blob/f53b99a9544dedebfaab06e135d90d12f9d719b6/opencog/atoms/atom_types/atom_types.script#L15-L18

however, due to not inheriting from `NODE` or `LINK` (or even `ATOM`) it has no scheme binding.

So the questions are:

1. How to properly handle and represent the bottom type?
2. What role should `(Typechoice)` have and how to make it consistent with the pattern matcher?

**Comment by ngeiswei** [comment]
My suggestion would be

1. Introduce

```
Top
``

and

```
Bottom
```

which would be the type equivalents of

```
TrueLink
```

and

```
FalseLink
```

2. Fix the pattern matcher so that `(TypeChoice)` is treated as `(Bottom)`.

**Comment by linas** [comment]
I like the idea of Bottom Type, this seems to be consistent, and sticking it into `Variables::extend` and the pattern matcher seems reasonable. 

Just to be clear: For this:
```
(cog-execute! (Get (TypedVariable X (TypeChoice)) (Inheritance X X)))
```
and also for this:
```
(cog-execute! (Get (TypedVariable X (TypeChoice 'NoType)) (Inheritance X X)))
```
the GetLink can be pre-compiled into an always-fail condition. Trivially-fail. Some flag somewhere (maybe in the c++ `class QueryLink`, that aborts the search before it even starts, because it can never be satisfied. 

I'm a little (a lot?) more nervous about introducing Top.  Maybe because it is not obviously needed? Maybe because a Top type is inherently contradictory? For example, what is the "top" or "universalization" of `AndLink` and `OrLink`? How can that make sense? `BooleanOperatorLink`  so OK, I click through to https://en.wikipedia.org/wiki/Top_type and so obviously, in opencog, `Atom` is the "top" ... except that `Atom` is not literally at the top, its kind-of- at the bottom, just above `NoType`.  

The confusion here is with that of lattice theory and partial orders: https://en.wikipedia.org/wiki/Lattice_(order) where "bottom" is "least", while "top" is "greatest" ... FYI, many lattices don't have a top, or a bottom, or have one but not the other. Somewhere in wikipedia, there are simple examples. I've not really looked at this in the context of type theory. 

Also, FYI, this:  https://en.wikipedia.org/wiki/Initial_and_terminal_objects  and I think that, in type theory, "bottom" is the type of the "initial object" and "top" is the type of the "final object", when these exist. Viz. "types" are the "kinds" of objects in categories.

I'm not sure we have to be theoretically clean just right now; adding needed `if(..){...}` as needed into the code base, to make it do "common sense" things is entirely acceptable.

**Comment by linas** [comment]
> I'm not sure we have to be theoretically clean just right now; adding needed if(..){...} as needed into the code base, to make it do "common sense" things is entirely acceptable.

I'm saying this because I want to avoid "quick-set concrete" which has to be jack-hammered out at a later date, when its  found to be incorrect.

**Comment by ngeiswei** [comment]
Thanks @linas, I agree no need to introduce `Top` for now. So I guess Kasim and I will work toward introducing `Bottom` and fixing the pattern matcher to trivially-fail when vardecl is, or equivalent to, bottom.

**Comment by linas** [comment]
closing, #2494 is merged, and I don't see any other remaining issues described here...
