### ISSUE TITLE
Variables::substitute_nocheck does not alpha-convert when required

### ISSUE THREAD

**Issue by ngeiswei** [opencog/atomspace#2504]
## Problem

`FreeVariables::substitute_nocheck` does not alpha-convert scope links in order to avoid name collision, whereas the comment

https://github.com/opencog/atomspace/blob/23ce42661444021e80973a06ff52baf184aa4e88/opencog/atoms/core/Variables.cc#L435-L438

indicates that it should.

## Reproduction

Enable the following unit test

https://github.com/opencog/atomspace/blob/d1d898dc6daa179982ddaec2860d1164acbdc048/tests/atoms/core/VariablesUTest.cxxtest#L853

## Solution

Fix `FreeVariables::substitute_scoped` to perform alpha-conversion when required.

**Comment by linas** [comment]
Very odd, because there's a huge blob of code: 

https://github.com/opencog/atomspace/blob/23ce42661444021e80973a06ff52baf184aa4e88/opencog/atoms/core/Variables.cc#L465-L536

that appears to be trying to protect the bound variables. So this is surprising.

**Comment by linas** [comment]
Oh, never mind; I see. The unit test is testing something very different from what the comments 
https://github.com/opencog/atomspace/blob/23ce42661444021e80973a06ff52baf184aa4e88/opencog/atoms/core/Variables.cc#L435-L438 
were intended to describe. And likewise, the big blob of code is handling the intended case.  The unit test is valid, but unexpected, so I'm not surprised that it failed.

The existing code is designed to handle this case:
```
(Inheritance (Variable X)  (Scope (Variable X) (... stuff ...)))
```
so that when substituting, only the first `X` is substituted; the second `X` is not. That is why the comments talk about "alpha-hiding" instead of "alpha-renaming" -- the second `X` is just hidden away during substitution. 

What you describe in the new unit test requires an actual renaming.
