### ISSUE TITLE
Glob node fix for Nested Arithmetic Link

### ISSUE THREAD

**Issue by Eman22S** [opencog/atomspace#2564]
I am working on URE-based reduction and attempting at porting contin-rules .  I found a couple of issues that needed to be fixed for Glob node .
 
1. Glob nodes under nested arithmetic links do not get executed e.g
if we have this in the atomspace
```
 (use-modules (opencog) (opencog exec))
(PlusLink
    (Number 3)
    (Number 10))
```
and we have this rule 
```
(define test
 (BindLink
      (PlusLink
         (Glob "$op")
         (Number 10))
 
      (PlusLink
         (Glob "$op")
         (Number 10))))
```
This can `(cog-execute! test)` and give
```
(SetLink
  (Number 13))
```

But if you run this rule using `cog-execute!`
```
(define test
 (BindLink
   (PlusLink
     (Glob "$op")
     (Number 10))

   (TimesLink
      (PlusLink
         (Glob "$op")
          (Number 10))
       (Number 30))))
```
It produces this as an output
```
(SetLink
   (TimesLink
      (PlusLink
         (GlobNode "$op")
         (NumberNode "10")
      )
      (NumberNode "30")
   )
)

```

**Comment by linas** [comment]
@Eman22S  Not sure why you closed this, but OK. This does sound like it could be a bug. It also sounds vaguely like a bug that was fixed a week or two ago; not sure. Be sure to pull the latest atomspace.

Also: please be aware: the latest atomspace contains several new link types useful for reduct: a step function (the HeavisideLink) which is zero for negative values, and is one for positive ones.  There is now also a MinLink and a MaxLink which compute the min and max of a set of values.

Last bu not least: please be aware that NumberNode now holds vectors, same as FloatValue and so you can say:
```
(Plus (Number 1 2 3 4 5) (Number 6 7 8 9 10))
```  
to get `(Number 7 9 11 13 15)` -- all functions - Plus, Times etc as well as Min Max, Heaviside all support vectors.

I mention vectors because this is a natural way to support tables. Make the columns into column vectors: when you add two columns, you add all of the row entries in the columns. Ping @ngeiswei  as you too should be aware of this vector ability, just in case you aren't.

**Comment by Eman22S** [comment]
@linas  I was going to mention where the code was creating this before I accidentally submitted it. 

Anyway, it appears this line  [https://github.com/opencog/atomspace/blob/master/opencog/atoms/execution/Instantiator.cc#L583 ]()
is the one creating the problem as it does not examine if the arithmetic link contain inside it a nested arithmetic link and simply push ```     (PlusLink
         (Glob "$op")
          (Number 10))
```  of our example into `oset_results`. https://github.com/opencog/atomspace/blob/master/opencog/atoms/execution/Instantiator.cc#L585. calling  back `instantiate` can fix this https://github.com/Eman22S/atomspace/blob/glob_node_fix/opencog/atoms/execution/Instantiator.cc#L606

**Comment by linas** [comment]
So if this is still a bug, you should reopen it! 

It seems like you also found a fix .. you should have created a pull req for it. As it happens, I also found a fix, a simpler one ... it had a comment in the code saying "shouldn't we be doing this?" and when I made it "do this", it started working. Funny how that is... I'll pull req shortly after more testing.

**Comment by linas** [comment]
Closing, fixed in #2566

**Comment by Eman22S** [comment]
> So if this is still a bug, you should reopen it!
> 
> It seems like you also found a fix .. you should have created a pull req for it. As it happens, I also found a fix, a simpler one ... it had a comment in the code saying "shouldn't we be doing this?" and when I made it "do this", it started working. Funny how that is... I'll pull req shortly after more testing.

 I haven't looked at that one, if your is simpler we can go with it. Will wait for it to be merged!

**Comment by Eman22S** [comment]
@linas I would also like you to like into glob nodes under quote link it has been troubling me alot. I have also  attempted to fix it and could open a separate issue describing the problem  well and how I intended to fix it. let me know if I should.
