### ISSUE TITLE
path to libsmob in as-config.scm is wrong

### ISSUE THREAD

**Issue by noskill** [opencog/atomspace#2608]
on my system it points to "/usr/local/lib/opencog/", 
while libsmob got installed in /usr/local/lib64/opencog/

Where the path is getting its value?

**Comment by ngeiswei** [comment]
I got that on Fedora too, which I fixed it by creating a symbolic link but that's a hack.

**Comment by linas** [comment]
Argh.  Certain people forced `as-config.scm` upon us, and its been a headache ever since.  It violates the "everything should be as simple as possible" commandment.

It is created in the build dir by `ADD_GUILE_MODULE` which is defined in `cmake/OpenCogGuile.cmake` 

Around line 311 it says `"(define-public ${SYMBOL} \"${CMAKE_INSTALL_PREFIX}/lib/opencog/\")\n")` and in Fedora that needs to be lib64

The fix is to find some Cmake variable that says "lib64" .. I will look for one now.

**Comment by linas** [comment]
Hmm, maybe it is this: `"lib${LIB_DIR_SUFFIX}/opencog"`

**Comment by linas** [comment]
Closing, I'm pretty sure that #2609 will fix this. If not, please re-open this bug.
