### ISSUE TITLE
Remove constant clause with pattern matcher, or not?

### ISSUE THREAD

**Issue by ngeiswei** [opencog/atomspace#2641]
My understanding is that constant clauses are removed during initialization. This is corroborated by this

https://github.com/opencog/atomspace/blob/7bc74eb08b1ec41f4605d78c47633cfa77ab8aef/opencog/atoms/pattern/PatternLink.cc#L59

which is however in contradiction with this unit test

https://github.com/opencog/atomspace/blob/7bc74eb08b1ec41f4605d78c47633cfa77ab8aef/tests/query/ConstantClausesUTest.cxxtest#L405-L422

Digging deeper, the reason this unit test passes is because its clause

```scheme
(Inheritance (Concept "DA") (Concept "DB"))
```

is actually not considered a constant by

https://github.com/opencog/atomspace/blob/7bc74eb08b1ec41f4605d78c47633cfa77ab8aef/opencog/atoms/pattern/PatternUtils.cc#L95-L119

because, `InheritanceLink` inherits from `EvaluatableLink`.

Of course fixing it results in `ConstantClausesUTest::test_constant_pattern()` to fail.

So I'm asking, how should constants be treated?

I should mention that on my [URE] end, removing constants is no problem, even if, as tested by `test_constant_pattern` these constants are in a different atomspace, because the URE does the checking anyway (as it was agreed previously).

So what should be done?

1. Should `test_constant_pattern` be modified to expect `(Set (Concept "DB"))`? And therefore `is_constant` be fixed?
2. Should `test_constant_pattern` not be modified? But in that case `is_constant` is still not doing what it says it does, in which case the pattern matcher should be fixed elsewhere as well.

**Comment by ngeiswei** [comment]
BTW, the intermittently failing ure utest is linked to that issue. I do not mind fixing it but I need to know what is the desirable behavior.

**Comment by linas** [comment]
The root issue goes back to a very old debate: Should the pattern engine look at TV's, or not? 

Clearly for `Evaluation GPN` it *must* run the GPN.  The GPN returns a TV, now what?  The current ad-hoc solution is to look at the TV with `if (tv->strength > 0.5)` and completely ignore the confidence.

What about `Evaluation PN` ? There is nothing to run! Should we look at the TV? The current ad-hoc solution is "yes" -  to see if it is present, and if it is, then  to look at the TV with `if (tv->strength > 0.5)` and completely ignore the confidence. 

What about `InheritanceLink`? There is nothing to run! Should we look at the TV? 

I think all of the old ad-hoc solutions should be deprecated, because they are no longer needed. We have a more precise, more controllable mechanism available: So, if you really want the TV on `InheritanceLink`, you can say
```
(GreaterThan (TruthValueOf (Inheritance X Y)) (Number 0.5))
``` 
Similarly for  `Evaluation PN` and also for  `Evaluation GPN` (!!) This would avoid the "problem" of ignoring the confidence, because there is a `ConfidenceValueOf` and so one can now say things like `(Times (TruthValueOf...) (Minus (Number 1) (ConfidenceOf...)))` and so on. 

So, I propose several solutions:

1) Make `InheritanceLink` be not evaluatable. I don't really care, either way; it was marked evaluatable because I think you asked for that, to make something in PLN work better.

2) Spew warning if `Evaluation PN` is found in the pattern.  There are many unit tests that will trigger on this, but do we have any "legacy code" that depends on this? Probably not.... so is this a good idea?

3) Should we continue to handle `Evaluation GPN` automatically, or should we ask all users to convert to `(GreaterThan (TruthValueOf (Evaluation GPN ...)) (Number 0.5))` ?

**Comment by linas** [comment]
Short answer: we can mark `Inheritance` to not be `Evaluatable`, and I'll clean up any failing unit tests, if any.

**Comment by linas** [comment]
BTW, looking now: currently, the following are evaluatable: MemberLink, Inheritance, SimilarityLink, SatisfyingSet, ImplicationScope, Implication and everything that inherits from them.

Since none of these actually require run-time evaluation, I propose changing them to not be evaluatable.  Doing so allows all unit tests to pass, except `ConstantClauses`.

We could invent a new type: `ThisAtomHasATVThatYouMightBeInterestedInLink` and inherit from that type. Or, better yet (Ben wanted this long ago!) have a `ProbababilisticInterpretationLink` and a `FuzzyInterpretationLink`, and have atoms inherit from one or the other, depending on how the SimpleTV's should be interpreted. 

I like this last one the best. Can you send a list of which ones are supposed to be fuzzy, and which ones probabilistic?

**Comment by ngeiswei** [comment]
Regarding `ProbababilisticInterpretationLink` and `FuzzyInterpretationLink`, it might be a good idea, though as of right now PLN has rules for that anyway, and I think it would be better if the prob vs fuzzy vs mixture is encored in the Value itself, as proposed in https://github.com/opencog/atomspace/issues/833, there's a prototype by @rTreutlein that needs to be cleaned up and merged to https://github.com/opencog/distributional-value.

**Comment by ngeiswei** [comment]
> I propose changing them to not be evaluatable

Yep, it works, none of the ure and pln utests fail, so it's clearly the way to go. Thanks!

**Comment by linas** [comment]
@ngeiswei the point of having a `ProbababilisticInterpretationLink` and a `FuzzyInterpretationLink` is that it allows consistency checking: if (for example) a MemberLink has the wrong kind of TV attached to it, you can spot this.

**Comment by ngeiswei** [comment]
Actually as proposed in https://github.com/opencog/atomspace/issues/833 mixing probabilistic and fuzzy TVs can be consistent.
