### ISSUE TITLE
Feature Request: the IncrementLink

### ISSUE THREAD

**Issue by einalex** [opencog/atomspace#2668]
Should replace a NumberNode in a StateLink with a NumberNode of increased value, depending on the value of a provided NumberNode.
~~increment the value(s) of a NumberNode by a given other NumberNode. Similar to what `x += y` does in python.~~

Should maybe be called differently as it can also be used to decrement the value, but a better name doesn't yet come to mind. "NumberModificationLink" ? Doesn't seem elegant.

```python

IncrementLink(
            SomeAtom,
            SomeNumberNode)

PutLink(
            VariableNode("count"),
            StateLink(
                SomeAtom,
                VariableNode("count")),
            PlusLink(
                SomeNumberNode,
                GetLink(
                    VariableNode("count"),
                    StateLink(
                        SomeAtom,
                        VariableNode("count")))))

-----------------

IncrementLink(
            ListLink(
                        ConceptNode("The old tree"),
                        PredicateNode("Number of apples")),
            NumberNode("23"))

PutLink(
            VariableNode("count"),
            StateLink(
                ListLink(
                    ConceptNode("The old tree"),
                    PredicateNode("Number of apples")),
                    VariableNode("count")),
            PlusLink(
                NumberNode("23"),
                GetLink(
                    VariableNode("count"),
                    StateLink(
                        ListLink(
                            ConceptNode("The old tree"),
                            PredicateNode("Number of apples")),
                        VariableNode("count")))))
```

**Comment by linas** [comment]
Heh. That is not what was described in issue #2627 -- all Nodes and Links are necessarily immutable and so this cannot be implemented as described.They're immutable for many reasons - to avoid race conditions, to avoid dangling pointers, consistent access, etc,  all the standard reasons listed on e.g. wikipedia.  The only thing you can do is add to the atomspace, and delete from it. (The only thing that StateLink does it to add and delete in a thread-safe manner).

All mutable state goes into Values. The trade-off is that Values are not searchable. (that is, the set of keys on an atom are not searchable. Hmmm .. I guess we could add a `KeysOfLink` to expose them to searches. But that would be an actual exhaustive search, instead of a fast-tracked index lookup.  Immutablity allows the construction of indexes that are guaranteed stable, and do not need thread-locking...)

If you have to have mutable state that is also searchable, you have to cobble it together with Statelinks, which you are already doing. For example
```
(Put
    (State (Predicate "foo") (Variable "new"))
    (Plus (Get  (State (Predicate "foo") (Variable "old"))) (Number 1))
```
which gets the old state, adds 1 to it, and inserts it as the new state.  its verbose.

**Comment by einalex** [comment]
yeah, sorry it was late.
I'm actually using the StateLink version of this. Will edit the top post.

Regarding Values, it's a bummer that we can't look them up in a directed fashion and get truth values based on other values...

kind of like
`(ValueGreaterThanLink (ConceptNode "oven") (PredicateNode "Temperature") (NumberNode "200"))`

**Comment by linas** [comment]
> it's a bummer

except that *does* work.  You can include in your search pattern
```
   (GreaterThan
      (ValueOf (ConceptNode "oven") (PredicateNode "Temperature"))
      (NumberNode "200"))
```
and that works just fine.  So you can search that way.  What you cannot do is to ask "Get all of the atoms that have a key called `(Concept "temerrpature")`" because there is no master index of all keys cross-referenced according to what atoms they were in. ... if such a master index existed, then it would defeat the purpose of values, which is to be small and fast.  Indexes are large, and consume a lot of RAM... in typical databases, indexes consume 80% or 90% or RAM, the actual data consumes much less.  and the AtomSpace is no different: Atoms are small approaching tiny, but keeping track of them all is RAM-intensive.  That's the speed-size tradeoff.

**Comment by linas** [comment]
The original proposal was in https://github.com/opencog/atomspace/issues/2627#issuecomment-633113829 and it suggested that
```
(IncrementLink (Predicate "counter") (Concept "thing") (Number 1)) 
```
is a short-hand for 
```
(SetValue (Predicate "counter") (Concept "thing") (Plus (Number 1) (GetValue (Predicate "counter") (Concept "thing"))))
```
It has nothing to do with StateLink.

BTW, @einalex you realize, don't you, that you are using `StateLink` to implement something vary similar to the Values system, but .. differently?  What you are doing works, but its duplicating values, which, in most ways, are simpler, smaller, faster.  If you didn't quite realize this, then maybe you should think about this some more...

BTW, values can be used to wrap rapidly-changing data, e.g. video, audio streams, GPU state, etc. which would be impossible using `StateLink` (no one has used them for video or audio .. but the idea is there..)

**Comment by einalex** [comment]
Oh, we have SetValueLinks now?
That's great! :)

**Comment by einalex** [comment]
Ah, `GetValueLink` doesn't yet exist on the python side for some reason.
Also not on the wiki.

**Comment by linas** [comment]
It's called `ValueOfLink`

**Comment by einalex** [comment]
Oh! `(GetValue (Predicate "counter") (Concept "thing"))))` confused me.

**Comment by linas** [comment]
:-) I will edit that comment now

**Comment by einalex** [comment]
ok, I'm trying 

```python
crate_count = PredicateNode("crate count")
someone = ConceptNode("bob").truth_value(1.0, 1.0)
SetValueLink(crate_count, someone, NumberNode("1"))

has_crates = GreaterThanLink(
                    ValueOfLink(
                        crate_count,
                        someone),
                    NumberNode("0"))
results = evaluate_atom(atomspace, has_crates)

```

and getting
```
Traceback (most recent call last):
  File "./example5.py", line 119, in <module>
    results = evaluate_atom(atomspace, has_crates)
  File "execute.pyx", line 23, in opencog.execute.evaluate_atom
RuntimeError: No value at key (ConceptNode "bob" (stv 1 1)) ; [510da4194021b685][1] on atom (PredicateNode "crate count") ; [428cc022ef986b3b][1] (/home/rasberry/git/atomspace/opencog/atoms/flow/ValueOfLink.cc:67)

```

**Comment by einalex** [comment]
Ok...
trying this:
```python
crate_count = PredicateNode("crate count")
someone = ConceptNode("bob").truth_value(1.0, 1.0)
SetValueLink(someone, crate_count, NumberNode("1"))

has_crates = GreaterThanLink(
                    ValueOfLink(
                        someone,
                        crate_count),
                    NumberNode("0"))
results = evaluate_atom(atomspace, has_crates)
```

getting

```
Traceback (most recent call last):
  File "./example5.py", line 120, in <module>
    results = evaluate_atom(atomspace, has_crates)
  File "execute.pyx", line 23, in opencog.execute.evaluate_atom
RuntimeError: No value at key (PredicateNode "crate count") ; [428cc022ef986b3b][1] on atom (ConceptNode "bob" (stv 1 1)) ; [510da4194021b685][1] (/home/rasberry/git/atomspace/opencog/atoms/flow/ValueOfLink.cc:67)
```

**Comment by linas** [comment]
Yes, that's it.

**Comment by linas** [comment]
Closing, based on comment https://github.com/opencog/atomspace/issues/2668#issuecomment-638582230 and the subsequent discussion.
