### ISSUE TITLE
Memory usage during compilation is high

### ISSUE THREAD

**Issue by mmmkkaaayy** [opencog/atomspace#2708]
I'm trying to compile AtomSpace in an Ubuntu VM with 16GB of allocated RAM. While running `make -j`, I notice that my memory usage goes up to the entire 16GB (idle memory usage is ~500MB). When that happens, my VM freezes for a few minutes until the system OOM process killer comes along and kills the compilation. I can see elevated disk usage while the VM is frozen, which I believe is a result of it trying to save overflow memory to swap.

I can rerun `make -j` multiple times in order to finish compilation since it seems to be reusing resources from previous runs.

The same thing occurs when I try to run the unit tests with `make -j test`. For this, I can't just keep rerunning the command to make it eventually work.

Is it normal for compilation/unit tests to take more than 16GB RAM? Is there anything I can try other than buying more RAM?

**Comment by linas** [comment]
Sure! don't say `make -j` !!

If you say `make` it will run just one compile thread.  .. and that should be fine, but slow-ish.  If you say `make -j2` it will use two CPU cores.  `make -j4` will use 4... and `make -j` will run all jobs in parallel, no matter how many cores you have, and so you need enough RAM to compile the largest directories.  I think one of the directories has more than 30 files, so that would launch more than 30 compilations at the same time ...

**Comment by linas** [comment]
We need to change the instructions that say `make -j` ... where did you find this .. the README?

**Comment by linas** [comment]
FWIW, this stuff runs on a Raspberry PI with one or two gigs of RAM ... you stumbled onto a development issue.

**Comment by mmmkkaaayy** [comment]
Ah... that makes a lot of sense. Peak memory utilization with `make -j8` was 3GB of RAM. Thanks!

And yes, I found `make -j` in the README, which I believe you've already fixed :)

**Comment by linas** [comment]
ツ
