### ISSUE TITLE
SatisfactionLink problem 

### ISSUE THREAD

**Issue by manisabri** [opencog/atomspace#2821]
https://github.com/opencog/atomspace/blob/master/examples/pattern-matcher/satisfaction.scm#L34
Above is not returning any results

**Comment by linas** [comment]
Hmm, That's an old feature added for open-psi ... and I guess it bit-rotted. And its apparently unused, since no one has complained.  It's been replaced by a different mechanism ... which only sort-of works ... which apparently no one has noticed, either. 

Anyway, I fixed it up, I'll push a pull req tomorrow. It is ... a less than entirely thrilling fix, but it's also an experimental feature, subject to change. It's trying to solve an old, icky problem; none of the solutions seem terribly elegant, so far, but no one is using them, either, so it doesn't matter much.

**Comment by manisabri** [comment]
Some unit tests for these kind of stuff that are not that popular but still gonna remain in the repository gonna be useful I guess. Prevent newbies like me the confusion. Same goes for that attention value problem, a unit test could have prevented that

**Comment by linas** [comment]
When someone thinks they need some feature, they usually write a unit test for it -- there are 175 unit tests for the atomspace, alone. Some features, like this one, get added as "experimental" features, to see how they work out, or, in this case to solve an open-psii problem. When they fail, it is a signal that the code is obsolete. There's no unit test mostly because no one thought it was important. (I don't, I can't do all the work here, even though it feels like that sometimes)

**Comment by linas** [comment]
fixed in #2821 .. by rewriting the example.
