### ISSUE TITLE
std::map<Handle, ***> unadded atom operator< issue

### ISSUE THREAD

**Issue by williampma** [opencog/atomspace#287]
I am having problems with std::map of unadded handles.  This is hard to reproduce deterministically since it depends on the address assigned.  Suppose the following
```
Handle h1 = (ConceptNode "A")   no UUID, with AtomPtr address 0x8
Handle h2 = (ConceptNode "B")   no UUID, with AtomPtr address 0x4
```
then create a map
```
std::map<Handle, int> my_map;
my_map[h1] = 100;
my_map[h2] = 200;
```
Now, since std::map stores using operator< order, internally it's stored in [h2, h1] order.

Then
```
Handle h3 = (ConceptNode "A")  no UUID, with AtomPtr address 0x2
my_map.count(h3) == ??
```
std::map first compares h3 with h2 (well, sort of... it looks like std::map stores its keys in a tree), found h3 < h2 to be true, and concludes that if h3 is in my_map, it would have been stored in front of h2, so h3 is not in my_map.  In fact h3 is in my_map in the form of h1.

So it seems 2 atoms not inside atomspace yet should not be compared by the AtomPtr address (not for operator< anyway).

**Comment by linas** [comment]
Huh? But h3 is not the same as h1, they point to two different atoms! 

The only way that h3 can be the same atom as h1 is if they both point to exactly the same address in RAM.  If they don't point to the same address, they are not the same atom!  

I mean, that is the whole point of having an atomspace in the first place!

Think of it this way: if, in the above example, you set the TV on h3, and you then fetch the TV on h1, can you expect the two to be the same?  No, of course not -- they point to different atoms.   Suppose you wanted to "fix" this, so that whenever you changed the TV on h3, it would automatically find h1, and change the TV there, as well.  How could you even find h1?

The whole point of the atomspace is to resolve this ambiguity -- given a pointer to an atom, you can ask it "do you have another atom that is equivalent to this one, and if so, please give it to me" (the get_atom() function) and "do you have another atom that is equivalent to this one, and if not, please add this one" (the add_atom() function).

The atomspace is the only reasonable way to de-duplicate atom pointers.  You could try to "fix" the handle compare method, but the TV example would remain broken.   

Note also: your example breaks down if h1 was placed in atomspace a1, and h3 was placed in atomspace a3:  both would belong to an atomspace, each would have a different UUID, even though both would have the same type and string name... 

For this reasons, I'm closing the bug report -- it does not seem legitimate.
