### ISSUE TITLE
Haskell build error inside a docker container.

### ISSUE THREAD

**Issue by AmeBel** [opencog/atomspace#310]
pulling latest change and building results in the following,
```
[ 90%] [ 90%] Built target atomspace_bm
[100%] Built target scheme_wrapper
Built target ruleengine
[100%] Building Haskell bindings.
opencog-atomspace-0.1.0.0: build
setup-Simple-Cabal-1.18.1.5-x86_64-linux-ghc-7.8.4:
.stack-work/dist/x86_64-linux/Cabal-1.18.1.5/build/autogen/Paths_opencog_atomspace.hs:
permission denied

--  While building package opencog-atomspace-0.1.0.0 using:
      /home/opencog/.stack/setup-exe-cache/setup-Simple-Cabal-1.18.1.5-x86_64-linux-ghc-7.8.4 --builddir=.stack-work/dist/x86_64-linux/Cabal-1.18.1.5/ build lib:opencog-atomspace --ghc-options -hpcdir .stack-work/dist/x86_64-linux/Cabal-1.18.1.5/hpc/.hpc/ -ddump-hi -ddump-to-file
    Process exited with code: ExitFailure 1
make[2]: *** [opencog/haskell/CMakeFiles/haskell-atomspace-lib] Error 1
make[1]: *** [opencog/haskell/CMakeFiles/haskell-atomspace-lib.dir/all] Error 2
make: *** [all] Error 2
```
@ngeiswei do you know what is happening?

**Comment by ngeiswei** [comment]
Hi @AmeBel I had a similar problem before, the following file has the wrong the permission (it must be owned by root or something), the solution is just to delete it

.stack-work/dist/x86_64-linux/Cabal-1.18.1.5/build/autogen/Paths_opencog_atomspace.hs

But I'm surprise you're getting such a problem since your compile on a pristine system every time, right?

**Comment by AmeBel** [comment]
where is `.stack-work/dist/...` couldn't find it.

I encounterd it when, I pulled recent atomspace changes for installing into the docker container and commit the docker container into an image, for future use;  because rebuilding the container takes some time.

**Comment by ngeiswei** [comment]
It's really strange, what is the current SHA? And what was the previous SHA?

**Comment by AmeBel** [comment]
I don't think it is realted with any particular git commit. I had encountered it a couple times before today, i just circumvented it by purging stack and ghc. 

A clean docker build doesn't trigger the error though.

**Comment by MarcosPividori** [comment]
Hi,
 ".stack-work" dir is located in <ATOMSPACE_ROOT>/opencog/haskell/

I see the reason of this problem, let me explain myself:
- Stack works on the ".stack-work" directory. It builds the haskell package there.
- We are executing stack through a "add_custom_target" on cmake.

When we run "make": stack is executed and the haskell package is built in the ".stack-work" dir.
When we execute "sudo make install": stack is executed again, as root, but, as it has done all the work on the building step, it doesn't do anything here.
So, it was fine until now.

With new versions of Stack, some behaviour has changed. It looks like Stack always modifies some files when executed, not matter if the package was built before.
So, with new versions of Stack, when you run: "sudo make install", Stack will modify some files as root in the .stack-work dir, and future calls to "make" (without root) will fail, because stack tries to modify the same file without root access.

So, what is the solution?? Avoid executing stack when installing, only when building.

I have made a commit that fixes this.
I hope this helps!

**Comment by AmeBel** [comment]
Thanks @MarcosPividori that fixed it

**Comment by ngeiswei** [comment]
Thanks, Marco!
