### ISSUE TITLE
GetLink over a ChoiceLink in body isn't returning result.

### ISSUE THREAD

**Issue by AmeBel** [opencog/atomspace#474]
### Atomspace content and Scheme function

``` scheme
(StateLink
    (Node "action-on-demand")
    (ListLink
        (ConceptNode "Increase")
        (ConceptNode "Novelty")))

(define (get-current-goal)
    (cog-execute!
       (GetLink
          (TypedVariableLink
              (VariableNode "demand")
              (TypeNode "ConceptNode"))
          (StateLink
              (Node "action-on-demand")
              (ListLink
                  (ChoiceLink
                      (ConceptNode "Decrease")
                      (ConceptNode "Increase"))
                  (VariableNode "demand"))))
    )
)
```
### Present Output

``` scheme
guile> (get-current-goal)            
(SetLink                             
)                                    
```
### Expected Output

``` scheme
guile> (get-current-goal)            
(SetLink  
       (ConceptNode "Novelty")                        
)                                    
```

**Comment by linas** [comment]
Has nothing to do with StateLink, fails the same way with any other link type.  I believe that the code expects ChoiceLink was to wrap things with variables inside of it ...

**Comment by linas** [comment]
If the ChoiceLink wraps other links, then it works.  The fail case is only when ChoiceLink wraps nodes. ChoiceLink does NOT need to  wrap variables.

When ChoiceLink wraps nodes, the start search-trem structure gets confused,...

**Comment by AmeBel** [comment]
ok thanks,

**Comment by linas** [comment]
It seems that fixing this will be difficult; however, I think it will also simplify the code -- the correct fix seems to be to remove the "start_term" everywhere, ad use the normal do_term_up code from everywhere.

**Comment by linas** [comment]
A fix for this would be nice, as lots of relex-related rules need this.

**Comment by linas** [comment]
still a bug

**Comment by vsbogd** [comment]
Would you mind if I will get it? 

I experimented with solution which uses PatternTerm tree to find thinnest term and  use thinnest term as start point for do_term_up. Such approach solves the issue.

**Comment by linas** [comment]
If you have a fix, please create a pull request. However, I don't quite like that you mention PatternTerm; that is a device for managing the back-tracking state of unordered links, and should not be part of a fix for this particular bug. 

My comments from Nov 2015 above suggests that code could be simplified by removing `start_term` ...

**Comment by vsbogd** [comment]
Hi @linas,

I see that since https://github.com/opencog/atomspace/pull/229 PatternTerm tree is used for traversing query during pattern matching. For instance first parameter of do_term_up() is PatternTerm which is used to get parent term: https://github.com/opencog/atomspace/blob/4997169521d1c303e155cd04f9c43d10389f1785/opencog/query/PatternMatchEngine.cc#L1509-L1516 As another example ordered_compare() use PatternTerm to get list of outgoing links: https://github.com/opencog/atomspace/blob/4997169521d1c303e155cd04f9c43d10389f1785/opencog/query/PatternMatchEngine.cc#L180-L184
Only start of the search uses original pattern to get start_term but it is replaced by PatternTerm in  PatternMatchEngine::explore_term_branches() method where all possible PatternTerms branches are explored.

What I am suggesting to do is replacing code in InitiateSearchCB::neighbor_search which explores incoming set of the thinnest term: https://github.com/opencog/atomspace/blob/4997169521d1c303e155cd04f9c43d10389f1785/opencog/query/InitiateSearchCB.cc#L391-L399
by calling do_term_up(). But to call do_term_up() thinnest PatternTerm should be searched first.

**Comment by vsbogd** [comment]
I have raised PR to review approach https://github.com/opencog/atomspace/pull/1701

**Comment by linas** [comment]
Yes, perhaps using PatternTerm more widely is not a bad idea.  However...

PatternTerm was originally invented to keep track of search-state for unordered links.  When exploring an unordered link, one has to explore all possible permutations. If exactly the same unordered link appears in two different locations in the pattern, one has to explore permutations on each, independently.   The PatternTerm keeps track of the two different locations, thus allowing each site to have different back-tracking state.

In this bug, we are not exploring alternative permutations of the ChoiceLink. So I'm confused as to why the solution would need to involve PatternTerm. Can you explain, in words, why the switch to PatternTerm could be expected to fix the bug?

**Comment by linas** [comment]
Pull req #1705 fixes this bug. Closing.

**Comment by linas** [comment]
Again: the primary issue is that PatternTerm is fairly heavy-weight: it uses a lot of RAM, and its slow. So I'm thinking that a good collection of benchmarks for the pattern matcher are fairly important to guide future changes.  I'm resisting this one, because of cost/benefit concerns.

**Comment by vsbogd** [comment]
Ok, got it will switch on benchmarks then.
