### ISSUE TITLE
why make _virtual & _fixed clauses private?

### ISSUE THREAD

**Issue by AmeBel** [opencog/atomspace#492]
### Question
@linas What is the reason for making [_virtual and _fixed](https://github.com/opencog/atomspace/blob/master/opencog/atoms/pattern/PatternLink.h#L87-L89 ) private and not public in [Pattern struct](https://github.com/opencog/atomspace/blob/master/opencog/query/Pattern.h#L48) ?

Yes `unbundle_virtual` can be used to get the values, but if I am not mistaken one has to use PatternLinkCast to get to `_pat` for it's fields so as to pass back to `unbundle_virtual` along with some new HandleSeq to capture the result, which had already been found during the cast but have to be recomputed?

### Purpose
get to the separated clauses for composing new patterns. Of course a get methods could be added to PatternLink, but Pattern struct seems to be a container for holding these kind of pattern-structure informations.

**Comment by linas** [comment]
Don't quite understand the question.  Casting does not cause any computation to happen .. casting is just a pointer cast (a fancy cast, because they are reference counted)   Computation is done in the class constructor... 

If you want to assemble new patterns out of parts, and just need to get parts, why not just  create a new PatternLink (in C++) let the C++ constructor untangle the parts, and then pull the parts out of the Pattern?  If you need to get _virtual or _fixed, just add getters for those.

unbundle_virtual() is marked private because ... it is easier to support it if no one uses or mis-uses it.  So, it may depend on certain steps being done in a certain order, or certain steps being done afterwards; these steps might not be documented.   its avoids error checking, which might be needed if it was public. It may change in the future, it was not meant to be a stable, documented, tested API.  More work might be needed to create a stable, tested, documented API ...

**Comment by AmeBel** [comment]
thanks I will add getters to _virtual or _fixed.
