### ISSUE TITLE
cog-execute! doesn't throw exception

### ISSUE THREAD

**Issue by AmeBel** [opencog/atomspace#663]
Don't know whether it is a bug or the wiki is outdated , but on following the [wiki](http://wiki.opencog.org/wikihome/index.php/Cog-execute!)
```scheme
scheme@(guile-user)> (use-modules (opencog) (opencog exec))
...
...

scheme@(guile-user)> (cog-execute! (ConceptNode "asdf"))
$1 = (ConceptNode "asdf")
```

**Comment by linas** [comment]
Not sure. Flip a coin.  We could take a hard line: concept nodes are not executable, and thus should throw an error.  We could be lenient: there are some complicated search patterns and bind-links that have to be executed, and when they run and are boiled down to something simpler, it resembles the execution of a concept node.  Since we want the complicated thing to "just work", it should not be an error.

Then we can flip-flop: if the complicated thing is like "execute concept" then the complicated thing is probably buggy, and it would be easier to debug if the error was thrown, instead of being silently ignored.

So... flip a coin.

**Comment by AmeBel** [comment]
I have added your explanation, to the wiki. Thanks
