### ISSUE TITLE
EinsteinUTest is running 10x slower.

### ISSUE THREAD

**Issue by linas** [opencog/atomspace#676]
EinsteinUTest normally runs in about 10 seconds; it currently is taking 95 seconds.  The change occurred in the last few weeks.

EinsteinUTest is sensitive to certain parts of the pattern-matcher internals.  

Its possible, but pure speculation that this is due to pull request #666  It could also be #673

**Comment by jswiergo** [comment]
This is caused by commit 5eb1fa04bbcc332151b5784

**Comment by inflector** [comment]
The devil's request strikes again. Commit 5eb1fa04bbcc332151b5784 was part of #666.

I'll check into this. Odd that it would still work but just be slower.

**Comment by inflector** [comment]
This is fixed in pull request #680.

The existing code to clear an atomspace was inefficient for transient atomspaces. So I moved the code for clear into the atom table since it was using all atom table methods anyway. Then use the much faster clearing code for transient spaces.

**Comment by linas** [comment]
OK, yes, this is fixed i issue #680.  I am not closing this just yet, though, because the fast-clear implemented in #680 leaves garbage in the incoming sets of atoms. This won't hurt operations at first, since weak pointers are ignored, but over time, I imagine a lot will pile up, chewing up RAM and hurting performance slightly.

**Comment by inflector** [comment]
Doesn't this code take care of that?

https://github.com/opencog/atomspace/blob/master/opencog/atomspace/AtomTable.cc#L179

It loops over the outgoing set of the atoms that are links and removes the link from the incoming sets of those atoms. I copied this from the destructor code.

**Comment by linas** [comment]
Oh, ah, right!  Yes, that looks like it will do the job. ... and we should use that for the regular clear as well. 

That is, use `clear_all_atoms` for the transient and the non-transient atomspaces, and for the non-transient ones, just call clear() on the assorted indexes. That will surely be faster than that `extract` loop that has that nasty `XXX FIXME` warning on it, anyway...

**Comment by inflector** [comment]
One semantic difference is that the other slow `clear()` is emitting signals for each atom as it is removed. 

I didn't know who is listening to those signals and what the implications of not emitting them for `clear()` would be.

**Comment by linas** [comment]
Heh. I'd very much like to remove support for those signals. I think its a mistake ... as far as I know, no one is using them, and they would have a sharp negative effect on performance if they were used. (because you'd have to wait for each callback handler to run!)  

In this case, I think we can just punt on this; in some distant future, if someone really really cares about atomspaces being deleted, well, we can solve that problem then.

**Comment by bgoertzel** [comment]
I think ECAN may be using those signals, you'd have to ask Misgana to be sure...

As I recall, the idea is that: the AttentionalFocus is a certain list of Atoms, and if an Atom is removed from the Atomspace, the AF should get a signal saying so, so that it can remove the Atom from the AF...

Also, if an Atom's importance gets below the AFThreshold, then a signal should be sent to remove it from the AF; and if an Atom's importance gets above the AFThreshold, then a signal should be sent to add it to the AF...

I may be remembering from a now-obsolete version of the code now.... And also, even if it is currently done this way, maybe there's a better design pattern to handle this....  If you have a better suggestion for doing the above stuff let Misgana &  Roman know as they will be refactoring ECAN a bit anyway...

**Comment by misgeatgit** [comment]
Hi Ben, Linas and Curtis, ECAN is using the atom added to AF signal for
creating HebbianLinks(
https://github.com/opencog/opencog/blob/master/opencog/attention/HebbianCreationModule.cc#L54).
So,
I don't think removing atom added and atom removed signals would be an
issue in the current code base unless there are some other parts using
those. However, I remember using the atom added signal code in my python
quantitative predicates implementation for updating truth values of the
predicates as new ExecutionLinks with QuantitativePredicat nodes arrive but
it is not merged and my approach might not be the best way to do it but
 still we might need these signals for other similar trigger update use
cases where the process occurs outside the AtomsPace class. For instance,
TV merging is a similar use case but it is handled inside the AtomSpace
class.

**Comment by inflector** [comment]
Running signals for the `clear()` case is different. Similar to signals running in the destructor for an AtomSpace. One calls  `clear()` to get rid of **all** the atoms. In both the ~AtomSpace and `clear()` cases, looping over all the atoms and then recursively deleting them via their outgoing sets and sending signals for each atom is a lot of extra work since they are all going away.

These cases are very distinct from a single atom going away, or a new one being added, which generally has something to do with knowledge updates. 

A `clear()` call, on the other hand, is almost always an algorithmic state reset over a temporary atomspace, most often in our code during unit tests, but also during pattern matches for transient atomspaces.

Do you want the signal handlers to run when all the atoms are going at once? Probably not. If you do want a signals at this time, you really just want one, one that tells you that all the atoms are going away.

**Comment by linas** [comment]
closing, fixed a while ago.
