### ISSUE TITLE
DefineLink full support

### ISSUE THREAD

**Issue by ngeiswei** [opencog/atomspace#74]
We're getting close to being able to use Atomese as a real programming language. It seems we still need to add (full) support for DefineLink.

I think the following wiki page

http://wiki.opencog.org/w/Definelink#SchemaNode

correctly defines what we want.

Do we agree on that?

Or do you think PutLink/GetLink can be substituted to DefineLink?

**Comment by ngeiswei** [comment]
## Subtasks
- [X] Generalize DefineLink to handle constants (addressed in PR #185)
- [ ] Add support for definition variables directly in the DefineLink in the case of function/predicate/etc definitions

**Comment by linas** [comment]
The contents of http://wiki.opencog.org/w/Definelink at this moment seem OK.  However ...

The place where DefineLink becomes interesting is in the pattern matcher: what happens when a pattern has define links in it? Should these be searched verbatim?  Should these be understood as defining sub-patterns to be searched for? If a patten is large and complex, it sure would be nice to build it out of smaller, simpler sub-patterns defined in a DefineLink.

Tangled up in the above is the notion of "beta reduction" aka "substitution" aka "composition": all three of these terms refer to the same idea:  given some expression containing x, substitute the value a for all occurrences of x (but do NOT do any further evaluation/execution; just substitute) -- this gets interesting if "a" is a the thing that is defined.

So, for example: the ExecutionOutputLink/SchemaNode example has two steps: a beta-reduction step, where the values 2 and 4 are substituted for X and Y, and then an execution step, where 2+ 4*10 is computed numerically.  It would be nice to have a BetaRedexLink or SubstitutionLink or CompisitionLink (or even a modified PutLink!!??) that only does the beta-reduction, and nothing else.

There are more tangles.  So, the SchemaNode example "works" because we "know" that, whenever we see a SchemaNode, that it was previously "defined" with a DefineLink (and that it is an error if a DefineLink cannot be found).    But what about the PredicateNode "MyPredicate" example?  So, every time that we see a PredicateNode, should we try to see if it is behing a DefineLink?  This would be very CPU-wasteful...  This suggests that the only things that can be "defined" are SchemaNodes, and maybe "DefinedPredicateNode"s and maybe, ummm.  "DefinedPatternNode" (for defining search patterns??)

One last remark:  I tried to solve some of the above while simultaneously writing the C++ implementation. What I often found was that, although my "theoretical" idea of how it should work was simple and clean, the C++ code became ugly. This was usually a signal that my "theoretical" notions were flawed.

One more last remark: the atomspace really really is a lot like "typed prolog" and it is very useful to study prolog, and see how it deals with these issues.  Also, studying MUMPS seems like a good idea (although I haven't done so myself) -- MUMPS faces and solves many of these same issues.

**Comment by ngeiswei** [comment]
OK, I understand the distinction you're making between BetaRedexLink and ExecutionOutputLink/ApplicationLink. In lambda calculus of course beta-reduction is equal to execution, or should I say repeated beta-reduction till normalization is reached and beta-reduction is no longer possible.

**Comment by ngeiswei** [comment]
So a BetaRedexLink represent a single beta-reduction (well possible several steps, as many as they are variables), but an ExecutionOutputLink/ApplicationLink represent a sequence of beta-reduction till completion.

Now if the body of a BetaRedexLink is a GSN, I guess OpenCog should treat it as if it were an ExecutionOutputLink/ApplicationLink, as it is a black box, there is no way to ask this black box to decompose it's execution into multiple beta-reductions. Right?

**Comment by linas** [comment]
On Thu, Aug 6, 2015 at 2:27 AM, ngeiswei <notifications@github.com> wrote:

> So a BetaRedexLink represent a single beta-reduction (well possible
> several steps, as many as they are variables),
>
Yes.

> but an ExecutionOutputLink/ApplicationLink represent a sequence of
> beta-reduction till completion.
>
No. Don't confuse beta-reduction with other kinds of reduction, of which
there are many ... an (uncountably) infinite number of.  Beta-reduction is
very narrowly defined simply as a substitution, and nothing more.

For opencog, for the atomspace, it makes sense to define four types of
reduction, I think:
-- beta-reduction (simple substitution)
-- execution (the result of which is an atom)
-- evaluation (the result of which is a TV)
-- "combo-reduct-style-reduction"  (the result is an atom, but the
resulting expression will typically still have variables in it.  By
contrast, in today's code, the cog-execute! will core-dump or puke or
error-out if variables remain).

Just to be concrete:  you might try to write 5*(x+2) like so:

ExecutionOutputLink
    GroundedSchemaNode "py: times"
    ListLink
         NumberNode 5
         ExecutionOutputLink
               GroundedSchemaNode "py: plus"
               ListLink
                      VariableNode x
                      NumberNode 2

but executing this will not give you the desired result of 5x+10

And even in algebra, there is no one single "desired result":  5x+10 is a
good reduction, but others are possible and might be more appropriate,
depending on the situation.   Thus, reduction is really about deciding
which reduction rules you want to apply, and when, and what you want your
final form to be.  e.g. for polynomials, do you want to to be fully
factored? Or fully expanded? Both are needed in different situations!  If
you are factoring, what is your splitting field? The complex numbers? Some
finite field?  etc.

Another example: scheme, lisp, haskell have a very extremely limited set of
reduction rules that are deeply hard-coded into these languages, in a way
that makes them impossible to alter.  This makes scheme, haskell, etc.
completely impossible to use for anything that needs different reduction
rules.  These languages fail to provide any mechanism for even specifying
the reduction to be applied: its a meta-issue, above and outside of these
languages.

So, for example, you cannot do symbolic algebra in haskell or scheme (but
you can *implement* a symbolic algebra system with the haskell programming
language -- not the same thing -- completely different situation), you
cannot do proof assistants.  You cannot do parsing.

By contrast, you can implement symbolic algebra in comboreduct: and indeed,
that is mostly what comboreduct currently does.  You could do proof
assistants, or parsing in cmboreduct.   That's because comboreduct makes
the reduction explicit, and under programmer control.  By contrast,
scheme/haskell completely hide the reduction deep, deep insides the guts.

So -- don't loose sigh of the above.

The URE, among other things, needs to be comboreduct-like in how it works.

Don't make the mental confusion that execution in opencog is the same as
running the URE.  executing something, and reducing it using the URE, are
very different.

Now if the body of a BetaRedexLink is a GSN, I guess OpenCog should treat
> it as if it were an ExecutionOutputLink/ApplicationLink, as it is a black
> box, there is no way to ask this black box to decompose it's execution into
> multiple beta-reductions. Right?
>
Again: scheme/haskell have a tiny number of reduction rules that are deeply
embedded into the language (and yes, beta reduction is one of them).  In
opencog, we are trying to build a URE so that its combo-reduct-like, so
that we can explicitly control the reductions to be applied, and the order
in which they are applied.  Oh, we even allow the user t specify their own
reductions (aka e-write rules).

**Comment by linas** [comment]
OK, so, in order to actually use DefineLink, I need to know an atom is a name for something else, so that I can chase down the DefineLink to get the definition.  To that end, I propose adding a NameNode or DefinitionNode or EntryNode or HandleNode to be the first atom. That way, every time I see a NameNode, I know "ah hah, let me look up it's definition".  That way, I don't waste CPU time checking every possible ConceptNode or whatever, to see if it's defined.

I plan to ad this in the next few hours; it seems like I need this for the robotics behavior work.

BTW, LambdaLink is now full implemented in exactly the way I think you would want it to be. Function composition is now done by PutLink, which mostly works the way you want function composition to work (I got lazy while implementing it and left off some type-checking bits.)  My goal it  to be able to combine DefineLink with PutLink and GetLink and have it work as expected.

**Comment by linas** [comment]
Oh wait .. I partly retract the above comment.  According to the wiki page, I should use PredicateNode or SchemaNode instead of NameNode.... so whenever I see PredicateNode, I should liik to see if its defined...

**Comment by ngeiswei** [comment]
@linas I assume you know what I'm about to say but just in case, there is a static method in DefineLink to get the body given an alias: https://github.com/opencog/atomspace/blob/master/opencog/atoms/core/DefineLink.h#L88-L97.

**Comment by linas** [comment]
pull requests #240 and #242 implement some of the work.

**Comment by linas** [comment]
Pull requests #304, #305 and #308 add support for DefinedSchemaNode.  As a result, the example at the bottom of the wiki page works.  I think that this means that essentially everything that needs to be done here is finished; thus I'm closing this.

There may still be bugs :-)

**Comment by ngeiswei** [comment]
Excellent, thanks!
