### ISSUE TITLE
Dual Link

### ISSUE THREAD

**Issue by wdevore** [opencog/atomspace#775]
In porting the code to Dart and merging the latest from the trunk I noticed that Dual_Link inherits from PatternLink in the code:
`class DualLink : public PatternLink`...

But the atom_types.script file specifies:
`DUAL_LINK <- SATISFYING_LINK`

Is this correct?

Wouldn't the code be:
`class DualLink : public SatisfyingLink`

**Comment by linas** [comment]
Hi, good observation .. except that not all of the atom types have a corresponding C++ class.

In fact, most atoms types don't have corresponding c++classes; the dozen that do, use the classes as "utilies" to cache intermediate results and avoid excess re-calculation.  

In the bigger putcture
```
SATISFYING_LINK <- PATTERN_LINK
DUAL_LINK <- SATISFYING_LINK
```

and since there is no SatisfyingLink C++ class, inheriting from PatternLink is OK.  (we could create an empty SatisfyingLink C++ class but that would be pointless)

**Comment by wdevore** [comment]
Thanks. Makes sense. I can now see how that applies to Value too.

**Comment by linas** [comment]
Closing, I think this is resolved.
