### ISSUE TITLE
Multiple PresentLink in a DefinedPredicate causes segfault

### ISSUE THREAD

**Issue by AmeBel** [opencog/atomspace#852]
## 1. Steps to reproduce the error
```scheme
scheme@(guile-user)> (use-modules (opencog) (opencog exec))
;;; note: auto-compilation is enabled, set GUILE_AUTO_COMPILE=0
;;;       or pass the --no-auto-compile argument to disable.
;;; compiling /usr/local/share/opencog/scm/opencog.scm
;;; opencog.scm:45:30: warning: possibly unbound variable `cog-atomspace'
....
....
scheme@(guile-user)> (DefineLink
...     (DefinedPredicateNode "just for testing")
...     (SatisfactionLink
...         (AndLink
...             ; If someone is visible...
...             (PresentLink (EvaluationLink (PredicateNode "visible face")
...                     (ListLink (VariableNode "$face-id-nn"))))
...             ; but not yet acknowledged...
...             (AbsentLink (EvaluationLink (PredicateNode "acked face")
...                     (ListLink (VariableNode "$face-id-nn"))))
...             ; and is recognizable
...             (PresentLink (EvaluationLink (PredicateNode "name")
...                     (ListLink
...                     (VariableNode "$face-id")
...                     (VariableNode "$recog-id"))))
...             (Not (Equal (VariableNode "$recog-id") (ConceptNode "0")))
...             )))
$1 = (DefineLink
   (DefinedPredicateNode "just for testing")
   (SatisfactionLink
      (AndLink
         (PresentLink
            (EvaluationLink
               (PredicateNode "visible face")
               (ListLink
                  (VariableNode "$face-id-nn")
               )
            )
         )
         (AbsentLink
            (EvaluationLink
               (PredicateNode "acked face")
               (ListLink
                  (VariableNode "$face-id-nn")
               )
            )
         )
         (PresentLink
            (EvaluationLink
               (PredicateNode "name")
               (ListLink
                  (VariableNode "$face-id")
                  (VariableNode "$recog-id")
               )
            )
         )
         (NotLink
            (EqualLink
               (VariableNode "$recog-id")
               (ConceptNode "0")
            )
         )
      )
   )
)

scheme@(guile-user)> (cog-evaluate! (DefinedPredicateNode "just for testing"))
Segmentation fault (core dumped)
```
## 2 Expected result
```
scheme@(guile-user)> (cog-evaluate! (DefinedPredicateNode "just for testing"))
$2 = (stv 0 1)
```

**Comment by linas** [comment]
looking

**Comment by linas** [comment]
pull req #853 fixes this.

Its not the multiple PresentLinks, its the EqualLink that cause the issue -- the pattern got split into multiple components.  (although that too is a bug .. it should really be a single-component pattern. I'm looking into that now.

**Comment by linas** [comment]
Ah! BTW, your example above has a bug in it -- the third variable should be `(VariableNode "$face-id-nn")` instead of `(VariableNode "$face-id")`   This bug was triggering the multi-component path.

There is some code that actually checks for this syntax error, and would catch it and report it -- but it got disabled, because PLN intentionally constructs such invalid graphs, and still expects them to work right :-(

Also BTW, you can get a minor performance boost by using IdenticalLink instead of EqualLink.  See http://wiki.opencog.org/wikihome/index.php/EqualLink

**Comment by AmeBel** [comment]
No, the third variable is `(VariableNode "$face-id")`. The DefinedPredicate is not complete, I kept the ugly part for a pr :-). To reproduce the bug the `(Not (Equal..` wasn't needed.

What is an invalid graph? Do you mean a graph which doesn't make semantic sense?

Thanks on the fix and hint :-)

**Comment by linas** [comment]
well, the graph has two disconnected parts. You're right, its not the EqualLink, I thought that was the reason it had two disconnected parts until I saw the mis-matched names.  The bug triggered because it has two independent parts, one not linked to the other.  Changedin the variable names links them back into one.

Anyway, it should all work now.

**Comment by linas** [comment]
closing I believe this is fixed
