### ISSUE TITLE
psql peer authentication failed

### ISSUE THREAD

**Issue by beew** [opencog/atomspace#880]
Hi, I am trying to compile atomspace, but keep getting these warnings 

```
CMake Warning at tests/persist/sql/odbc/CMakeLists.txt:67 (MESSAGE):
  /usr/bin/psql: psql: FATAL: Peer authentication failed for user
  "opencog_user"
```

I have set up postresql according to the Readme in atomspace/opencog/persist/sql 
and I have edited atomspace-test in atomspace/lib and the CMakelists.txt files in atomspace/tests/persist/sql/ , atomspace/tests/persist/sql/odbc accordingly. 

Note: the readme is not consistent, it uses opencog_user in the example template but elsewhere another readme uses opencog_tester and so do the CMakelists.txt 

OS is Ubuntu 16.04 64 bit, cmake 3.5.1

**Comment by jswiergo** [comment]
Try to use 'opencog_tester' login for database and do not change this login in the source code. Check this Readme:
https://github.com/opencog/atomspace/blob/master/tests/persist/sql/README

**Comment by beew** [comment]
I did. Got the same error. Also only "opencog_user" has been created for the db as per the other readme and it says I should edit the source for it to be the same !

**Comment by linas** [comment]
I just added a postgres driver, so that odbc can be completely avoided.  That should sharply simplify configuration mistakes.

-- please try it!
-- you'll need to install libpq-dev for it to compile.
-- you'll need to make clean also
-- please make sure that the unit tests pass.  There are four of them, they should pass.
