### ISSUE TITLE
Implement alpha-conversion

### ISSUE THREAD

**Issue by ngeiswei** [opencog/atomspace#895]
If I'm correct we have no method to perform alpha-conversion. We have methods to test alpha-equivalence
`Variables::is_equal` and `ScopeLink::is_equal`, but none for alpha-conversion.

@linas I noticed this comment in

https://github.com/opencog/atomspace/blob/master/opencog/atomspace/AtomTable.cc#L392

which means that you have at least considered coding one. Although I wonder if we want to do this on the fly, it smells like trouble to me, better be explicit at the AtomSpace level and if necessary have agents take care of it as a higher level process, what do you think?

# Proposal

Implement alpha-conversion functions to rename variables so that they do not collide with a set of given variables, or the whole atomspace, or using some SHA key to be almost certain to avoid collision.

```
Rule::gen_standardize_apart
```

does already somewhat this, but it's such a general function that it should be moved somewhere else (with a more generic API). @linas where do you think the right place for such a function should be? `atomutils`?

**Comment by ngeiswei** [comment]
Hmm, I think you want to perform alpha-conversion of a ScopeLink at a time (or possibly all scopes links, optionally), so maybe it could be by under it, something like

```
ScopeLink ScopeLink::alpha_conversion(<arguments>);
```

That is, given a ScopeLink object one could call this method to create an alpha-converted clone of it. What do you think?

**Comment by ngeiswei** [comment]
Could take a flag `recursive` in argument to perform alpha-conversion of all descendant scope links as well, etc.

**Comment by linas** [comment]
What is the actual problem that you are trying to solve? The ScopeLink is, ***by definition*** that link which hides all variables underneath it; that's all it does, nothing more, nothing less. Conceptually, is as if the variables appearing in a scope link were alpha-converted to some new name that is guaranteed to never-ever collide with any other variables during evaluation/execution.

In practice, the way I handle this is not by explicitly, actually performing that alpha-conversion, but instead ignoring those variables during searches for free variables. So e.g. during unification, one would bump into a scope link, and say "oh gee lookit, I had better not try to unify these variables here".  So far, this ignore-and-handle strategy seems to work fine.

Conversely, hacking the ScopeLink C++ constructor to replace all occurrences of Variable "$x" to Variable "$x-6740cbbbd85200759bcdbdaa3901e390" does not in any way solve the unification problem, or any other free-variable-search problems. It also has the very unfortunate side-effect of taking a human-readable Variable "$x" into a "where in the wtf is this variable I know its in here somewhere but I can't find it" type of debugging situation. 

Its for this reason that I would be against any sort of explicit, actual alpha-conversion: I don't see that it actually solves any problems we actually have. So again: what is the actual problem?

**Comment by linas** [comment]
Also: explicit alpha-conversion potentially wreaks havoc with persistence.  So, If I have a ScopeLink (or some other link, where alpha-conversion is being explicitly done) and I save it to disk, and then I restore it from disk, should I alpha-convert it again? What happens if I save that?  It gets even worse: Suppose I have some link, and all I want to do is to get that link from the disk, update it's TV, and store it back to disk.  How do I know what to look for? Do I need to create a special alpha-equivalence search for the SQL backend, that will search for and find all possible ScopeLinks that have the same shape, but different  variable names?  That has the potential of turning into quite the mess...

**Comment by linas** [comment]
FYI: both C++ `class ScopeLink` and `class Variables` have a method `is_equal()` that returns true, if two instances are equivalent, up to alpha-conversion.

**Comment by ngeiswei** [comment]
@linas, I agree with you on all points. The problems comes when combining 2 ScopeLinks to create a new one.

Let me give an example in the context of the backward chainer:

Assume we want to prove
```
A->B
```

For that we can use the deduction rule

```
X->Y
Y->Z
|-
X->Z
```

The result of the unification of its target leads to the following rule

```
A->Y
Y->B
|-
A->B
```

but suppose that such premises are not groundable yet, they we need to expand some premises as well, say A->Y, choose it as target and produce

```
A->Z
Z->Y
|-
A->Y
```

you can see that we can no longer use the same variable name Y while producing this ScopeLink because it would collide with the previous Y, so I choose Z.

**Comment by ngeiswei** [comment]
So, back to initial question, where the code of the such function/method should be?

**Comment by ngeiswei** [comment]
Well, the other option is to have the unifier take care of that alpha-conversion on the fly, but I'd rather have these split in different functions, would that be just for the sake of code clarity.

Also, to be clear, the alpha-conversion would copy-alpha-convert, not alpha-convert the ScopeLink object itself (which requires to rewrite all its incoming links, etc).

**Comment by linas** [comment]
You've described the problem too abstractly for me to guess what the problem is. I can see that you are trying to chain the premises together, and I can see that, conceptually, you want Z to be different from Y, but I don't see how that could ever matter in actual code. Are you saying that you are creating brand-new scope-links on the fly, and getting variable collisions in them?  If so, can't you just create some new temporary variable name on the fly?

**Comment by ngeiswei** [comment]
Yes, I'm creating brand new scope links on the fly and want to avoid variable name collision.

Yes, I could generate new variable names on the fly (not that they are not necessarily temporary, they live for the duration of the back inference tree, possibly forever), as I said I'd rather have that be done in a separate function, just for the sake of code clarity, and that function would be rightly called, alpha-conversion, and thus deserves to be located somewhere else than the URE given how generic it is.

**Comment by ngeiswei** [comment]
It's pretty clear to me that such a function will be re-used in the future, another good reason to be located at the right place.

**Comment by linas** [comment]
Arghh. My main computer is crashing daily, now, I hope it is not a hardware fault. Crashed mid-reply.

The unifier -- I haven't read the code, but I assume that it stops whenever it gets to a scope-link, and does not try to explore the body of the scope link. If it is exploring the interior of a scope link, that would be bad.  To create a new scope link on the fly, you just need an eval method to "paste" constants in for selected variables, creating a new scope link. That eval method exists and is heavily used, but may be mis-located somewhere, possibly it might be living in the lambda-link code base.  But if you create a new scope link, with some constants substituted in for some variables, (i.e. beta-reduced) I see no harm in re-using a variable name -- next time that you unify, the unifier would "know" that the variables in a scope link cannot possibly be the "same" as free variables living outside the scope link (even though they accidentally might have the same name). 

So, given teh way you are talking about this, I get the impression that the unifier has a bug: it is accidentally mistaking the free variable, which happens to be called "x", with a bound variable, which happens to also be called "x". But that is a mistake: even though they have the same name, we know they cannot possibly ever be the same variable, and so the unifier should not mistake the one for the other...

**Comment by linas** [comment]
anyway, that's my last reply for the night.  Yes, LambdaLink.h has a `substitute()` method on it that replaces variables with values.  I believe it works fine if you only provide values for some but not all variables. I suppose that method maybe should be moved to ScopeLink, maybe?  Or maybe ask yourself if you should be using Lambda instead of Scope, instead?

**Comment by linas** [comment]
Aiee -- I take that back, what I said about exploring the interior of a scope link ... that's just wrong, as otherwise, you cannot match.  I am thinking that perhaps the ScopeLink itself should get a new method, similar to `is_equal()`, but maybe called `is_unifiable()` that returns the true/false if a match is possible...

**Comment by ngeiswei** [comment]
I've been thinking a bit more, and I really don't like the idea of the unifier doing alpha-conversion on the fly, I think it is too confusing for the user. Imagine unification is called as follow
```
arg1 = ScopeLink
   Variable X
   Inheritance
      A
      X
,
arg2 = ScopeLink
   Variable X
   Inheritance
      X
      B
```
the result as currently coded should be the typed equality partition
```
{{X (from arg1), B}:B, {X (from arg2), A}:A}
```
where `:A` and `:B` are the types of the partitions blocks.

You can see I have 2 options:

1. Forbid name collision
2. Have the unification rename the colliding variables on the fly (that is `X` is renamed by `X (from arg1)`, or whichever random name is generated).

I think having the unification rename the variables on the fly is very confusing to the user, even worse is that the solution set now refers to atoms not provided by the user, very confusing when the user needs the solution set to build other atoms (as the BC does).

So I'm even surer now, we need an standalone alpha-converter.

I'll study the ScopeLink (possibly the LambdaLink) code to see if that would be the right place, otherwise I'll put that under atomutils.

**Comment by ngeiswei** [comment]
Hmm, the other option is to have the solution set replace the variable by a pair (variable, associated scope), like
```
{{(X, <scope from arg1>), B}:B, {(X, <scope from arg2>, A}:A}
```
The thing though is ultimately the BC will have to rename these conflicting variables, so why not do that head on before even calling the unifier.

Anyway, so yeah, for sake of simplicity I'll go with 1. forbid name collision, and implement standalone alpha-conversion.

**Comment by ngeiswei** [comment]
I think it makes sense to have this function as a `ScopeLink` method. For that, `Variables::substitute` would be very handy (especially cause it properly supports escaping quoted and scoped variables) but I need to change it a bit so that it supports substituting variables by other variables, not just values, which Variables::is_type does not support.

I'm gonna attempt to update Variables::is_type and hope it does not yield a cascade of failures.

**Comment by ngeiswei** [comment]
No, stupid me! I will use `substitute_nocheck`!

**Comment by linas** [comment]
Hey Nil,

You still haven't clearly explained what the actual problem is, that you are trying to solve. 

From what I understand, adding an "is_unifiable()" method to the ScopeLink class will provide everything that you need, without requiring any sort of explicit alpha conversion to take place.

From where I sit, explicit alpha conversion is a huge evil, as explained above: it makes the atomspace completely unmanageable and undebuggable. The users will find it completely confusing, because what the atomspace contains will not match up with any reasonable expectations of what one would think it contains. Between the fact that its confusing to users, and its hard for the system developers, I still strongly suggest against it.

Again: what, exactly, is the problem that you are trying to solve, here?
