### ISSUE TITLE
Bug in ScopeLink::is_equal

### ISSUE THREAD

**Issue by ngeiswei** [opencog/atomspace#896]
Due to `ScopeLink` assuming only a single body`ScopeLink::is_equal` fails to properly check the alpha-equivalence of scope links with multiple bodies, such as bind links. 

I suggest to replace
```c++
Handle ScopeLink::_body
```
by
```c++
HandleSeq ScopeLink::_bodies
```
and update `ScopeLink::is_equal` appropriately. This might also simplify the code of the classes inheriting from ScopeLink as we won't need special treatments for scope links with more than 1 body.

**Comment by linas** [comment]
what the heck is "multiple bodies"? ??? what can that possibly even mean? What is the semantics of that? Is there an implied AndLink between all of the bodies? An implicit Implication link between the bodies? Can there be more than two bodies? Can one choose which body one feels like working with, or does one have to use all of the bodies, in some unspecified way ???  What should one do, if one finds more than one body?

Before you identify problems and alter existing code that is used in the existing code base, with real, fixed semantics, some discussion would be good -- in this case, I cannot begin to imagine what "mutiple bodies" might even mean.

In some of these cases, it would probably be better to invent a new link type, instead of forcing changes onto a well-defined existing link.  "MultiBoduyScopeLink" comes to mind.

**Comment by linas** [comment]
I mean -- if you want to have Set semantics, stick all the bodies in a SetLink, and put the SetLink  into the ScopeLink.  If you want an ordered set, use ListLink.  Of you want to have boolean semantics, stick them in and AndlInk or OrLink and jam that into the ScopeLink.  If you want choice semantics, stick them in a ChoiceLink. If you want Implication semantics, stick them in an ImplicationLink. If you want predicate semantics, stick them in an EvaluationLink.  If you need to invent a new link type. But please don't do what you just did.

I strongly suggest reverting this, and switching up the code to use the correct link type for whatever you are trying to do.

**Comment by ngeiswei** [comment]
Bodies were supposed to mean anything that isn't a variable declaration, for instance in a BindLink _bodies[1] would be the implicant.

But anyway, I've just realized this was not a good idea and there is a much simpler fix to #899 . The reason I persisted in this way is because of the initial conviction that it would simplify the code of ScopeLink and its inherited classes. Might still be true, but it's less obvious than I thought and it requires extra work that I'd rather spend on something else.
