### ISSUE TITLE
VariableLink

### ISSUE THREAD

**Issue by rTreutlein** [opencog/atomspace#969]
Has there been given any thought on VariableLinks? It seems to be necessary for certain cases to be able to search for patterns with VariableLinks.

Specifically, in Lojban, you can ask how 2 things are logically related.

```
mi                ji                 do     klama     ti
I     "connected in what way with"   you     go     there?
```

Which I would like to translate to the following pattern.

```
EvaluationLink
	PredicateNode "klama"
	ListLink 
		VariableLink
			ConceptNode "mi"
			ConceptNode "do"
		ConceptNode "ti"
```

Obviously, I would also need to specify a VariableType to not match everything.

    
Something, where this could also be useful, is the "junctor-lambda-distribution-fact" in PLN. As this currently, generates multiple facts/rules for different LinkTypes.

**Comment by linas** [comment]
You'd have to elaborate the example a bit more. I don't understand why the following won't work for binary relations:
```
EvaluationLink
    PredicateNode "some_relation"
    ListLink
          ConceptNode "mi"
          ConceptNode "do"
```

More generally, for language relations, you probably want to use link-grammar style disjuncts, instead of using EvaluationLinks and PredicateNodes.  The disjunct style will in general be more powerful and flexible.  The point here is that  EvaluationLinks and PredicateNodes were never designed for hierarchical use; the example is "badly formed" and will sooner or later lead to trouble and madness.  Best to keep depth in the outgoing-set direction as flat as possible, and put all complexity into the incoming set.

But if you must, I think that the "deep types" should work too, although this code is under-tested and might be buggy. Might not even be code-complete --you would be the first or one of the first users.  So, something like this:
```
 GetLink
    TypedVariableLink
        VariableNode  "$foo"
        TypeChoice
              SignatureLink
                   SomeLink
                         ConceptNode "mi"
                         ConceptNode "do"
              SignatureLink
                   OtherLink
                         ConceptNode "mi"
                         ConceptNode "do"   

  EvaluationLink
	PredicateNode "klama"
	ListLink 
		VariableNode $foo
		ConceptNode "ti"          
```
The above says that the variable $foo has to one of the two link types.

The above should be equivalent to this:
```
 GetLink
    TypedVariableLink
        VariableNode  "$foo"
         SignatureLink
              TypeChoice
                   TypeNode "SomeLink"
                   TypeNode "OtherLink"
               ConceptNode "mi"
               ConceptNode "do"

  EvaluationLink
	PredicateNode "klama"
	ListLink 
		VariableNode $foo
		ConceptNode "ti"          
```

The above is supposed to work.. don't know if it does. Its documented here:
http://wiki.opencog.org/w/SignatureLink
http://wiki.opencog.org/w/Type_checker

and is implemented in  atomutils/TypeUtils.cc  atoms/core/TypedAtomLink.cc and atoms/core/VariableList.cc

**Comment by rTreutlein** [comment]
Well the links I am looking for in this case are mainly AndLink and OrLink and I guess I could make a PredicateNode "And" not sure if that is such a good idea when we already have it as primitives.

But the deep-types seem to do what I want. I'll play around with that and try to make it work.

**Comment by linas** [comment]
closing, this was a question and appears to have been answered.
